/* tslint:disable */
/* eslint-disable */
/**
 * Saved API
 * encrypted backups and distributed storage
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  DownloadBackup200Response,
  RequestBackup201Response,
} from '../models/index';
import {
    DownloadBackup200ResponseFromJSON,
    DownloadBackup200ResponseToJSON,
    RequestBackup201ResponseFromJSON,
    RequestBackup201ResponseToJSON,
} from '../models/index';

export interface DeleteBackupRequest {
    workspaceId: string;
    jobId: string;
    backupId: string;
}

export interface DownloadBackupRequest {
    workspaceId: string;
    jobId: string;
    backupId: string;
}

export interface GetBackupRequest {
    workspaceId: string;
    jobId: string;
    backupId: string;
}

export interface ListBackupsRequest {
    workspaceId: string;
    jobId: string;
    limit?: number;
    offset?: number;
}

/**
 * BackupsApi - interface
 * 
 * @export
 * @interface BackupsApiInterface
 */
export interface BackupsApiInterface {
    /**
     * 
     * @summary Delete a backup
     * @param {string} workspaceId The unique identifier of the workspace.
     * @param {string} jobId The unique identifier of the job.
     * @param {string} backupId The unique identifier of the backup.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BackupsApiInterface
     */
    deleteBackupRaw(requestParameters: DeleteBackupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Delete a backup
     */
    deleteBackup(workspaceId: string, jobId: string, backupId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @summary Download a backup
     * @param {string} workspaceId The unique identifier of the workspace.
     * @param {string} jobId The unique identifier of the job.
     * @param {string} backupId The unique identifier of the backup.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BackupsApiInterface
     */
    downloadBackupRaw(requestParameters: DownloadBackupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DownloadBackup200Response>>;

    /**
     * Download a backup
     */
    downloadBackup(workspaceId: string, jobId: string, backupId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DownloadBackup200Response>;

    /**
     * 
     * @summary Get a backup
     * @param {string} workspaceId The unique identifier of the workspace.
     * @param {string} jobId The unique identifier of the job.
     * @param {string} backupId The unique identifier of the backup.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BackupsApiInterface
     */
    getBackupRaw(requestParameters: GetBackupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestBackup201Response>>;

    /**
     * Get a backup
     */
    getBackup(workspaceId: string, jobId: string, backupId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestBackup201Response>;

    /**
     * 
     * @summary List backups for a job
     * @param {string} workspaceId The unique identifier of the workspace.
     * @param {string} jobId The unique identifier of the job.
     * @param {number} [limit] The number of items to return.
     * @param {number} [offset] The number of items to skip.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BackupsApiInterface
     */
    listBackupsRaw(requestParameters: ListBackupsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<RequestBackup201Response>>>;

    /**
     * List backups for a job
     */
    listBackups(workspaceId: string, jobId: string, limit?: number, offset?: number, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<RequestBackup201Response>>;

}

/**
 * 
 */
export class BackupsApi extends runtime.BaseAPI implements BackupsApiInterface {

    /**
     * Delete a backup
     */
    async deleteBackupRaw(requestParameters: DeleteBackupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['workspaceId'] == null) {
            throw new runtime.RequiredError(
                'workspaceId',
                'Required parameter "workspaceId" was null or undefined when calling deleteBackup().'
            );
        }

        if (requestParameters['jobId'] == null) {
            throw new runtime.RequiredError(
                'jobId',
                'Required parameter "jobId" was null or undefined when calling deleteBackup().'
            );
        }

        if (requestParameters['backupId'] == null) {
            throw new runtime.RequiredError(
                'backupId',
                'Required parameter "backupId" was null or undefined when calling deleteBackup().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/workspaces/{workspace_id}/jobs/{job_id}/backups/{backup_id}`;
        urlPath = urlPath.replace(`{${"workspace_id"}}`, encodeURIComponent(String(requestParameters['workspaceId'])));
        urlPath = urlPath.replace(`{${"job_id"}}`, encodeURIComponent(String(requestParameters['jobId'])));
        urlPath = urlPath.replace(`{${"backup_id"}}`, encodeURIComponent(String(requestParameters['backupId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a backup
     */
    async deleteBackup(workspaceId: string, jobId: string, backupId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteBackupRaw({ workspaceId: workspaceId, jobId: jobId, backupId: backupId }, initOverrides);
    }

    /**
     * Download a backup
     */
    async downloadBackupRaw(requestParameters: DownloadBackupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DownloadBackup200Response>> {
        if (requestParameters['workspaceId'] == null) {
            throw new runtime.RequiredError(
                'workspaceId',
                'Required parameter "workspaceId" was null or undefined when calling downloadBackup().'
            );
        }

        if (requestParameters['jobId'] == null) {
            throw new runtime.RequiredError(
                'jobId',
                'Required parameter "jobId" was null or undefined when calling downloadBackup().'
            );
        }

        if (requestParameters['backupId'] == null) {
            throw new runtime.RequiredError(
                'backupId',
                'Required parameter "backupId" was null or undefined when calling downloadBackup().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/workspaces/{workspace_id}/jobs/{job_id}/backups/{backup_id}/download`;
        urlPath = urlPath.replace(`{${"workspace_id"}}`, encodeURIComponent(String(requestParameters['workspaceId'])));
        urlPath = urlPath.replace(`{${"job_id"}}`, encodeURIComponent(String(requestParameters['jobId'])));
        urlPath = urlPath.replace(`{${"backup_id"}}`, encodeURIComponent(String(requestParameters['backupId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DownloadBackup200ResponseFromJSON(jsonValue));
    }

    /**
     * Download a backup
     */
    async downloadBackup(workspaceId: string, jobId: string, backupId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DownloadBackup200Response> {
        const response = await this.downloadBackupRaw({ workspaceId: workspaceId, jobId: jobId, backupId: backupId }, initOverrides);
        return await response.value();
    }

    /**
     * Get a backup
     */
    async getBackupRaw(requestParameters: GetBackupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestBackup201Response>> {
        if (requestParameters['workspaceId'] == null) {
            throw new runtime.RequiredError(
                'workspaceId',
                'Required parameter "workspaceId" was null or undefined when calling getBackup().'
            );
        }

        if (requestParameters['jobId'] == null) {
            throw new runtime.RequiredError(
                'jobId',
                'Required parameter "jobId" was null or undefined when calling getBackup().'
            );
        }

        if (requestParameters['backupId'] == null) {
            throw new runtime.RequiredError(
                'backupId',
                'Required parameter "backupId" was null or undefined when calling getBackup().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/workspaces/{workspace_id}/jobs/{job_id}/backups/{backup_id}`;
        urlPath = urlPath.replace(`{${"workspace_id"}}`, encodeURIComponent(String(requestParameters['workspaceId'])));
        urlPath = urlPath.replace(`{${"job_id"}}`, encodeURIComponent(String(requestParameters['jobId'])));
        urlPath = urlPath.replace(`{${"backup_id"}}`, encodeURIComponent(String(requestParameters['backupId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestBackup201ResponseFromJSON(jsonValue));
    }

    /**
     * Get a backup
     */
    async getBackup(workspaceId: string, jobId: string, backupId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestBackup201Response> {
        const response = await this.getBackupRaw({ workspaceId: workspaceId, jobId: jobId, backupId: backupId }, initOverrides);
        return await response.value();
    }

    /**
     * List backups for a job
     */
    async listBackupsRaw(requestParameters: ListBackupsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<RequestBackup201Response>>> {
        if (requestParameters['workspaceId'] == null) {
            throw new runtime.RequiredError(
                'workspaceId',
                'Required parameter "workspaceId" was null or undefined when calling listBackups().'
            );
        }

        if (requestParameters['jobId'] == null) {
            throw new runtime.RequiredError(
                'jobId',
                'Required parameter "jobId" was null or undefined when calling listBackups().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/workspaces/{workspace_id}/jobs/{job_id}/backups`;
        urlPath = urlPath.replace(`{${"workspace_id"}}`, encodeURIComponent(String(requestParameters['workspaceId'])));
        urlPath = urlPath.replace(`{${"job_id"}}`, encodeURIComponent(String(requestParameters['jobId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(RequestBackup201ResponseFromJSON));
    }

    /**
     * List backups for a job
     */
    async listBackups(workspaceId: string, jobId: string, limit?: number, offset?: number, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<RequestBackup201Response>> {
        const response = await this.listBackupsRaw({ workspaceId: workspaceId, jobId: jobId, limit: limit, offset: offset }, initOverrides);
        return await response.value();
    }

}
