/* tslint:disable */
/* eslint-disable */
/**
 * Saved API
 * Microservices-based backup and vault management platform with encrypted backups and distributed storage
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ConfirmBackupUploaded200Response,
  ConfirmBackupUploadedRequest,
  CreateBackupRequest,
  ListBackups200Response,
  ListBackups200ResponseAllOfItemsInner,
  ListWorkspaces401Response,
  RequestBackupCopy200Response,
} from '../models/index';
import {
    ConfirmBackupUploaded200ResponseFromJSON,
    ConfirmBackupUploaded200ResponseToJSON,
    ConfirmBackupUploadedRequestFromJSON,
    ConfirmBackupUploadedRequestToJSON,
    CreateBackupRequestFromJSON,
    CreateBackupRequestToJSON,
    ListBackups200ResponseFromJSON,
    ListBackups200ResponseToJSON,
    ListBackups200ResponseAllOfItemsInnerFromJSON,
    ListBackups200ResponseAllOfItemsInnerToJSON,
    ListWorkspaces401ResponseFromJSON,
    ListWorkspaces401ResponseToJSON,
    RequestBackupCopy200ResponseFromJSON,
    RequestBackupCopy200ResponseToJSON,
} from '../models/index';

export interface ConfirmBackupUploadedOperationRequest {
    workspaceId: string;
    projectId: string;
    backupId: string;
    confirmBackupUploadedRequest: ConfirmBackupUploadedRequest;
}

export interface CreateBackupOperationRequest {
    workspaceId: string;
    projectId: string;
    createBackupRequest: CreateBackupRequest;
}

export interface GetBackupRequest {
    workspaceId: string;
    projectId: string;
    backupId: string;
}

export interface ListBackupsRequest {
    workspaceId: string;
    projectId: string;
    page?: number;
    limit?: number;
}

export interface RequestBackupCopyRequest {
    workspaceId: string;
    projectId: string;
    backupId: string;
}

/**
 * BackupsApi - interface
 * 
 * @export
 * @interface BackupsApiInterface
 */
export interface BackupsApiInterface {
    /**
     * 
     * @summary Confirm backup uploaded
     * @param {string} workspaceId 
     * @param {string} projectId 
     * @param {string} backupId 
     * @param {ConfirmBackupUploadedRequest} confirmBackupUploadedRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BackupsApiInterface
     */
    confirmBackupUploadedRaw(requestParameters: ConfirmBackupUploadedOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConfirmBackupUploaded200Response>>;

    /**
     * Confirm backup uploaded
     */
    confirmBackupUploaded(workspaceId: string, projectId: string, backupId: string, confirmBackupUploadedRequest: ConfirmBackupUploadedRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConfirmBackupUploaded200Response>;

    /**
     * 
     * @summary Create backup (request upload)
     * @param {string} workspaceId 
     * @param {string} projectId 
     * @param {CreateBackupRequest} createBackupRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BackupsApiInterface
     */
    createBackupRaw(requestParameters: CreateBackupOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListBackups200ResponseAllOfItemsInner>>;

    /**
     * Create backup (request upload)
     */
    createBackup(workspaceId: string, projectId: string, createBackupRequest: CreateBackupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListBackups200ResponseAllOfItemsInner>;

    /**
     * 
     * @summary Get backup by ID
     * @param {string} workspaceId 
     * @param {string} projectId 
     * @param {string} backupId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BackupsApiInterface
     */
    getBackupRaw(requestParameters: GetBackupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListBackups200ResponseAllOfItemsInner>>;

    /**
     * Get backup by ID
     */
    getBackup(workspaceId: string, projectId: string, backupId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListBackups200ResponseAllOfItemsInner>;

    /**
     * 
     * @summary List backups
     * @param {string} workspaceId 
     * @param {string} projectId 
     * @param {number} [page] 
     * @param {number} [limit] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BackupsApiInterface
     */
    listBackupsRaw(requestParameters: ListBackupsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListBackups200Response>>;

    /**
     * List backups
     */
    listBackups(workspaceId: string, projectId: string, page?: number, limit?: number, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListBackups200Response>;

    /**
     * 
     * @summary Request backup copy for download
     * @param {string} workspaceId 
     * @param {string} projectId 
     * @param {string} backupId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BackupsApiInterface
     */
    requestBackupCopyRaw(requestParameters: RequestBackupCopyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestBackupCopy200Response>>;

    /**
     * Request backup copy for download
     */
    requestBackupCopy(workspaceId: string, projectId: string, backupId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestBackupCopy200Response>;

}

/**
 * 
 */
export class BackupsApi extends runtime.BaseAPI implements BackupsApiInterface {

    /**
     * Confirm backup uploaded
     */
    async confirmBackupUploadedRaw(requestParameters: ConfirmBackupUploadedOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConfirmBackupUploaded200Response>> {
        if (requestParameters['workspaceId'] == null) {
            throw new runtime.RequiredError(
                'workspaceId',
                'Required parameter "workspaceId" was null or undefined when calling confirmBackupUploaded().'
            );
        }

        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling confirmBackupUploaded().'
            );
        }

        if (requestParameters['backupId'] == null) {
            throw new runtime.RequiredError(
                'backupId',
                'Required parameter "backupId" was null or undefined when calling confirmBackupUploaded().'
            );
        }

        if (requestParameters['confirmBackupUploadedRequest'] == null) {
            throw new runtime.RequiredError(
                'confirmBackupUploadedRequest',
                'Required parameter "confirmBackupUploadedRequest" was null or undefined when calling confirmBackupUploaded().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/workspaces/{workspace_id}/projects/{project_id}/backups/{backup_id}/confirm`;
        urlPath = urlPath.replace(`{${"workspace_id"}}`, encodeURIComponent(String(requestParameters['workspaceId'])));
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));
        urlPath = urlPath.replace(`{${"backup_id"}}`, encodeURIComponent(String(requestParameters['backupId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ConfirmBackupUploadedRequestToJSON(requestParameters['confirmBackupUploadedRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConfirmBackupUploaded200ResponseFromJSON(jsonValue));
    }

    /**
     * Confirm backup uploaded
     */
    async confirmBackupUploaded(workspaceId: string, projectId: string, backupId: string, confirmBackupUploadedRequest: ConfirmBackupUploadedRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConfirmBackupUploaded200Response> {
        const response = await this.confirmBackupUploadedRaw({ workspaceId: workspaceId, projectId: projectId, backupId: backupId, confirmBackupUploadedRequest: confirmBackupUploadedRequest }, initOverrides);
        return await response.value();
    }

    /**
     * Create backup (request upload)
     */
    async createBackupRaw(requestParameters: CreateBackupOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListBackups200ResponseAllOfItemsInner>> {
        if (requestParameters['workspaceId'] == null) {
            throw new runtime.RequiredError(
                'workspaceId',
                'Required parameter "workspaceId" was null or undefined when calling createBackup().'
            );
        }

        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling createBackup().'
            );
        }

        if (requestParameters['createBackupRequest'] == null) {
            throw new runtime.RequiredError(
                'createBackupRequest',
                'Required parameter "createBackupRequest" was null or undefined when calling createBackup().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/workspaces/{workspace_id}/projects/{project_id}/backups`;
        urlPath = urlPath.replace(`{${"workspace_id"}}`, encodeURIComponent(String(requestParameters['workspaceId'])));
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateBackupRequestToJSON(requestParameters['createBackupRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListBackups200ResponseAllOfItemsInnerFromJSON(jsonValue));
    }

    /**
     * Create backup (request upload)
     */
    async createBackup(workspaceId: string, projectId: string, createBackupRequest: CreateBackupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListBackups200ResponseAllOfItemsInner> {
        const response = await this.createBackupRaw({ workspaceId: workspaceId, projectId: projectId, createBackupRequest: createBackupRequest }, initOverrides);
        return await response.value();
    }

    /**
     * Get backup by ID
     */
    async getBackupRaw(requestParameters: GetBackupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListBackups200ResponseAllOfItemsInner>> {
        if (requestParameters['workspaceId'] == null) {
            throw new runtime.RequiredError(
                'workspaceId',
                'Required parameter "workspaceId" was null or undefined when calling getBackup().'
            );
        }

        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling getBackup().'
            );
        }

        if (requestParameters['backupId'] == null) {
            throw new runtime.RequiredError(
                'backupId',
                'Required parameter "backupId" was null or undefined when calling getBackup().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/workspaces/{workspace_id}/projects/{project_id}/backups/{backup_id}`;
        urlPath = urlPath.replace(`{${"workspace_id"}}`, encodeURIComponent(String(requestParameters['workspaceId'])));
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));
        urlPath = urlPath.replace(`{${"backup_id"}}`, encodeURIComponent(String(requestParameters['backupId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListBackups200ResponseAllOfItemsInnerFromJSON(jsonValue));
    }

    /**
     * Get backup by ID
     */
    async getBackup(workspaceId: string, projectId: string, backupId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListBackups200ResponseAllOfItemsInner> {
        const response = await this.getBackupRaw({ workspaceId: workspaceId, projectId: projectId, backupId: backupId }, initOverrides);
        return await response.value();
    }

    /**
     * List backups
     */
    async listBackupsRaw(requestParameters: ListBackupsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListBackups200Response>> {
        if (requestParameters['workspaceId'] == null) {
            throw new runtime.RequiredError(
                'workspaceId',
                'Required parameter "workspaceId" was null or undefined when calling listBackups().'
            );
        }

        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling listBackups().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/workspaces/{workspace_id}/projects/{project_id}/backups`;
        urlPath = urlPath.replace(`{${"workspace_id"}}`, encodeURIComponent(String(requestParameters['workspaceId'])));
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListBackups200ResponseFromJSON(jsonValue));
    }

    /**
     * List backups
     */
    async listBackups(workspaceId: string, projectId: string, page?: number, limit?: number, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListBackups200Response> {
        const response = await this.listBackupsRaw({ workspaceId: workspaceId, projectId: projectId, page: page, limit: limit }, initOverrides);
        return await response.value();
    }

    /**
     * Request backup copy for download
     */
    async requestBackupCopyRaw(requestParameters: RequestBackupCopyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestBackupCopy200Response>> {
        if (requestParameters['workspaceId'] == null) {
            throw new runtime.RequiredError(
                'workspaceId',
                'Required parameter "workspaceId" was null or undefined when calling requestBackupCopy().'
            );
        }

        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling requestBackupCopy().'
            );
        }

        if (requestParameters['backupId'] == null) {
            throw new runtime.RequiredError(
                'backupId',
                'Required parameter "backupId" was null or undefined when calling requestBackupCopy().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/workspaces/{workspace_id}/projects/{project_id}/backups/{backup_id}/download`;
        urlPath = urlPath.replace(`{${"workspace_id"}}`, encodeURIComponent(String(requestParameters['workspaceId'])));
        urlPath = urlPath.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId'])));
        urlPath = urlPath.replace(`{${"backup_id"}}`, encodeURIComponent(String(requestParameters['backupId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestBackupCopy200ResponseFromJSON(jsonValue));
    }

    /**
     * Request backup copy for download
     */
    async requestBackupCopy(workspaceId: string, projectId: string, backupId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestBackupCopy200Response> {
        const response = await this.requestBackupCopyRaw({ workspaceId: workspaceId, projectId: projectId, backupId: backupId }, initOverrides);
        return await response.value();
    }

}
