/* tslint:disable */
/* eslint-disable */
/**
 * Saved API
 * Microservices-based backup and vault management platform with encrypted backups and distributed storage
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreatePortalSession200Response,
  CreatePortalSessionRequest,
  CreateSetupIntent200Response,
  GetCurrentUsage200Response,
  GetSubscription200Response,
  ListInvoices200ResponseInner,
  ListPaymentMethods200ResponseInner,
  ListWorkspaces401Response,
} from '../models/index';
import {
    CreatePortalSession200ResponseFromJSON,
    CreatePortalSession200ResponseToJSON,
    CreatePortalSessionRequestFromJSON,
    CreatePortalSessionRequestToJSON,
    CreateSetupIntent200ResponseFromJSON,
    CreateSetupIntent200ResponseToJSON,
    GetCurrentUsage200ResponseFromJSON,
    GetCurrentUsage200ResponseToJSON,
    GetSubscription200ResponseFromJSON,
    GetSubscription200ResponseToJSON,
    ListInvoices200ResponseInnerFromJSON,
    ListInvoices200ResponseInnerToJSON,
    ListPaymentMethods200ResponseInnerFromJSON,
    ListPaymentMethods200ResponseInnerToJSON,
    ListWorkspaces401ResponseFromJSON,
    ListWorkspaces401ResponseToJSON,
} from '../models/index';

export interface CancelSubscriptionRequest {
    id: string;
}

export interface CreatePortalSessionOperationRequest {
    id: string;
    createPortalSessionRequest: CreatePortalSessionRequest;
}

export interface CreateSetupIntentRequest {
    id: string;
}

export interface GetCurrentUsageRequest {
    id: string;
}

export interface GetSubscriptionRequest {
    id: string;
}

export interface ListInvoicesRequest {
    id: string;
    limit?: number;
}

export interface ListPaymentMethodsRequest {
    id: string;
}

export interface RemovePaymentMethodRequest {
    id: string;
    pmId: string;
}

export interface SetDefaultPaymentMethodRequest {
    id: string;
    pmId: string;
}

/**
 * BillingApi - interface
 * 
 * @export
 * @interface BillingApiInterface
 */
export interface BillingApiInterface {
    /**
     * 
     * @summary Cancel subscription
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BillingApiInterface
     */
    cancelSubscriptionRaw(requestParameters: CancelSubscriptionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListWorkspaces401Response>>;

    /**
     * Cancel subscription
     */
    cancelSubscription(id: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListWorkspaces401Response>;

    /**
     * 
     * @summary Create Stripe customer portal session
     * @param {string} id 
     * @param {CreatePortalSessionRequest} createPortalSessionRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BillingApiInterface
     */
    createPortalSessionRaw(requestParameters: CreatePortalSessionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreatePortalSession200Response>>;

    /**
     * Create Stripe customer portal session
     */
    createPortalSession(id: string, createPortalSessionRequest: CreatePortalSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreatePortalSession200Response>;

    /**
     * 
     * @summary Create setup intent for payment method
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BillingApiInterface
     */
    createSetupIntentRaw(requestParameters: CreateSetupIntentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateSetupIntent200Response>>;

    /**
     * Create setup intent for payment method
     */
    createSetupIntent(id: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateSetupIntent200Response>;

    /**
     * 
     * @summary Get current billing period usage
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BillingApiInterface
     */
    getCurrentUsageRaw(requestParameters: GetCurrentUsageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetCurrentUsage200Response>>;

    /**
     * Get current billing period usage
     */
    getCurrentUsage(id: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetCurrentUsage200Response>;

    /**
     * 
     * @summary Get subscription information
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BillingApiInterface
     */
    getSubscriptionRaw(requestParameters: GetSubscriptionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetSubscription200Response>>;

    /**
     * Get subscription information
     */
    getSubscription(id: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetSubscription200Response>;

    /**
     * 
     * @summary List invoices
     * @param {string} id 
     * @param {number} [limit] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BillingApiInterface
     */
    listInvoicesRaw(requestParameters: ListInvoicesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ListInvoices200ResponseInner>>>;

    /**
     * List invoices
     */
    listInvoices(id: string, limit?: number, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ListInvoices200ResponseInner>>;

    /**
     * 
     * @summary List payment methods
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BillingApiInterface
     */
    listPaymentMethodsRaw(requestParameters: ListPaymentMethodsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ListPaymentMethods200ResponseInner>>>;

    /**
     * List payment methods
     */
    listPaymentMethods(id: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ListPaymentMethods200ResponseInner>>;

    /**
     * 
     * @summary Remove payment method
     * @param {string} id 
     * @param {string} pmId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BillingApiInterface
     */
    removePaymentMethodRaw(requestParameters: RemovePaymentMethodRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListWorkspaces401Response>>;

    /**
     * Remove payment method
     */
    removePaymentMethod(id: string, pmId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListWorkspaces401Response>;

    /**
     * 
     * @summary Set default payment method
     * @param {string} id 
     * @param {string} pmId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BillingApiInterface
     */
    setDefaultPaymentMethodRaw(requestParameters: SetDefaultPaymentMethodRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListWorkspaces401Response>>;

    /**
     * Set default payment method
     */
    setDefaultPaymentMethod(id: string, pmId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListWorkspaces401Response>;

}

/**
 * 
 */
export class BillingApi extends runtime.BaseAPI implements BillingApiInterface {

    /**
     * Cancel subscription
     */
    async cancelSubscriptionRaw(requestParameters: CancelSubscriptionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListWorkspaces401Response>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling cancelSubscription().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/workspaces/{id}/billing/subscription`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListWorkspaces401ResponseFromJSON(jsonValue));
    }

    /**
     * Cancel subscription
     */
    async cancelSubscription(id: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListWorkspaces401Response> {
        const response = await this.cancelSubscriptionRaw({ id: id }, initOverrides);
        return await response.value();
    }

    /**
     * Create Stripe customer portal session
     */
    async createPortalSessionRaw(requestParameters: CreatePortalSessionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreatePortalSession200Response>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling createPortalSession().'
            );
        }

        if (requestParameters['createPortalSessionRequest'] == null) {
            throw new runtime.RequiredError(
                'createPortalSessionRequest',
                'Required parameter "createPortalSessionRequest" was null or undefined when calling createPortalSession().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/workspaces/{id}/billing/portal-session`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreatePortalSessionRequestToJSON(requestParameters['createPortalSessionRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreatePortalSession200ResponseFromJSON(jsonValue));
    }

    /**
     * Create Stripe customer portal session
     */
    async createPortalSession(id: string, createPortalSessionRequest: CreatePortalSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreatePortalSession200Response> {
        const response = await this.createPortalSessionRaw({ id: id, createPortalSessionRequest: createPortalSessionRequest }, initOverrides);
        return await response.value();
    }

    /**
     * Create setup intent for payment method
     */
    async createSetupIntentRaw(requestParameters: CreateSetupIntentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateSetupIntent200Response>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling createSetupIntent().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/workspaces/{id}/billing/setup-intent`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateSetupIntent200ResponseFromJSON(jsonValue));
    }

    /**
     * Create setup intent for payment method
     */
    async createSetupIntent(id: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateSetupIntent200Response> {
        const response = await this.createSetupIntentRaw({ id: id }, initOverrides);
        return await response.value();
    }

    /**
     * Get current billing period usage
     */
    async getCurrentUsageRaw(requestParameters: GetCurrentUsageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetCurrentUsage200Response>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getCurrentUsage().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/workspaces/{id}/billing/usage/current`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetCurrentUsage200ResponseFromJSON(jsonValue));
    }

    /**
     * Get current billing period usage
     */
    async getCurrentUsage(id: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetCurrentUsage200Response> {
        const response = await this.getCurrentUsageRaw({ id: id }, initOverrides);
        return await response.value();
    }

    /**
     * Get subscription information
     */
    async getSubscriptionRaw(requestParameters: GetSubscriptionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetSubscription200Response>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getSubscription().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/workspaces/{id}/billing/subscription`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetSubscription200ResponseFromJSON(jsonValue));
    }

    /**
     * Get subscription information
     */
    async getSubscription(id: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetSubscription200Response> {
        const response = await this.getSubscriptionRaw({ id: id }, initOverrides);
        return await response.value();
    }

    /**
     * List invoices
     */
    async listInvoicesRaw(requestParameters: ListInvoicesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ListInvoices200ResponseInner>>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling listInvoices().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/workspaces/{id}/billing/invoices`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ListInvoices200ResponseInnerFromJSON));
    }

    /**
     * List invoices
     */
    async listInvoices(id: string, limit?: number, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ListInvoices200ResponseInner>> {
        const response = await this.listInvoicesRaw({ id: id, limit: limit }, initOverrides);
        return await response.value();
    }

    /**
     * List payment methods
     */
    async listPaymentMethodsRaw(requestParameters: ListPaymentMethodsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ListPaymentMethods200ResponseInner>>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling listPaymentMethods().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/workspaces/{id}/billing/payment-methods`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ListPaymentMethods200ResponseInnerFromJSON));
    }

    /**
     * List payment methods
     */
    async listPaymentMethods(id: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ListPaymentMethods200ResponseInner>> {
        const response = await this.listPaymentMethodsRaw({ id: id }, initOverrides);
        return await response.value();
    }

    /**
     * Remove payment method
     */
    async removePaymentMethodRaw(requestParameters: RemovePaymentMethodRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListWorkspaces401Response>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling removePaymentMethod().'
            );
        }

        if (requestParameters['pmId'] == null) {
            throw new runtime.RequiredError(
                'pmId',
                'Required parameter "pmId" was null or undefined when calling removePaymentMethod().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/workspaces/{id}/billing/payment-methods/{pm_id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));
        urlPath = urlPath.replace(`{${"pm_id"}}`, encodeURIComponent(String(requestParameters['pmId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListWorkspaces401ResponseFromJSON(jsonValue));
    }

    /**
     * Remove payment method
     */
    async removePaymentMethod(id: string, pmId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListWorkspaces401Response> {
        const response = await this.removePaymentMethodRaw({ id: id, pmId: pmId }, initOverrides);
        return await response.value();
    }

    /**
     * Set default payment method
     */
    async setDefaultPaymentMethodRaw(requestParameters: SetDefaultPaymentMethodRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListWorkspaces401Response>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling setDefaultPaymentMethod().'
            );
        }

        if (requestParameters['pmId'] == null) {
            throw new runtime.RequiredError(
                'pmId',
                'Required parameter "pmId" was null or undefined when calling setDefaultPaymentMethod().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/workspaces/{id}/billing/payment-methods/{pm_id}/default`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));
        urlPath = urlPath.replace(`{${"pm_id"}}`, encodeURIComponent(String(requestParameters['pmId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListWorkspaces401ResponseFromJSON(jsonValue));
    }

    /**
     * Set default payment method
     */
    async setDefaultPaymentMethod(id: string, pmId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListWorkspaces401Response> {
        const response = await this.setDefaultPaymentMethodRaw({ id: id, pmId: pmId }, initOverrides);
        return await response.value();
    }

}
