/* tslint:disable */
/* eslint-disable */
/**
 * Saved API
 * encrypted backups and distributed storage
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ConfirmBackup200Response,
  ConfirmBackupRequest,
  GetBillingInfo401Response,
  GetJobDetails200ResponseRecentBackupsInner,
  RequestBackupRequest,
  UploadBackup200Response,
  UploadBackupRequest,
} from '../models/index';
import {
    ConfirmBackup200ResponseFromJSON,
    ConfirmBackup200ResponseToJSON,
    ConfirmBackupRequestFromJSON,
    ConfirmBackupRequestToJSON,
    GetBillingInfo401ResponseFromJSON,
    GetBillingInfo401ResponseToJSON,
    GetJobDetails200ResponseRecentBackupsInnerFromJSON,
    GetJobDetails200ResponseRecentBackupsInnerToJSON,
    RequestBackupRequestFromJSON,
    RequestBackupRequestToJSON,
    UploadBackup200ResponseFromJSON,
    UploadBackup200ResponseToJSON,
    UploadBackupRequestFromJSON,
    UploadBackupRequestToJSON,
} from '../models/index';

export interface ConfirmBackupOperationRequest {
    workspaceId: string;
    jobId: string;
    backupId: string;
    confirmBackupRequest: ConfirmBackupRequest;
}

export interface RequestBackupOperationRequest {
    workspaceId: string;
    jobId: string;
    requestBackupRequest?: RequestBackupRequest;
}

export interface UploadBackupOperationRequest {
    workspaceId: string;
    jobId: string;
    backupId: string;
    uploadBackupRequest: UploadBackupRequest;
}

/**
 * JobOperationsApi - interface
 * 
 * @export
 * @interface JobOperationsApiInterface
 */
export interface JobOperationsApiInterface {
    /**
     * 
     * @summary Confirm backup completion
     * @param {string} workspaceId The unique identifier of the workspace.
     * @param {string} jobId The unique identifier of the job.
     * @param {string} backupId The unique identifier of the backup.
     * @param {ConfirmBackupRequest} confirmBackupRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof JobOperationsApiInterface
     */
    confirmBackupRaw(requestParameters: ConfirmBackupOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConfirmBackup200Response>>;

    /**
     * Confirm backup completion
     */
    confirmBackup(workspaceId: string, jobId: string, backupId: string, confirmBackupRequest: ConfirmBackupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConfirmBackup200Response>;

    /**
     * 
     * @summary Request a backup
     * @param {string} workspaceId The unique identifier of the workspace.
     * @param {string} jobId The unique identifier of the job.
     * @param {RequestBackupRequest} [requestBackupRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof JobOperationsApiInterface
     */
    requestBackupRaw(requestParameters: RequestBackupOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetJobDetails200ResponseRecentBackupsInner>>;

    /**
     * Request a backup
     */
    requestBackup(workspaceId: string, jobId: string, requestBackupRequest?: RequestBackupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetJobDetails200ResponseRecentBackupsInner>;

    /**
     * 
     * @summary Upload a backup file
     * @param {string} workspaceId The unique identifier of the workspace.
     * @param {string} jobId The unique identifier of the job.
     * @param {string} backupId The unique identifier of the backup.
     * @param {UploadBackupRequest} uploadBackupRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof JobOperationsApiInterface
     */
    uploadBackupRaw(requestParameters: UploadBackupOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UploadBackup200Response>>;

    /**
     * Upload a backup file
     */
    uploadBackup(workspaceId: string, jobId: string, backupId: string, uploadBackupRequest: UploadBackupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UploadBackup200Response>;

}

/**
 * 
 */
export class JobOperationsApi extends runtime.BaseAPI implements JobOperationsApiInterface {

    /**
     * Confirm backup completion
     */
    async confirmBackupRaw(requestParameters: ConfirmBackupOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConfirmBackup200Response>> {
        if (requestParameters['workspaceId'] == null) {
            throw new runtime.RequiredError(
                'workspaceId',
                'Required parameter "workspaceId" was null or undefined when calling confirmBackup().'
            );
        }

        if (requestParameters['jobId'] == null) {
            throw new runtime.RequiredError(
                'jobId',
                'Required parameter "jobId" was null or undefined when calling confirmBackup().'
            );
        }

        if (requestParameters['backupId'] == null) {
            throw new runtime.RequiredError(
                'backupId',
                'Required parameter "backupId" was null or undefined when calling confirmBackup().'
            );
        }

        if (requestParameters['confirmBackupRequest'] == null) {
            throw new runtime.RequiredError(
                'confirmBackupRequest',
                'Required parameter "confirmBackupRequest" was null or undefined when calling confirmBackup().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/workspaces/{workspace_id}/jobs/{job_id}/backups/{backup_id}/confirm`;
        urlPath = urlPath.replace(`{${"workspace_id"}}`, encodeURIComponent(String(requestParameters['workspaceId'])));
        urlPath = urlPath.replace(`{${"job_id"}}`, encodeURIComponent(String(requestParameters['jobId'])));
        urlPath = urlPath.replace(`{${"backup_id"}}`, encodeURIComponent(String(requestParameters['backupId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ConfirmBackupRequestToJSON(requestParameters['confirmBackupRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConfirmBackup200ResponseFromJSON(jsonValue));
    }

    /**
     * Confirm backup completion
     */
    async confirmBackup(workspaceId: string, jobId: string, backupId: string, confirmBackupRequest: ConfirmBackupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConfirmBackup200Response> {
        const response = await this.confirmBackupRaw({ workspaceId: workspaceId, jobId: jobId, backupId: backupId, confirmBackupRequest: confirmBackupRequest }, initOverrides);
        return await response.value();
    }

    /**
     * Request a backup
     */
    async requestBackupRaw(requestParameters: RequestBackupOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetJobDetails200ResponseRecentBackupsInner>> {
        if (requestParameters['workspaceId'] == null) {
            throw new runtime.RequiredError(
                'workspaceId',
                'Required parameter "workspaceId" was null or undefined when calling requestBackup().'
            );
        }

        if (requestParameters['jobId'] == null) {
            throw new runtime.RequiredError(
                'jobId',
                'Required parameter "jobId" was null or undefined when calling requestBackup().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/workspaces/{workspace_id}/jobs/{job_id}/request`;
        urlPath = urlPath.replace(`{${"workspace_id"}}`, encodeURIComponent(String(requestParameters['workspaceId'])));
        urlPath = urlPath.replace(`{${"job_id"}}`, encodeURIComponent(String(requestParameters['jobId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RequestBackupRequestToJSON(requestParameters['requestBackupRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetJobDetails200ResponseRecentBackupsInnerFromJSON(jsonValue));
    }

    /**
     * Request a backup
     */
    async requestBackup(workspaceId: string, jobId: string, requestBackupRequest?: RequestBackupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetJobDetails200ResponseRecentBackupsInner> {
        const response = await this.requestBackupRaw({ workspaceId: workspaceId, jobId: jobId, requestBackupRequest: requestBackupRequest }, initOverrides);
        return await response.value();
    }

    /**
     * Upload a backup file
     */
    async uploadBackupRaw(requestParameters: UploadBackupOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UploadBackup200Response>> {
        if (requestParameters['workspaceId'] == null) {
            throw new runtime.RequiredError(
                'workspaceId',
                'Required parameter "workspaceId" was null or undefined when calling uploadBackup().'
            );
        }

        if (requestParameters['jobId'] == null) {
            throw new runtime.RequiredError(
                'jobId',
                'Required parameter "jobId" was null or undefined when calling uploadBackup().'
            );
        }

        if (requestParameters['backupId'] == null) {
            throw new runtime.RequiredError(
                'backupId',
                'Required parameter "backupId" was null or undefined when calling uploadBackup().'
            );
        }

        if (requestParameters['uploadBackupRequest'] == null) {
            throw new runtime.RequiredError(
                'uploadBackupRequest',
                'Required parameter "uploadBackupRequest" was null or undefined when calling uploadBackup().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/workspaces/{workspace_id}/jobs/{job_id}/backups/{backup_id}/upload`;
        urlPath = urlPath.replace(`{${"workspace_id"}}`, encodeURIComponent(String(requestParameters['workspaceId'])));
        urlPath = urlPath.replace(`{${"job_id"}}`, encodeURIComponent(String(requestParameters['jobId'])));
        urlPath = urlPath.replace(`{${"backup_id"}}`, encodeURIComponent(String(requestParameters['backupId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UploadBackupRequestToJSON(requestParameters['uploadBackupRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UploadBackup200ResponseFromJSON(jsonValue));
    }

    /**
     * Upload a backup file
     */
    async uploadBackup(workspaceId: string, jobId: string, backupId: string, uploadBackupRequest: UploadBackupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UploadBackup200Response> {
        const response = await this.uploadBackupRaw({ workspaceId: workspaceId, jobId: jobId, backupId: backupId, uploadBackupRequest: uploadBackupRequest }, initOverrides);
        return await response.value();
    }

}
