/* tslint:disable */
/* eslint-disable */
/**
 * Saved API
 * encrypted backups and distributed storage
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateAgentJob201Response,
  CreateAgentJobRequest,
  CreateManualJob201Response,
  CreateManualJobRequest,
  CreateWorkerJob201Response,
  CreateWorkerJobRequest,
  ListJobs200ResponseInner,
  TriggerJob202Response,
  UpdateJobRequest,
} from '../models/index';
import {
    CreateAgentJob201ResponseFromJSON,
    CreateAgentJob201ResponseToJSON,
    CreateAgentJobRequestFromJSON,
    CreateAgentJobRequestToJSON,
    CreateManualJob201ResponseFromJSON,
    CreateManualJob201ResponseToJSON,
    CreateManualJobRequestFromJSON,
    CreateManualJobRequestToJSON,
    CreateWorkerJob201ResponseFromJSON,
    CreateWorkerJob201ResponseToJSON,
    CreateWorkerJobRequestFromJSON,
    CreateWorkerJobRequestToJSON,
    ListJobs200ResponseInnerFromJSON,
    ListJobs200ResponseInnerToJSON,
    TriggerJob202ResponseFromJSON,
    TriggerJob202ResponseToJSON,
    UpdateJobRequestFromJSON,
    UpdateJobRequestToJSON,
} from '../models/index';

export interface CreateAgentJobOperationRequest {
    workspaceId: string;
    createAgentJobRequest: CreateAgentJobRequest;
}

export interface CreateManualJobOperationRequest {
    workspaceId: string;
    createManualJobRequest: CreateManualJobRequest;
}

export interface CreateWorkerJobOperationRequest {
    workspaceId: string;
    createWorkerJobRequest: CreateWorkerJobRequest;
}

export interface DeleteJobRequest {
    workspaceId: string;
    jobId: string;
}

export interface GetJobRequest {
    workspaceId: string;
    jobId: string;
}

export interface ListJobsRequest {
    workspaceId: string;
    limit?: number;
    offset?: number;
}

export interface TriggerJobRequest {
    workspaceId: string;
    jobId: string;
}

export interface UpdateJobOperationRequest {
    workspaceId: string;
    jobId: string;
    updateJobRequest: UpdateJobRequest;
}

/**
 * JobsApi - interface
 * 
 * @export
 * @interface JobsApiInterface
 */
export interface JobsApiInterface {
    /**
     * 
     * @summary Create an agent job
     * @param {string} workspaceId The unique identifier of the workspace.
     * @param {CreateAgentJobRequest} createAgentJobRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof JobsApiInterface
     */
    createAgentJobRaw(requestParameters: CreateAgentJobOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateAgentJob201Response>>;

    /**
     * Create an agent job
     */
    createAgentJob(workspaceId: string, createAgentJobRequest: CreateAgentJobRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateAgentJob201Response>;

    /**
     * 
     * @summary Create a manual job
     * @param {string} workspaceId The unique identifier of the workspace.
     * @param {CreateManualJobRequest} createManualJobRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof JobsApiInterface
     */
    createManualJobRaw(requestParameters: CreateManualJobOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateManualJob201Response>>;

    /**
     * Create a manual job
     */
    createManualJob(workspaceId: string, createManualJobRequest: CreateManualJobRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateManualJob201Response>;

    /**
     * 
     * @summary Create a worker job
     * @param {string} workspaceId The unique identifier of the workspace.
     * @param {CreateWorkerJobRequest} createWorkerJobRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof JobsApiInterface
     */
    createWorkerJobRaw(requestParameters: CreateWorkerJobOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateWorkerJob201Response>>;

    /**
     * Create a worker job
     */
    createWorkerJob(workspaceId: string, createWorkerJobRequest: CreateWorkerJobRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateWorkerJob201Response>;

    /**
     * 
     * @summary Delete a job
     * @param {string} workspaceId The unique identifier of the workspace.
     * @param {string} jobId The unique identifier of the job.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof JobsApiInterface
     */
    deleteJobRaw(requestParameters: DeleteJobRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Delete a job
     */
    deleteJob(workspaceId: string, jobId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @summary Get a job
     * @param {string} workspaceId The unique identifier of the workspace.
     * @param {string} jobId The unique identifier of the job.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof JobsApiInterface
     */
    getJobRaw(requestParameters: GetJobRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListJobs200ResponseInner>>;

    /**
     * Get a job
     */
    getJob(workspaceId: string, jobId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListJobs200ResponseInner>;

    /**
     * 
     * @summary List jobs
     * @param {string} workspaceId The unique identifier of the workspace.
     * @param {number} [limit] The number of items to return.
     * @param {number} [offset] The number of items to skip.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof JobsApiInterface
     */
    listJobsRaw(requestParameters: ListJobsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ListJobs200ResponseInner>>>;

    /**
     * List jobs
     */
    listJobs(workspaceId: string, limit?: number, offset?: number, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ListJobs200ResponseInner>>;

    /**
     * 
     * @summary Trigger a job
     * @param {string} workspaceId The unique identifier of the workspace.
     * @param {string} jobId The unique identifier of the job.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof JobsApiInterface
     */
    triggerJobRaw(requestParameters: TriggerJobRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TriggerJob202Response>>;

    /**
     * Trigger a job
     */
    triggerJob(workspaceId: string, jobId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TriggerJob202Response>;

    /**
     * 
     * @summary Update a job
     * @param {string} workspaceId The unique identifier of the workspace.
     * @param {string} jobId The unique identifier of the job.
     * @param {UpdateJobRequest} updateJobRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof JobsApiInterface
     */
    updateJobRaw(requestParameters: UpdateJobOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListJobs200ResponseInner>>;

    /**
     * Update a job
     */
    updateJob(workspaceId: string, jobId: string, updateJobRequest: UpdateJobRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListJobs200ResponseInner>;

}

/**
 * 
 */
export class JobsApi extends runtime.BaseAPI implements JobsApiInterface {

    /**
     * Create an agent job
     */
    async createAgentJobRaw(requestParameters: CreateAgentJobOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateAgentJob201Response>> {
        if (requestParameters['workspaceId'] == null) {
            throw new runtime.RequiredError(
                'workspaceId',
                'Required parameter "workspaceId" was null or undefined when calling createAgentJob().'
            );
        }

        if (requestParameters['createAgentJobRequest'] == null) {
            throw new runtime.RequiredError(
                'createAgentJobRequest',
                'Required parameter "createAgentJobRequest" was null or undefined when calling createAgentJob().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/workspaces/{workspace_id}/jobs/agent`;
        urlPath = urlPath.replace(`{${"workspace_id"}}`, encodeURIComponent(String(requestParameters['workspaceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateAgentJobRequestToJSON(requestParameters['createAgentJobRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateAgentJob201ResponseFromJSON(jsonValue));
    }

    /**
     * Create an agent job
     */
    async createAgentJob(workspaceId: string, createAgentJobRequest: CreateAgentJobRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateAgentJob201Response> {
        const response = await this.createAgentJobRaw({ workspaceId: workspaceId, createAgentJobRequest: createAgentJobRequest }, initOverrides);
        return await response.value();
    }

    /**
     * Create a manual job
     */
    async createManualJobRaw(requestParameters: CreateManualJobOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateManualJob201Response>> {
        if (requestParameters['workspaceId'] == null) {
            throw new runtime.RequiredError(
                'workspaceId',
                'Required parameter "workspaceId" was null or undefined when calling createManualJob().'
            );
        }

        if (requestParameters['createManualJobRequest'] == null) {
            throw new runtime.RequiredError(
                'createManualJobRequest',
                'Required parameter "createManualJobRequest" was null or undefined when calling createManualJob().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/workspaces/{workspace_id}/jobs/manual`;
        urlPath = urlPath.replace(`{${"workspace_id"}}`, encodeURIComponent(String(requestParameters['workspaceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateManualJobRequestToJSON(requestParameters['createManualJobRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateManualJob201ResponseFromJSON(jsonValue));
    }

    /**
     * Create a manual job
     */
    async createManualJob(workspaceId: string, createManualJobRequest: CreateManualJobRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateManualJob201Response> {
        const response = await this.createManualJobRaw({ workspaceId: workspaceId, createManualJobRequest: createManualJobRequest }, initOverrides);
        return await response.value();
    }

    /**
     * Create a worker job
     */
    async createWorkerJobRaw(requestParameters: CreateWorkerJobOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateWorkerJob201Response>> {
        if (requestParameters['workspaceId'] == null) {
            throw new runtime.RequiredError(
                'workspaceId',
                'Required parameter "workspaceId" was null or undefined when calling createWorkerJob().'
            );
        }

        if (requestParameters['createWorkerJobRequest'] == null) {
            throw new runtime.RequiredError(
                'createWorkerJobRequest',
                'Required parameter "createWorkerJobRequest" was null or undefined when calling createWorkerJob().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/workspaces/{workspace_id}/jobs/worker`;
        urlPath = urlPath.replace(`{${"workspace_id"}}`, encodeURIComponent(String(requestParameters['workspaceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateWorkerJobRequestToJSON(requestParameters['createWorkerJobRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateWorkerJob201ResponseFromJSON(jsonValue));
    }

    /**
     * Create a worker job
     */
    async createWorkerJob(workspaceId: string, createWorkerJobRequest: CreateWorkerJobRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateWorkerJob201Response> {
        const response = await this.createWorkerJobRaw({ workspaceId: workspaceId, createWorkerJobRequest: createWorkerJobRequest }, initOverrides);
        return await response.value();
    }

    /**
     * Delete a job
     */
    async deleteJobRaw(requestParameters: DeleteJobRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['workspaceId'] == null) {
            throw new runtime.RequiredError(
                'workspaceId',
                'Required parameter "workspaceId" was null or undefined when calling deleteJob().'
            );
        }

        if (requestParameters['jobId'] == null) {
            throw new runtime.RequiredError(
                'jobId',
                'Required parameter "jobId" was null or undefined when calling deleteJob().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/workspaces/{workspace_id}/jobs/{job_id}`;
        urlPath = urlPath.replace(`{${"workspace_id"}}`, encodeURIComponent(String(requestParameters['workspaceId'])));
        urlPath = urlPath.replace(`{${"job_id"}}`, encodeURIComponent(String(requestParameters['jobId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a job
     */
    async deleteJob(workspaceId: string, jobId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteJobRaw({ workspaceId: workspaceId, jobId: jobId }, initOverrides);
    }

    /**
     * Get a job
     */
    async getJobRaw(requestParameters: GetJobRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListJobs200ResponseInner>> {
        if (requestParameters['workspaceId'] == null) {
            throw new runtime.RequiredError(
                'workspaceId',
                'Required parameter "workspaceId" was null or undefined when calling getJob().'
            );
        }

        if (requestParameters['jobId'] == null) {
            throw new runtime.RequiredError(
                'jobId',
                'Required parameter "jobId" was null or undefined when calling getJob().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/workspaces/{workspace_id}/jobs/{job_id}`;
        urlPath = urlPath.replace(`{${"workspace_id"}}`, encodeURIComponent(String(requestParameters['workspaceId'])));
        urlPath = urlPath.replace(`{${"job_id"}}`, encodeURIComponent(String(requestParameters['jobId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListJobs200ResponseInnerFromJSON(jsonValue));
    }

    /**
     * Get a job
     */
    async getJob(workspaceId: string, jobId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListJobs200ResponseInner> {
        const response = await this.getJobRaw({ workspaceId: workspaceId, jobId: jobId }, initOverrides);
        return await response.value();
    }

    /**
     * List jobs
     */
    async listJobsRaw(requestParameters: ListJobsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ListJobs200ResponseInner>>> {
        if (requestParameters['workspaceId'] == null) {
            throw new runtime.RequiredError(
                'workspaceId',
                'Required parameter "workspaceId" was null or undefined when calling listJobs().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/workspaces/{workspace_id}/jobs`;
        urlPath = urlPath.replace(`{${"workspace_id"}}`, encodeURIComponent(String(requestParameters['workspaceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ListJobs200ResponseInnerFromJSON));
    }

    /**
     * List jobs
     */
    async listJobs(workspaceId: string, limit?: number, offset?: number, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ListJobs200ResponseInner>> {
        const response = await this.listJobsRaw({ workspaceId: workspaceId, limit: limit, offset: offset }, initOverrides);
        return await response.value();
    }

    /**
     * Trigger a job
     */
    async triggerJobRaw(requestParameters: TriggerJobRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TriggerJob202Response>> {
        if (requestParameters['workspaceId'] == null) {
            throw new runtime.RequiredError(
                'workspaceId',
                'Required parameter "workspaceId" was null or undefined when calling triggerJob().'
            );
        }

        if (requestParameters['jobId'] == null) {
            throw new runtime.RequiredError(
                'jobId',
                'Required parameter "jobId" was null or undefined when calling triggerJob().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/workspaces/{workspace_id}/jobs/{job_id}/trigger`;
        urlPath = urlPath.replace(`{${"workspace_id"}}`, encodeURIComponent(String(requestParameters['workspaceId'])));
        urlPath = urlPath.replace(`{${"job_id"}}`, encodeURIComponent(String(requestParameters['jobId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TriggerJob202ResponseFromJSON(jsonValue));
    }

    /**
     * Trigger a job
     */
    async triggerJob(workspaceId: string, jobId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TriggerJob202Response> {
        const response = await this.triggerJobRaw({ workspaceId: workspaceId, jobId: jobId }, initOverrides);
        return await response.value();
    }

    /**
     * Update a job
     */
    async updateJobRaw(requestParameters: UpdateJobOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListJobs200ResponseInner>> {
        if (requestParameters['workspaceId'] == null) {
            throw new runtime.RequiredError(
                'workspaceId',
                'Required parameter "workspaceId" was null or undefined when calling updateJob().'
            );
        }

        if (requestParameters['jobId'] == null) {
            throw new runtime.RequiredError(
                'jobId',
                'Required parameter "jobId" was null or undefined when calling updateJob().'
            );
        }

        if (requestParameters['updateJobRequest'] == null) {
            throw new runtime.RequiredError(
                'updateJobRequest',
                'Required parameter "updateJobRequest" was null or undefined when calling updateJob().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/workspaces/{workspace_id}/jobs/{job_id}`;
        urlPath = urlPath.replace(`{${"workspace_id"}}`, encodeURIComponent(String(requestParameters['workspaceId'])));
        urlPath = urlPath.replace(`{${"job_id"}}`, encodeURIComponent(String(requestParameters['jobId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateJobRequestToJSON(requestParameters['updateJobRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListJobs200ResponseInnerFromJSON(jsonValue));
    }

    /**
     * Update a job
     */
    async updateJob(workspaceId: string, jobId: string, updateJobRequest: UpdateJobRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListJobs200ResponseInner> {
        const response = await this.updateJobRaw({ workspaceId: workspaceId, jobId: jobId, updateJobRequest: updateJobRequest }, initOverrides);
        return await response.value();
    }

}
