/* tslint:disable */
/* eslint-disable */
/**
 * BackedUp API
 * Microservices-based backup and vault management platform with encrypted backups and distributed storage
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateKeyRequest,
  CreateWorkspaceRequest,
  ListKeys200Response,
  ListKeys200ResponseAllOfItemsInner,
  ListWorkspaces401Response,
} from '../models/index';
import {
    CreateKeyRequestFromJSON,
    CreateKeyRequestToJSON,
    CreateWorkspaceRequestFromJSON,
    CreateWorkspaceRequestToJSON,
    ListKeys200ResponseFromJSON,
    ListKeys200ResponseToJSON,
    ListKeys200ResponseAllOfItemsInnerFromJSON,
    ListKeys200ResponseAllOfItemsInnerToJSON,
    ListWorkspaces401ResponseFromJSON,
    ListWorkspaces401ResponseToJSON,
} from '../models/index';

export interface CreateKeyOperationRequest {
    workspaceId: string;
    createKeyRequest: CreateKeyRequest;
}

export interface DeleteKeyRequest {
    workspaceId: string;
    keyId: string;
}

export interface GetKeyRequest {
    workspaceId: string;
    keyId: string;
}

export interface ListKeysRequest {
    workspaceId: string;
    page?: number;
    limit?: number;
}

export interface UpdateKeyRequest {
    workspaceId: string;
    keyId: string;
    createWorkspaceRequest: CreateWorkspaceRequest;
}

/**
 * KeysApi - interface
 * 
 * @export
 * @interface KeysApiInterface
 */
export interface KeysApiInterface {
    /**
     * 
     * @summary Create encryption key
     * @param {string} workspaceId 
     * @param {CreateKeyRequest} createKeyRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof KeysApiInterface
     */
    createKeyRaw(requestParameters: CreateKeyOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListKeys200ResponseAllOfItemsInner>>;

    /**
     * Create encryption key
     */
    createKey(workspaceId: string, createKeyRequest: CreateKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListKeys200ResponseAllOfItemsInner>;

    /**
     * 
     * @summary Delete encryption key
     * @param {string} workspaceId 
     * @param {string} keyId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof KeysApiInterface
     */
    deleteKeyRaw(requestParameters: DeleteKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Delete encryption key
     */
    deleteKey(workspaceId: string, keyId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @summary Get encryption key by ID
     * @param {string} workspaceId 
     * @param {string} keyId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof KeysApiInterface
     */
    getKeyRaw(requestParameters: GetKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListKeys200ResponseAllOfItemsInner>>;

    /**
     * Get encryption key by ID
     */
    getKey(workspaceId: string, keyId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListKeys200ResponseAllOfItemsInner>;

    /**
     * 
     * @summary List encryption keys
     * @param {string} workspaceId 
     * @param {number} [page] 
     * @param {number} [limit] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof KeysApiInterface
     */
    listKeysRaw(requestParameters: ListKeysRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListKeys200Response>>;

    /**
     * List encryption keys
     */
    listKeys(workspaceId: string, page?: number, limit?: number, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListKeys200Response>;

    /**
     * 
     * @summary Update encryption key
     * @param {string} workspaceId 
     * @param {string} keyId 
     * @param {CreateWorkspaceRequest} createWorkspaceRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof KeysApiInterface
     */
    updateKeyRaw(requestParameters: UpdateKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListKeys200ResponseAllOfItemsInner>>;

    /**
     * Update encryption key
     */
    updateKey(workspaceId: string, keyId: string, createWorkspaceRequest: CreateWorkspaceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListKeys200ResponseAllOfItemsInner>;

}

/**
 * 
 */
export class KeysApi extends runtime.BaseAPI implements KeysApiInterface {

    /**
     * Create encryption key
     */
    async createKeyRaw(requestParameters: CreateKeyOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListKeys200ResponseAllOfItemsInner>> {
        if (requestParameters['workspaceId'] == null) {
            throw new runtime.RequiredError(
                'workspaceId',
                'Required parameter "workspaceId" was null or undefined when calling createKey().'
            );
        }

        if (requestParameters['createKeyRequest'] == null) {
            throw new runtime.RequiredError(
                'createKeyRequest',
                'Required parameter "createKeyRequest" was null or undefined when calling createKey().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/workspaces/{workspace_id}/keys`;
        urlPath = urlPath.replace(`{${"workspace_id"}}`, encodeURIComponent(String(requestParameters['workspaceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateKeyRequestToJSON(requestParameters['createKeyRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListKeys200ResponseAllOfItemsInnerFromJSON(jsonValue));
    }

    /**
     * Create encryption key
     */
    async createKey(workspaceId: string, createKeyRequest: CreateKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListKeys200ResponseAllOfItemsInner> {
        const response = await this.createKeyRaw({ workspaceId: workspaceId, createKeyRequest: createKeyRequest }, initOverrides);
        return await response.value();
    }

    /**
     * Delete encryption key
     */
    async deleteKeyRaw(requestParameters: DeleteKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['workspaceId'] == null) {
            throw new runtime.RequiredError(
                'workspaceId',
                'Required parameter "workspaceId" was null or undefined when calling deleteKey().'
            );
        }

        if (requestParameters['keyId'] == null) {
            throw new runtime.RequiredError(
                'keyId',
                'Required parameter "keyId" was null or undefined when calling deleteKey().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/workspaces/{workspace_id}/keys/{key_id}`;
        urlPath = urlPath.replace(`{${"workspace_id"}}`, encodeURIComponent(String(requestParameters['workspaceId'])));
        urlPath = urlPath.replace(`{${"key_id"}}`, encodeURIComponent(String(requestParameters['keyId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete encryption key
     */
    async deleteKey(workspaceId: string, keyId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteKeyRaw({ workspaceId: workspaceId, keyId: keyId }, initOverrides);
    }

    /**
     * Get encryption key by ID
     */
    async getKeyRaw(requestParameters: GetKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListKeys200ResponseAllOfItemsInner>> {
        if (requestParameters['workspaceId'] == null) {
            throw new runtime.RequiredError(
                'workspaceId',
                'Required parameter "workspaceId" was null or undefined when calling getKey().'
            );
        }

        if (requestParameters['keyId'] == null) {
            throw new runtime.RequiredError(
                'keyId',
                'Required parameter "keyId" was null or undefined when calling getKey().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/workspaces/{workspace_id}/keys/{key_id}`;
        urlPath = urlPath.replace(`{${"workspace_id"}}`, encodeURIComponent(String(requestParameters['workspaceId'])));
        urlPath = urlPath.replace(`{${"key_id"}}`, encodeURIComponent(String(requestParameters['keyId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListKeys200ResponseAllOfItemsInnerFromJSON(jsonValue));
    }

    /**
     * Get encryption key by ID
     */
    async getKey(workspaceId: string, keyId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListKeys200ResponseAllOfItemsInner> {
        const response = await this.getKeyRaw({ workspaceId: workspaceId, keyId: keyId }, initOverrides);
        return await response.value();
    }

    /**
     * List encryption keys
     */
    async listKeysRaw(requestParameters: ListKeysRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListKeys200Response>> {
        if (requestParameters['workspaceId'] == null) {
            throw new runtime.RequiredError(
                'workspaceId',
                'Required parameter "workspaceId" was null or undefined when calling listKeys().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/workspaces/{workspace_id}/keys`;
        urlPath = urlPath.replace(`{${"workspace_id"}}`, encodeURIComponent(String(requestParameters['workspaceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListKeys200ResponseFromJSON(jsonValue));
    }

    /**
     * List encryption keys
     */
    async listKeys(workspaceId: string, page?: number, limit?: number, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListKeys200Response> {
        const response = await this.listKeysRaw({ workspaceId: workspaceId, page: page, limit: limit }, initOverrides);
        return await response.value();
    }

    /**
     * Update encryption key
     */
    async updateKeyRaw(requestParameters: UpdateKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListKeys200ResponseAllOfItemsInner>> {
        if (requestParameters['workspaceId'] == null) {
            throw new runtime.RequiredError(
                'workspaceId',
                'Required parameter "workspaceId" was null or undefined when calling updateKey().'
            );
        }

        if (requestParameters['keyId'] == null) {
            throw new runtime.RequiredError(
                'keyId',
                'Required parameter "keyId" was null or undefined when calling updateKey().'
            );
        }

        if (requestParameters['createWorkspaceRequest'] == null) {
            throw new runtime.RequiredError(
                'createWorkspaceRequest',
                'Required parameter "createWorkspaceRequest" was null or undefined when calling updateKey().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/workspaces/{workspace_id}/keys/{key_id}`;
        urlPath = urlPath.replace(`{${"workspace_id"}}`, encodeURIComponent(String(requestParameters['workspaceId'])));
        urlPath = urlPath.replace(`{${"key_id"}}`, encodeURIComponent(String(requestParameters['keyId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: CreateWorkspaceRequestToJSON(requestParameters['createWorkspaceRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListKeys200ResponseAllOfItemsInnerFromJSON(jsonValue));
    }

    /**
     * Update encryption key
     */
    async updateKey(workspaceId: string, keyId: string, createWorkspaceRequest: CreateWorkspaceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListKeys200ResponseAllOfItemsInner> {
        const response = await this.updateKeyRaw({ workspaceId: workspaceId, keyId: keyId, createWorkspaceRequest: createWorkspaceRequest }, initOverrides);
        return await response.value();
    }

}
