/* tslint:disable */
/* eslint-disable */
/**
 * Saved API
 * encrypted backups and distributed storage
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GetBillingInfo401Response,
  GetClientConfigAuth200Response,
} from '../models/index';
import {
    GetBillingInfo401ResponseFromJSON,
    GetBillingInfo401ResponseToJSON,
    GetClientConfigAuth200ResponseFromJSON,
    GetClientConfigAuth200ResponseToJSON,
} from '../models/index';

/**
 * PublicApi - interface
 * 
 * @export
 * @interface PublicApiInterface
 */
export interface PublicApiInterface {
    /**
     * Returns Auth0 configuration for client authentication.
     * @summary Get client auth configuration
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PublicApiInterface
     */
    getClientConfigAuthRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetClientConfigAuth200Response>>;

    /**
     * Returns Auth0 configuration for client authentication.
     * Get client auth configuration
     */
    getClientConfigAuth(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetClientConfigAuth200Response>;

}

/**
 * 
 */
export class PublicApi extends runtime.BaseAPI implements PublicApiInterface {

    /**
     * Returns Auth0 configuration for client authentication.
     * Get client auth configuration
     */
    async getClientConfigAuthRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetClientConfigAuth200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/client/config/auth`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetClientConfigAuth200ResponseFromJSON(jsonValue));
    }

    /**
     * Returns Auth0 configuration for client authentication.
     * Get client auth configuration
     */
    async getClientConfigAuth(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetClientConfigAuth200Response> {
        const response = await this.getClientConfigAuthRaw(initOverrides);
        return await response.value();
    }

}
