/* tslint:disable */
/* eslint-disable */
/**
 * Saved API
 * Microservices-based backup and vault management platform with encrypted backups and distributed storage
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddProjectSignalRequest
 */
export interface AddProjectSignalRequest {
    /**
     * 
     * @type {string}
     * @memberof AddProjectSignalRequest
     */
    client_signal_id: string;
}

/**
 * Check if a given object implements the AddProjectSignalRequest interface.
 */
export function instanceOfAddProjectSignalRequest(value: object): value is AddProjectSignalRequest {
    if (!('client_signal_id' in value) || value['client_signal_id'] === undefined) return false;
    return true;
}

export function AddProjectSignalRequestFromJSON(json: any): AddProjectSignalRequest {
    return AddProjectSignalRequestFromJSONTyped(json, false);
}

export function AddProjectSignalRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddProjectSignalRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'client_signal_id': json['client_signal_id'],
    };
}

export function AddProjectSignalRequestToJSON(json: any): AddProjectSignalRequest {
    return AddProjectSignalRequestToJSONTyped(json, false);
}

export function AddProjectSignalRequestToJSONTyped(value?: AddProjectSignalRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'client_signal_id': value['client_signal_id'],
    };
}

