/* tslint:disable */
/* eslint-disable */
/**
 * BackedUp API
 * Microservices-based backup and vault management platform with encrypted backups and distributed storage
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListAgents200ResponseAllOfItemsInner } from './ListAgents200ResponseAllOfItemsInner';
import {
    ListAgents200ResponseAllOfItemsInnerFromJSON,
    ListAgents200ResponseAllOfItemsInnerFromJSONTyped,
    ListAgents200ResponseAllOfItemsInnerToJSON,
    ListAgents200ResponseAllOfItemsInnerToJSONTyped,
} from './ListAgents200ResponseAllOfItemsInner';

/**
 * 
 * @export
 * @interface AgentListResponse
 */
export interface AgentListResponse {
    /**
     * 
     * @type {number}
     * @memberof AgentListResponse
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof AgentListResponse
     */
    limit?: number;
    /**
     * 
     * @type {number}
     * @memberof AgentListResponse
     */
    total?: number;
    /**
     * 
     * @type {Array<ListAgents200ResponseAllOfItemsInner>}
     * @memberof AgentListResponse
     */
    items?: Array<ListAgents200ResponseAllOfItemsInner>;
}

/**
 * Check if a given object implements the AgentListResponse interface.
 */
export function instanceOfAgentListResponse(value: object): value is AgentListResponse {
    return true;
}

export function AgentListResponseFromJSON(json: any): AgentListResponse {
    return AgentListResponseFromJSONTyped(json, false);
}

export function AgentListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgentListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'] == null ? undefined : json['page'],
        'limit': json['limit'] == null ? undefined : json['limit'],
        'total': json['total'] == null ? undefined : json['total'],
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(ListAgents200ResponseAllOfItemsInnerFromJSON)),
    };
}

export function AgentListResponseToJSON(json: any): AgentListResponse {
    return AgentListResponseToJSONTyped(json, false);
}

export function AgentListResponseToJSONTyped(value?: AgentListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page': value['page'],
        'limit': value['limit'],
        'total': value['total'],
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(ListAgents200ResponseAllOfItemsInnerToJSON)),
    };
}

