/* tslint:disable */
/* eslint-disable */
/**
 * BackedUp API
 * Microservices-based backup and vault management platform with encrypted backups and distributed storage
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Type of backup execution - 'worker' for cloud-managed, 'agent' for self-hosted
 * @export
 */
export const BackupJobType = {
    Worker: 'worker',
    Agent: 'agent'
} as const;
export type BackupJobType = typeof BackupJobType[keyof typeof BackupJobType];


export function instanceOfBackupJobType(value: any): boolean {
    for (const key in BackupJobType) {
        if (Object.prototype.hasOwnProperty.call(BackupJobType, key)) {
            if (BackupJobType[key as keyof typeof BackupJobType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function BackupJobTypeFromJSON(json: any): BackupJobType {
    return BackupJobTypeFromJSONTyped(json, false);
}

export function BackupJobTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): BackupJobType {
    return json as BackupJobType;
}

export function BackupJobTypeToJSON(value?: BackupJobType | null): any {
    return value as any;
}

export function BackupJobTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): BackupJobType {
    return value as BackupJobType;
}

