/* tslint:disable */
/* eslint-disable */
/**
 * Saved API
 * Microservices-based backup and vault management platform with encrypted backups and distributed storage
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CancelSubscription200Response
 */
export interface CancelSubscription200Response {
    /**
     * 
     * @type {string}
     * @memberof CancelSubscription200Response
     */
    message?: string;
}

/**
 * Check if a given object implements the CancelSubscription200Response interface.
 */
export function instanceOfCancelSubscription200Response(value: object): value is CancelSubscription200Response {
    return true;
}

export function CancelSubscription200ResponseFromJSON(json: any): CancelSubscription200Response {
    return CancelSubscription200ResponseFromJSONTyped(json, false);
}

export function CancelSubscription200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CancelSubscription200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function CancelSubscription200ResponseToJSON(json: any): CancelSubscription200Response {
    return CancelSubscription200ResponseToJSONTyped(json, false);
}

export function CancelSubscription200ResponseToJSONTyped(value?: CancelSubscription200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

