/* tslint:disable */
/* eslint-disable */
/**
 * BackedUp API
 * Microservices-based backup and vault management platform with encrypted backups and distributed storage
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ClientEncryptionKeyResponse
 */
export interface ClientEncryptionKeyResponse {
    /**
     * 
     * @type {string}
     * @memberof ClientEncryptionKeyResponse
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientEncryptionKeyResponse
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientEncryptionKeyResponse
     */
    workspace_id?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientEncryptionKeyResponse
     */
    finger_print?: string;
    /**
     * 
     * @type {Date}
     * @memberof ClientEncryptionKeyResponse
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ClientEncryptionKeyResponse
     */
    updatedAt?: Date;
}

/**
 * Check if a given object implements the ClientEncryptionKeyResponse interface.
 */
export function instanceOfClientEncryptionKeyResponse(value: object): value is ClientEncryptionKeyResponse {
    return true;
}

export function ClientEncryptionKeyResponseFromJSON(json: any): ClientEncryptionKeyResponse {
    return ClientEncryptionKeyResponseFromJSONTyped(json, false);
}

export function ClientEncryptionKeyResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClientEncryptionKeyResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'workspace_id': json['workspace_id'] == null ? undefined : json['workspace_id'],
        'finger_print': json['finger_print'] == null ? undefined : json['finger_print'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
    };
}

export function ClientEncryptionKeyResponseToJSON(json: any): ClientEncryptionKeyResponse {
    return ClientEncryptionKeyResponseToJSONTyped(json, false);
}

export function ClientEncryptionKeyResponseToJSONTyped(value?: ClientEncryptionKeyResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'workspace_id': value['workspace_id'],
        'finger_print': value['finger_print'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
    };
}

