/* tslint:disable */
/* eslint-disable */
/**
 * Saved API
 * Microservices-based backup and vault management platform with encrypted backups and distributed storage
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ClientAgentResponse
 */
export interface ClientAgentResponse {
    /**
     * 
     * @type {string}
     * @memberof ClientAgentResponse
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientAgentResponse
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientAgentResponse
     */
    workspace_id?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientAgentResponse
     */
    created_at?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientAgentResponse
     */
    updated_at?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientAgentResponse
     */
    client_id?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientAgentResponse
     */
    client_secret?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientAgentResponse
     */
    scope?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientAgentResponse
     */
    public_url?: string;
    /**
     * Current status of the agent
     * @type {string}
     * @memberof ClientAgentResponse
     */
    status?: ClientAgentResponseStatusEnum;
    /**
     * Certificate common name
     * @type {string}
     * @memberof ClientAgentResponse
     */
    certificate_cn?: string;
    /**
     * Certificate expiration date
     * @type {Date}
     * @memberof ClientAgentResponse
     */
    certificate_expiry?: Date;
    /**
     * Temporal namespace for this agent
     * @type {string}
     * @memberof ClientAgentResponse
     */
    temporal_namespace?: string;
    /**
     * Temporal task queue name
     * @type {string}
     * @memberof ClientAgentResponse
     */
    temporal_task_queue?: string;
    /**
     * Temporal host and port
     * @type {string}
     * @memberof ClientAgentResponse
     */
    temporal_host_port?: string;
}


/**
 * @export
 */
export const ClientAgentResponseStatusEnum = {
    Active: 'active',
    PendingCertificate: 'pending_certificate',
    Disabled: 'disabled'
} as const;
export type ClientAgentResponseStatusEnum = typeof ClientAgentResponseStatusEnum[keyof typeof ClientAgentResponseStatusEnum];


/**
 * Check if a given object implements the ClientAgentResponse interface.
 */
export function instanceOfClientAgentResponse(value: object): value is ClientAgentResponse {
    return true;
}

export function ClientAgentResponseFromJSON(json: any): ClientAgentResponse {
    return ClientAgentResponseFromJSONTyped(json, false);
}

export function ClientAgentResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClientAgentResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'workspace_id': json['workspace_id'] == null ? undefined : json['workspace_id'],
        'created_at': json['created_at'] == null ? undefined : json['created_at'],
        'updated_at': json['updated_at'] == null ? undefined : json['updated_at'],
        'client_id': json['client_id'] == null ? undefined : json['client_id'],
        'client_secret': json['client_secret'] == null ? undefined : json['client_secret'],
        'scope': json['scope'] == null ? undefined : json['scope'],
        'public_url': json['public_url'] == null ? undefined : json['public_url'],
        'status': json['status'] == null ? undefined : json['status'],
        'certificate_cn': json['certificate_cn'] == null ? undefined : json['certificate_cn'],
        'certificate_expiry': json['certificate_expiry'] == null ? undefined : (new Date(json['certificate_expiry'])),
        'temporal_namespace': json['temporal_namespace'] == null ? undefined : json['temporal_namespace'],
        'temporal_task_queue': json['temporal_task_queue'] == null ? undefined : json['temporal_task_queue'],
        'temporal_host_port': json['temporal_host_port'] == null ? undefined : json['temporal_host_port'],
    };
}

export function ClientAgentResponseToJSON(json: any): ClientAgentResponse {
    return ClientAgentResponseToJSONTyped(json, false);
}

export function ClientAgentResponseToJSONTyped(value?: ClientAgentResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'workspace_id': value['workspace_id'],
        'created_at': value['created_at'],
        'updated_at': value['updated_at'],
        'client_id': value['client_id'],
        'client_secret': value['client_secret'],
        'scope': value['scope'],
        'public_url': value['public_url'],
        'status': value['status'],
        'certificate_cn': value['certificate_cn'],
        'certificate_expiry': value['certificate_expiry'] == null ? undefined : ((value['certificate_expiry']).toISOString()),
        'temporal_namespace': value['temporal_namespace'],
        'temporal_task_queue': value['temporal_task_queue'],
        'temporal_host_port': value['temporal_host_port'],
    };
}

