/* tslint:disable */
/* eslint-disable */
/**
 * Saved API
 * Microservices-based backup and vault management platform with encrypted backups and distributed storage
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConfirmBackupUploadedRequest
 */
export interface ConfirmBackupUploadedRequest {
    /**
     * Actual filename
     * @type {string}
     * @memberof ConfirmBackupUploadedRequest
     */
    name: string;
    /**
     * File size in bytes
     * @type {number}
     * @memberof ConfirmBackupUploadedRequest
     */
    size: number;
    /**
     * SHA256 hash of the file
     * @type {string}
     * @memberof ConfirmBackupUploadedRequest
     */
    checksum: string;
    /**
     * MIME type of the file
     * @type {string}
     * @memberof ConfirmBackupUploadedRequest
     */
    content_type: string;
}

/**
 * Check if a given object implements the ConfirmBackupUploadedRequest interface.
 */
export function instanceOfConfirmBackupUploadedRequest(value: object): value is ConfirmBackupUploadedRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('size' in value) || value['size'] === undefined) return false;
    if (!('checksum' in value) || value['checksum'] === undefined) return false;
    if (!('content_type' in value) || value['content_type'] === undefined) return false;
    return true;
}

export function ConfirmBackupUploadedRequestFromJSON(json: any): ConfirmBackupUploadedRequest {
    return ConfirmBackupUploadedRequestFromJSONTyped(json, false);
}

export function ConfirmBackupUploadedRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfirmBackupUploadedRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'size': json['size'],
        'checksum': json['checksum'],
        'content_type': json['content_type'],
    };
}

export function ConfirmBackupUploadedRequestToJSON(json: any): ConfirmBackupUploadedRequest {
    return ConfirmBackupUploadedRequestToJSONTyped(json, false);
}

export function ConfirmBackupUploadedRequestToJSONTyped(value?: ConfirmBackupUploadedRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'size': value['size'],
        'checksum': value['checksum'],
        'content_type': value['content_type'],
    };
}

