/* tslint:disable */
/* eslint-disable */
/**
 * Saved API
 * encrypted backups and distributed storage
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConfirmCreditPurchase200Response
 */
export interface ConfirmCreditPurchase200Response {
    /**
     * 
     * @type {string}
     * @memberof ConfirmCreditPurchase200Response
     */
    workspace_id?: string;
    /**
     * 
     * @type {number}
     * @memberof ConfirmCreditPurchase200Response
     */
    balance?: number;
    /**
     * 
     * @type {string}
     * @memberof ConfirmCreditPurchase200Response
     */
    currency?: string;
}

/**
 * Check if a given object implements the ConfirmCreditPurchase200Response interface.
 */
export function instanceOfConfirmCreditPurchase200Response(value: object): value is ConfirmCreditPurchase200Response {
    return true;
}

export function ConfirmCreditPurchase200ResponseFromJSON(json: any): ConfirmCreditPurchase200Response {
    return ConfirmCreditPurchase200ResponseFromJSONTyped(json, false);
}

export function ConfirmCreditPurchase200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfirmCreditPurchase200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'workspace_id': json['workspace_id'] == null ? undefined : json['workspace_id'],
        'balance': json['balance'] == null ? undefined : json['balance'],
        'currency': json['currency'] == null ? undefined : json['currency'],
    };
}

export function ConfirmCreditPurchase200ResponseToJSON(json: any): ConfirmCreditPurchase200Response {
    return ConfirmCreditPurchase200ResponseToJSONTyped(json, false);
}

export function ConfirmCreditPurchase200ResponseToJSONTyped(value?: ConfirmCreditPurchase200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'workspace_id': value['workspace_id'],
        'balance': value['balance'],
        'currency': value['currency'],
    };
}

