/* tslint:disable */
/* eslint-disable */
/**
 * Saved API
 * encrypted backups and distributed storage
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConfirmBackup200Response
 */
export interface ConfirmBackup200Response {
    /**
     * 
     * @type {string}
     * @memberof ConfirmBackup200Response
     */
    backup_id?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ConfirmBackup200Response
     */
    status?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ConfirmBackup200Response
     */
    message?: string;
}

/**
 * Check if a given object implements the ConfirmBackup200Response interface.
 */
export function instanceOfConfirmBackup200Response(value: object): value is ConfirmBackup200Response {
    return true;
}

export function ConfirmBackup200ResponseFromJSON(json: any): ConfirmBackup200Response {
    return ConfirmBackup200ResponseFromJSONTyped(json, false);
}

export function ConfirmBackup200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfirmBackup200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'backup_id': json['backup_id'] == null ? undefined : json['backup_id'],
        'status': json['status'] == null ? undefined : json['status'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function ConfirmBackup200ResponseToJSON(json: any): ConfirmBackup200Response {
    return ConfirmBackup200ResponseToJSONTyped(json, false);
}

export function ConfirmBackup200ResponseToJSONTyped(value?: ConfirmBackup200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'backup_id': value['backup_id'],
        'status': value['status'],
        'message': value['message'],
    };
}

