/* tslint:disable */
/* eslint-disable */
/**
 * Saved API
 * encrypted backups and distributed storage
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConfirmCreditPurchaseRequest
 */
export interface ConfirmCreditPurchaseRequest {
    /**
     * 
     * @type {string}
     * @memberof ConfirmCreditPurchaseRequest
     */
    payment_intent_id: string;
}

/**
 * Check if a given object implements the ConfirmCreditPurchaseRequest interface.
 */
export function instanceOfConfirmCreditPurchaseRequest(value: object): value is ConfirmCreditPurchaseRequest {
    if (!('payment_intent_id' in value) || value['payment_intent_id'] === undefined) return false;
    return true;
}

export function ConfirmCreditPurchaseRequestFromJSON(json: any): ConfirmCreditPurchaseRequest {
    return ConfirmCreditPurchaseRequestFromJSONTyped(json, false);
}

export function ConfirmCreditPurchaseRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfirmCreditPurchaseRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'payment_intent_id': json['payment_intent_id'],
    };
}

export function ConfirmCreditPurchaseRequestToJSON(json: any): ConfirmCreditPurchaseRequest {
    return ConfirmCreditPurchaseRequestToJSONTyped(json, false);
}

export function ConfirmCreditPurchaseRequestToJSONTyped(value?: ConfirmCreditPurchaseRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'payment_intent_id': value['payment_intent_id'],
    };
}

