/* tslint:disable */
/* eslint-disable */
/**
 * Saved API
 * encrypted backups and distributed storage
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConfirmBackupRequest
 */
export interface ConfirmBackupRequest {
    /**
     * 
     * @type {boolean}
     * @memberof ConfirmBackupRequest
     */
    status?: boolean;
}

/**
 * Check if a given object implements the ConfirmBackupRequest interface.
 */
export function instanceOfConfirmBackupRequest(value: object): value is ConfirmBackupRequest {
    return true;
}

export function ConfirmBackupRequestFromJSON(json: any): ConfirmBackupRequest {
    return ConfirmBackupRequestFromJSONTyped(json, false);
}

export function ConfirmBackupRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfirmBackupRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function ConfirmBackupRequestToJSON(json: any): ConfirmBackupRequest {
    return ConfirmBackupRequestToJSONTyped(json, false);
}

export function ConfirmBackupRequestToJSONTyped(value?: ConfirmBackupRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
    };
}

