/* tslint:disable */
/* eslint-disable */
/**
 * BackedUp API
 * Microservices-based backup and vault management platform with encrypted backups and distributed storage
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateAutoBackupJson
 */
export interface CreateAutoBackupJson {
    /**
     * Type of backup execution - 'worker' for cloud-managed, 'agent' for self-hosted
     * @type {string}
     * @memberof CreateAutoBackupJson
     */
    type: CreateAutoBackupJsonTypeEnum;
    /**
     * Backup provider type (currently supports HTTP, extensible for future providers)
     * @type {string}
     * @memberof CreateAutoBackupJson
     */
    provider: CreateAutoBackupJsonProviderEnum;
    /**
     * Provider-specific backup job configuration. Required for worker jobs, optional for agent jobs (config provided in agent YAML)
     * @type {object}
     * @memberof CreateAutoBackupJson
     */
    config?: object;
    /**
     * Required when type is 'agent'
     * @type {string}
     * @memberof CreateAutoBackupJson
     */
    agent_id?: string;
    /**
     * Required when type is 'worker' (e.g., us-east-1, us-west-2)
     * @type {string}
     * @memberof CreateAutoBackupJson
     */
    zone?: string;
    /**
     * Cron expression for scheduled execution (e.g., "0 2 * * *" for daily at 2 AM)
     * @type {string}
     * @memberof CreateAutoBackupJson
     */
    schedule: string;
}


/**
 * @export
 */
export const CreateAutoBackupJsonTypeEnum = {
    Worker: 'worker',
    Agent: 'agent'
} as const;
export type CreateAutoBackupJsonTypeEnum = typeof CreateAutoBackupJsonTypeEnum[keyof typeof CreateAutoBackupJsonTypeEnum];

/**
 * @export
 */
export const CreateAutoBackupJsonProviderEnum = {
    Http: 'http'
} as const;
export type CreateAutoBackupJsonProviderEnum = typeof CreateAutoBackupJsonProviderEnum[keyof typeof CreateAutoBackupJsonProviderEnum];


/**
 * Check if a given object implements the CreateAutoBackupJson interface.
 */
export function instanceOfCreateAutoBackupJson(value: object): value is CreateAutoBackupJson {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('provider' in value) || value['provider'] === undefined) return false;
    if (!('schedule' in value) || value['schedule'] === undefined) return false;
    return true;
}

export function CreateAutoBackupJsonFromJSON(json: any): CreateAutoBackupJson {
    return CreateAutoBackupJsonFromJSONTyped(json, false);
}

export function CreateAutoBackupJsonFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAutoBackupJson {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'provider': json['provider'],
        'config': json['config'] == null ? undefined : json['config'],
        'agent_id': json['agent_id'] == null ? undefined : json['agent_id'],
        'zone': json['zone'] == null ? undefined : json['zone'],
        'schedule': json['schedule'],
    };
}

export function CreateAutoBackupJsonToJSON(json: any): CreateAutoBackupJson {
    return CreateAutoBackupJsonToJSONTyped(json, false);
}

export function CreateAutoBackupJsonToJSONTyped(value?: CreateAutoBackupJson | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'provider': value['provider'],
        'config': value['config'],
        'agent_id': value['agent_id'],
        'zone': value['zone'],
        'schedule': value['schedule'],
    };
}

