/* tslint:disable */
/* eslint-disable */
/**
 * BackedUp API
 * Microservices-based backup and vault management platform with encrypted backups and distributed storage
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateClientAgent
 */
export interface CreateClientAgent {
    /**
     * 
     * @type {string}
     * @memberof CreateClientAgent
     */
    name: string;
}

/**
 * Check if a given object implements the CreateClientAgent interface.
 */
export function instanceOfCreateClientAgent(value: object): value is CreateClientAgent {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CreateClientAgentFromJSON(json: any): CreateClientAgent {
    return CreateClientAgentFromJSONTyped(json, false);
}

export function CreateClientAgentFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateClientAgent {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function CreateClientAgentToJSON(json: any): CreateClientAgent {
    return CreateClientAgentToJSONTyped(json, false);
}

export function CreateClientAgentToJSONTyped(value?: CreateClientAgent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

