/* tslint:disable */
/* eslint-disable */
/**
 * BackedUp API
 * Microservices-based backup and vault management platform with encrypted backups and distributed storage
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateBackupRequest
 */
export interface CreateBackupRequest {
    /**
     * Backup description
     * @type {string}
     * @memberof CreateBackupRequest
     */
    description?: string;
    /**
     * List of tags for categorization
     * @type {Array<string>}
     * @memberof CreateBackupRequest
     */
    tags?: Array<string>;
    /**
     * Additional key-value metadata
     * @type {{ [key: string]: string; }}
     * @memberof CreateBackupRequest
     */
    metadata?: { [key: string]: string; };
}

/**
 * Check if a given object implements the CreateBackupRequest interface.
 */
export function instanceOfCreateBackupRequest(value: object): value is CreateBackupRequest {
    return true;
}

export function CreateBackupRequestFromJSON(json: any): CreateBackupRequest {
    return CreateBackupRequestFromJSONTyped(json, false);
}

export function CreateBackupRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateBackupRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'tags': json['tags'] == null ? undefined : json['tags'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function CreateBackupRequestToJSON(json: any): CreateBackupRequest {
    return CreateBackupRequestToJSONTyped(json, false);
}

export function CreateBackupRequestToJSONTyped(value?: CreateBackupRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'tags': value['tags'],
        'metadata': value['metadata'],
    };
}

