/* tslint:disable */
/* eslint-disable */
/**
 * Saved API
 * encrypted backups and distributed storage
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateCreditPurchase200Response
 */
export interface CreateCreditPurchase200Response {
    /**
     * 
     * @type {string}
     * @memberof CreateCreditPurchase200Response
     */
    payment_intent_id?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCreditPurchase200Response
     */
    client_secret?: string;
    /**
     * 
     * @type {number}
     * @memberof CreateCreditPurchase200Response
     */
    amount_cents?: number;
    /**
     * 
     * @type {string}
     * @memberof CreateCreditPurchase200Response
     */
    currency?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCreditPurchase200Response
     */
    status?: string;
}

/**
 * Check if a given object implements the CreateCreditPurchase200Response interface.
 */
export function instanceOfCreateCreditPurchase200Response(value: object): value is CreateCreditPurchase200Response {
    return true;
}

export function CreateCreditPurchase200ResponseFromJSON(json: any): CreateCreditPurchase200Response {
    return CreateCreditPurchase200ResponseFromJSONTyped(json, false);
}

export function CreateCreditPurchase200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCreditPurchase200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'payment_intent_id': json['payment_intent_id'] == null ? undefined : json['payment_intent_id'],
        'client_secret': json['client_secret'] == null ? undefined : json['client_secret'],
        'amount_cents': json['amount_cents'] == null ? undefined : json['amount_cents'],
        'currency': json['currency'] == null ? undefined : json['currency'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function CreateCreditPurchase200ResponseToJSON(json: any): CreateCreditPurchase200Response {
    return CreateCreditPurchase200ResponseToJSONTyped(json, false);
}

export function CreateCreditPurchase200ResponseToJSONTyped(value?: CreateCreditPurchase200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'payment_intent_id': value['payment_intent_id'],
        'client_secret': value['client_secret'],
        'amount_cents': value['amount_cents'],
        'currency': value['currency'],
        'status': value['status'],
    };
}

