/* tslint:disable */
/* eslint-disable */
/**
 * Saved API
 * Microservices-based backup and vault management platform with encrypted backups and distributed storage
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateSetupIntent200Response
 */
export interface CreateSetupIntent200Response {
    /**
     * 
     * @type {string}
     * @memberof CreateSetupIntent200Response
     */
    client_secret?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateSetupIntent200Response
     */
    id?: string;
}

/**
 * Check if a given object implements the CreateSetupIntent200Response interface.
 */
export function instanceOfCreateSetupIntent200Response(value: object): value is CreateSetupIntent200Response {
    return true;
}

export function CreateSetupIntent200ResponseFromJSON(json: any): CreateSetupIntent200Response {
    return CreateSetupIntent200ResponseFromJSONTyped(json, false);
}

export function CreateSetupIntent200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSetupIntent200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'client_secret': json['client_secret'] == null ? undefined : json['client_secret'],
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function CreateSetupIntent200ResponseToJSON(json: any): CreateSetupIntent200Response {
    return CreateSetupIntent200ResponseToJSONTyped(json, false);
}

export function CreateSetupIntent200ResponseToJSONTyped(value?: CreateSetupIntent200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'client_secret': value['client_secret'],
        'id': value['id'],
    };
}

