/* tslint:disable */
/* eslint-disable */
/**
 * BackedUp API
 * Microservices-based backup and vault management platform with encrypted backups and distributed storage
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateWorkspace
 */
export interface CreateWorkspace {
    /**
     * 
     * @type {string}
     * @memberof CreateWorkspace
     */
    name: string;
}

/**
 * Check if a given object implements the CreateWorkspace interface.
 */
export function instanceOfCreateWorkspace(value: object): value is CreateWorkspace {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CreateWorkspaceFromJSON(json: any): CreateWorkspace {
    return CreateWorkspaceFromJSONTyped(json, false);
}

export function CreateWorkspaceFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateWorkspace {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function CreateWorkspaceToJSON(json: any): CreateWorkspace {
    return CreateWorkspaceToJSONTyped(json, false);
}

export function CreateWorkspaceToJSONTyped(value?: CreateWorkspace | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

