/* tslint:disable */
/* eslint-disable */
/**
 * Saved API
 * encrypted backups and distributed storage
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateManualJobRequest
 */
export interface CreateManualJobRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateManualJobRequest
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof CreateManualJobRequest
     */
    max_backup_count: number;
    /**
     * Duration in nanoseconds
     * @type {number}
     * @memberof CreateManualJobRequest
     */
    retention_lock_period: number;
    /**
     * Duration in nanoseconds
     * @type {number}
     * @memberof CreateManualJobRequest
     */
    max_backup_age: number;
    /**
     * 
     * @type {number}
     * @memberof CreateManualJobRequest
     */
    compression_level?: number;
}

/**
 * Check if a given object implements the CreateManualJobRequest interface.
 */
export function instanceOfCreateManualJobRequest(value: object): value is CreateManualJobRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('max_backup_count' in value) || value['max_backup_count'] === undefined) return false;
    if (!('retention_lock_period' in value) || value['retention_lock_period'] === undefined) return false;
    if (!('max_backup_age' in value) || value['max_backup_age'] === undefined) return false;
    return true;
}

export function CreateManualJobRequestFromJSON(json: any): CreateManualJobRequest {
    return CreateManualJobRequestFromJSONTyped(json, false);
}

export function CreateManualJobRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateManualJobRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'max_backup_count': json['max_backup_count'],
        'retention_lock_period': json['retention_lock_period'],
        'max_backup_age': json['max_backup_age'],
        'compression_level': json['compression_level'] == null ? undefined : json['compression_level'],
    };
}

export function CreateManualJobRequestToJSON(json: any): CreateManualJobRequest {
    return CreateManualJobRequestToJSONTyped(json, false);
}

export function CreateManualJobRequestToJSONTyped(value?: CreateManualJobRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'max_backup_count': value['max_backup_count'],
        'retention_lock_period': value['retention_lock_period'],
        'max_backup_age': value['max_backup_age'],
        'compression_level': value['compression_level'],
    };
}

