/* tslint:disable */
/* eslint-disable */
/**
 * Saved API
 * encrypted backups and distributed storage
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateWorkspaceRequest
 */
export interface CreateWorkspaceRequest {
    /**
     * The name of the workspace.
     * @type {string}
     * @memberof CreateWorkspaceRequest
     */
    name: string;
    /**
     * A brief description of the workspace.
     * @type {string}
     * @memberof CreateWorkspaceRequest
     */
    description?: string;
}

/**
 * Check if a given object implements the CreateWorkspaceRequest interface.
 */
export function instanceOfCreateWorkspaceRequest(value: object): value is CreateWorkspaceRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CreateWorkspaceRequestFromJSON(json: any): CreateWorkspaceRequest {
    return CreateWorkspaceRequestFromJSONTyped(json, false);
}

export function CreateWorkspaceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateWorkspaceRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function CreateWorkspaceRequestToJSON(json: any): CreateWorkspaceRequest {
    return CreateWorkspaceRequestToJSONTyped(json, false);
}

export function CreateWorkspaceRequestToJSONTyped(value?: CreateWorkspaceRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
    };
}

