/* tslint:disable */
/* eslint-disable */
/**
 * Saved API
 * Microservices-based backup and vault management platform with encrypted backups and distributed storage
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreatePortalSessionRequest
 */
export interface CreatePortalSessionRequest {
    /**
     * 
     * @type {string}
     * @memberof CreatePortalSessionRequest
     */
    return_url?: string;
}

/**
 * Check if a given object implements the CreatePortalSessionRequest interface.
 */
export function instanceOfCreatePortalSessionRequest(value: object): value is CreatePortalSessionRequest {
    return true;
}

export function CreatePortalSessionRequestFromJSON(json: any): CreatePortalSessionRequest {
    return CreatePortalSessionRequestFromJSONTyped(json, false);
}

export function CreatePortalSessionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePortalSessionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'return_url': json['return_url'] == null ? undefined : json['return_url'],
    };
}

export function CreatePortalSessionRequestToJSON(json: any): CreatePortalSessionRequest {
    return CreatePortalSessionRequestToJSONTyped(json, false);
}

export function CreatePortalSessionRequestToJSONTyped(value?: CreatePortalSessionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'return_url': value['return_url'],
    };
}

