/* tslint:disable */
/* eslint-disable */
/**
 * BackedUp API
 * Microservices-based backup and vault management platform with encrypted backups and distributed storage
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateBackup
 */
export interface CreateBackup {
    /**
     * Backup description
     * @type {string}
     * @memberof CreateBackup
     */
    description?: string;
    /**
     * List of tags for categorization
     * @type {Array<string>}
     * @memberof CreateBackup
     */
    tags?: Array<string>;
    /**
     * Additional key-value metadata
     * @type {{ [key: string]: string; }}
     * @memberof CreateBackup
     */
    metadata?: { [key: string]: string; };
}

/**
 * Check if a given object implements the CreateBackup interface.
 */
export function instanceOfCreateBackup(value: object): value is CreateBackup {
    return true;
}

export function CreateBackupFromJSON(json: any): CreateBackup {
    return CreateBackupFromJSONTyped(json, false);
}

export function CreateBackupFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateBackup {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'tags': json['tags'] == null ? undefined : json['tags'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function CreateBackupToJSON(json: any): CreateBackup {
    return CreateBackupToJSONTyped(json, false);
}

export function CreateBackupToJSONTyped(value?: CreateBackup | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'tags': value['tags'],
        'metadata': value['metadata'],
    };
}

