/* tslint:disable */
/* eslint-disable */
/**
 * BackedUp API
 * Microservices-based backup and vault management platform with encrypted backups and distributed storage
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateAutoBackupRequest
 */
export interface CreateAutoBackupRequest {
    /**
     * Type of backup execution - 'worker' for cloud-managed, 'agent' for self-hosted
     * @type {string}
     * @memberof CreateAutoBackupRequest
     */
    type: CreateAutoBackupRequestTypeEnum;
    /**
     * Backup provider type (currently supports HTTP, extensible for future providers)
     * @type {string}
     * @memberof CreateAutoBackupRequest
     */
    provider: CreateAutoBackupRequestProviderEnum;
    /**
     * Provider-specific backup job configuration. Required for worker jobs, optional for agent jobs (config provided in agent YAML)
     * @type {object}
     * @memberof CreateAutoBackupRequest
     */
    config?: object;
    /**
     * Required when type is 'agent'
     * @type {string}
     * @memberof CreateAutoBackupRequest
     */
    agent_id?: string;
    /**
     * Required when type is 'worker' (e.g., us-east-1, us-west-2)
     * @type {string}
     * @memberof CreateAutoBackupRequest
     */
    zone?: string;
    /**
     * Cron expression for scheduled execution (e.g., "0 2 * * *" for daily at 2 AM)
     * @type {string}
     * @memberof CreateAutoBackupRequest
     */
    schedule: string;
}


/**
 * @export
 */
export const CreateAutoBackupRequestTypeEnum = {
    Worker: 'worker',
    Agent: 'agent'
} as const;
export type CreateAutoBackupRequestTypeEnum = typeof CreateAutoBackupRequestTypeEnum[keyof typeof CreateAutoBackupRequestTypeEnum];

/**
 * @export
 */
export const CreateAutoBackupRequestProviderEnum = {
    Http: 'http'
} as const;
export type CreateAutoBackupRequestProviderEnum = typeof CreateAutoBackupRequestProviderEnum[keyof typeof CreateAutoBackupRequestProviderEnum];


/**
 * Check if a given object implements the CreateAutoBackupRequest interface.
 */
export function instanceOfCreateAutoBackupRequest(value: object): value is CreateAutoBackupRequest {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('provider' in value) || value['provider'] === undefined) return false;
    if (!('schedule' in value) || value['schedule'] === undefined) return false;
    return true;
}

export function CreateAutoBackupRequestFromJSON(json: any): CreateAutoBackupRequest {
    return CreateAutoBackupRequestFromJSONTyped(json, false);
}

export function CreateAutoBackupRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAutoBackupRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'provider': json['provider'],
        'config': json['config'] == null ? undefined : json['config'],
        'agent_id': json['agent_id'] == null ? undefined : json['agent_id'],
        'zone': json['zone'] == null ? undefined : json['zone'],
        'schedule': json['schedule'],
    };
}

export function CreateAutoBackupRequestToJSON(json: any): CreateAutoBackupRequest {
    return CreateAutoBackupRequestToJSONTyped(json, false);
}

export function CreateAutoBackupRequestToJSONTyped(value?: CreateAutoBackupRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'provider': value['provider'],
        'config': value['config'],
        'agent_id': value['agent_id'],
        'zone': value['zone'],
        'schedule': value['schedule'],
    };
}

