/* tslint:disable */
/* eslint-disable */
/**
 * BackedUp API
 * Microservices-based backup and vault management platform with encrypted backups and distributed storage
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateProject
 */
export interface CreateProject {
    /**
     * 
     * @type {string}
     * @memberof CreateProject
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof CreateProject
     */
    retention_lock_period?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateProject
     */
    max_backup_count?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateProject
     */
    max_backup_age?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateProject
     */
    compression_level?: number;
}

/**
 * Check if a given object implements the CreateProject interface.
 */
export function instanceOfCreateProject(value: object): value is CreateProject {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CreateProjectFromJSON(json: any): CreateProject {
    return CreateProjectFromJSONTyped(json, false);
}

export function CreateProjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateProject {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'retention_lock_period': json['retention_lock_period'] == null ? undefined : json['retention_lock_period'],
        'max_backup_count': json['max_backup_count'] == null ? undefined : json['max_backup_count'],
        'max_backup_age': json['max_backup_age'] == null ? undefined : json['max_backup_age'],
        'compression_level': json['compression_level'] == null ? undefined : json['compression_level'],
    };
}

export function CreateProjectToJSON(json: any): CreateProject {
    return CreateProjectToJSONTyped(json, false);
}

export function CreateProjectToJSONTyped(value?: CreateProject | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'retention_lock_period': value['retention_lock_period'],
        'max_backup_count': value['max_backup_count'],
        'max_backup_age': value['max_backup_age'],
        'compression_level': value['compression_level'],
    };
}

