/* tslint:disable */
/* eslint-disable */
/**
 * Saved API
 * encrypted backups and distributed storage
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateWorkerJob201Response
 */
export interface CreateWorkerJob201Response {
    /**
     * 
     * @type {string}
     * @memberof CreateWorkerJob201Response
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateWorkerJob201Response
     */
    workspace_id?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CreateWorkerJob201Response
     */
    enabled?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CreateWorkerJob201Response
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateWorkerJob201Response
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateWorkerJob201Response
     */
    schedule?: string;
    /**
     * 
     * @type {number}
     * @memberof CreateWorkerJob201Response
     */
    max_backup_count?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateWorkerJob201Response
     */
    retention_lock_period?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateWorkerJob201Response
     */
    max_backup_age?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateWorkerJob201Response
     */
    compression_level?: number;
    /**
     * 
     * @type {string}
     * @memberof CreateWorkerJob201Response
     */
    temporal_schedule_id?: string;
    /**
     * 
     * @type {Date}
     * @memberof CreateWorkerJob201Response
     */
    created_at?: Date;
    /**
     * 
     * @type {Date}
     * @memberof CreateWorkerJob201Response
     */
    updated_at?: Date;
    /**
     * 
     * @type {string}
     * @memberof CreateWorkerJob201Response
     */
    provider?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateWorkerJob201Response
     */
    agent_id?: string;
    /**
     * 
     * @type {object}
     * @memberof CreateWorkerJob201Response
     */
    config?: object;
}

/**
 * Check if a given object implements the CreateWorkerJob201Response interface.
 */
export function instanceOfCreateWorkerJob201Response(value: object): value is CreateWorkerJob201Response {
    return true;
}

export function CreateWorkerJob201ResponseFromJSON(json: any): CreateWorkerJob201Response {
    return CreateWorkerJob201ResponseFromJSONTyped(json, false);
}

export function CreateWorkerJob201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateWorkerJob201Response {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'workspace_id': json['workspace_id'] == null ? undefined : json['workspace_id'],
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
        'name': json['name'] == null ? undefined : json['name'],
        'type': json['type'] == null ? undefined : json['type'],
        'schedule': json['schedule'] == null ? undefined : json['schedule'],
        'max_backup_count': json['max_backup_count'] == null ? undefined : json['max_backup_count'],
        'retention_lock_period': json['retention_lock_period'] == null ? undefined : json['retention_lock_period'],
        'max_backup_age': json['max_backup_age'] == null ? undefined : json['max_backup_age'],
        'compression_level': json['compression_level'] == null ? undefined : json['compression_level'],
        'temporal_schedule_id': json['temporal_schedule_id'] == null ? undefined : json['temporal_schedule_id'],
        'created_at': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updated_at': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'provider': json['provider'] == null ? undefined : json['provider'],
        'agent_id': json['agent_id'] == null ? undefined : json['agent_id'],
        'config': json['config'] == null ? undefined : json['config'],
    };
}

export function CreateWorkerJob201ResponseToJSON(json: any): CreateWorkerJob201Response {
    return CreateWorkerJob201ResponseToJSONTyped(json, false);
}

export function CreateWorkerJob201ResponseToJSONTyped(value?: CreateWorkerJob201Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'workspace_id': value['workspace_id'],
        'enabled': value['enabled'],
        'name': value['name'],
        'type': value['type'],
        'schedule': value['schedule'],
        'max_backup_count': value['max_backup_count'],
        'retention_lock_period': value['retention_lock_period'],
        'max_backup_age': value['max_backup_age'],
        'compression_level': value['compression_level'],
        'temporal_schedule_id': value['temporal_schedule_id'],
        'created_at': value['created_at'] == null ? undefined : ((value['created_at']).toISOString()),
        'updated_at': value['updated_at'] == null ? undefined : ((value['updated_at']).toISOString()),
        'provider': value['provider'],
        'agent_id': value['agent_id'],
        'config': value['config'],
    };
}

