/* tslint:disable */
/* eslint-disable */
/**
 * Saved API
 * Microservices-based backup and vault management platform with encrypted backups and distributed storage
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateSignalRequest
 */
export interface CreateSignalRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateSignalRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateSignalRequest
     */
    provider: CreateSignalRequestProviderEnum;
    /**
     * Provider-specific configuration (email or webhook)
     * @type {object}
     * @memberof CreateSignalRequest
     */
    config: object;
}


/**
 * @export
 */
export const CreateSignalRequestProviderEnum = {
    Email: 'email',
    Webhook: 'webhook'
} as const;
export type CreateSignalRequestProviderEnum = typeof CreateSignalRequestProviderEnum[keyof typeof CreateSignalRequestProviderEnum];


/**
 * Check if a given object implements the CreateSignalRequest interface.
 */
export function instanceOfCreateSignalRequest(value: object): value is CreateSignalRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('provider' in value) || value['provider'] === undefined) return false;
    if (!('config' in value) || value['config'] === undefined) return false;
    return true;
}

export function CreateSignalRequestFromJSON(json: any): CreateSignalRequest {
    return CreateSignalRequestFromJSONTyped(json, false);
}

export function CreateSignalRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSignalRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'provider': json['provider'],
        'config': json['config'],
    };
}

export function CreateSignalRequestToJSON(json: any): CreateSignalRequest {
    return CreateSignalRequestToJSONTyped(json, false);
}

export function CreateSignalRequestToJSONTyped(value?: CreateSignalRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'provider': value['provider'],
        'config': value['config'],
    };
}

