/* tslint:disable */
/* eslint-disable */
/**
 * Saved API
 * encrypted backups and distributed storage
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateCreditPurchaseRequest
 */
export interface CreateCreditPurchaseRequest {
    /**
     * 
     * @type {number}
     * @memberof CreateCreditPurchaseRequest
     */
    amount_cents: number;
}

/**
 * Check if a given object implements the CreateCreditPurchaseRequest interface.
 */
export function instanceOfCreateCreditPurchaseRequest(value: object): value is CreateCreditPurchaseRequest {
    if (!('amount_cents' in value) || value['amount_cents'] === undefined) return false;
    return true;
}

export function CreateCreditPurchaseRequestFromJSON(json: any): CreateCreditPurchaseRequest {
    return CreateCreditPurchaseRequestFromJSONTyped(json, false);
}

export function CreateCreditPurchaseRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCreditPurchaseRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'amount_cents': json['amount_cents'],
    };
}

export function CreateCreditPurchaseRequestToJSON(json: any): CreateCreditPurchaseRequest {
    return CreateCreditPurchaseRequestToJSONTyped(json, false);
}

export function CreateCreditPurchaseRequestToJSONTyped(value?: CreateCreditPurchaseRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount_cents': value['amount_cents'],
    };
}

