/* tslint:disable */
/* eslint-disable */
/**
 * Saved API
 * encrypted backups and distributed storage
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateWorkerJobRequest
 */
export interface CreateWorkerJobRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateWorkerJobRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateWorkerJobRequest
     */
    provider: CreateWorkerJobRequestProviderEnum;
    /**
     * 
     * @type {object}
     * @memberof CreateWorkerJobRequest
     */
    config?: object;
    /**
     * 
     * @type {string}
     * @memberof CreateWorkerJobRequest
     */
    schedule: string;
    /**
     * 
     * @type {number}
     * @memberof CreateWorkerJobRequest
     */
    max_backup_count: number;
    /**
     * Duration in nanoseconds
     * @type {number}
     * @memberof CreateWorkerJobRequest
     */
    retention_lock_period: number;
    /**
     * Duration in nanoseconds
     * @type {number}
     * @memberof CreateWorkerJobRequest
     */
    max_backup_age: number;
    /**
     * 
     * @type {number}
     * @memberof CreateWorkerJobRequest
     */
    compression_level?: number;
}


/**
 * @export
 */
export const CreateWorkerJobRequestProviderEnum = {
    Http: 'http',
    Ftp: 'ftp',
    Webdav: 'webdav',
    Git: 'git',
    AwsS3: 'aws.s3',
    AwsDynamodb: 'aws.dynamodb',
    Mysql: 'mysql',
    Postgres: 'postgres',
    Mssql: 'mssql',
    Redis: 'redis'
} as const;
export type CreateWorkerJobRequestProviderEnum = typeof CreateWorkerJobRequestProviderEnum[keyof typeof CreateWorkerJobRequestProviderEnum];


/**
 * Check if a given object implements the CreateWorkerJobRequest interface.
 */
export function instanceOfCreateWorkerJobRequest(value: object): value is CreateWorkerJobRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('provider' in value) || value['provider'] === undefined) return false;
    if (!('schedule' in value) || value['schedule'] === undefined) return false;
    if (!('max_backup_count' in value) || value['max_backup_count'] === undefined) return false;
    if (!('retention_lock_period' in value) || value['retention_lock_period'] === undefined) return false;
    if (!('max_backup_age' in value) || value['max_backup_age'] === undefined) return false;
    return true;
}

export function CreateWorkerJobRequestFromJSON(json: any): CreateWorkerJobRequest {
    return CreateWorkerJobRequestFromJSONTyped(json, false);
}

export function CreateWorkerJobRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateWorkerJobRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'provider': json['provider'],
        'config': json['config'] == null ? undefined : json['config'],
        'schedule': json['schedule'],
        'max_backup_count': json['max_backup_count'],
        'retention_lock_period': json['retention_lock_period'],
        'max_backup_age': json['max_backup_age'],
        'compression_level': json['compression_level'] == null ? undefined : json['compression_level'],
    };
}

export function CreateWorkerJobRequestToJSON(json: any): CreateWorkerJobRequest {
    return CreateWorkerJobRequestToJSONTyped(json, false);
}

export function CreateWorkerJobRequestToJSONTyped(value?: CreateWorkerJobRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'provider': value['provider'],
        'config': value['config'],
        'schedule': value['schedule'],
        'max_backup_count': value['max_backup_count'],
        'retention_lock_period': value['retention_lock_period'],
        'max_backup_age': value['max_backup_age'],
        'compression_level': value['compression_level'],
    };
}

