/* tslint:disable */
/* eslint-disable */
/**
 * Saved API
 * encrypted backups and distributed storage
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DownloadBackup200Response
 */
export interface DownloadBackup200Response {
    /**
     * 
     * @type {string}
     * @memberof DownloadBackup200Response
     */
    url?: string;
    /**
     * 
     * @type {Date}
     * @memberof DownloadBackup200Response
     */
    expires_at?: Date;
}

/**
 * Check if a given object implements the DownloadBackup200Response interface.
 */
export function instanceOfDownloadBackup200Response(value: object): value is DownloadBackup200Response {
    return true;
}

export function DownloadBackup200ResponseFromJSON(json: any): DownloadBackup200Response {
    return DownloadBackup200ResponseFromJSONTyped(json, false);
}

export function DownloadBackup200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DownloadBackup200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'] == null ? undefined : json['url'],
        'expires_at': json['expires_at'] == null ? undefined : (new Date(json['expires_at'])),
    };
}

export function DownloadBackup200ResponseToJSON(json: any): DownloadBackup200Response {
    return DownloadBackup200ResponseToJSONTyped(json, false);
}

export function DownloadBackup200ResponseToJSONTyped(value?: DownloadBackup200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
        'expires_at': value['expires_at'] == null ? undefined : ((value['expires_at']).toISOString()),
    };
}

