/* tslint:disable */
/* eslint-disable */
/**
 * Saved API
 * encrypted backups and distributed storage
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetBillingInfo404ResponseDetailsInner } from './GetBillingInfo404ResponseDetailsInner';
import {
    GetBillingInfo404ResponseDetailsInnerFromJSON,
    GetBillingInfo404ResponseDetailsInnerFromJSONTyped,
    GetBillingInfo404ResponseDetailsInnerToJSON,
    GetBillingInfo404ResponseDetailsInnerToJSONTyped,
} from './GetBillingInfo404ResponseDetailsInner';

/**
 * 
 * @export
 * @interface ErrorResponse
 */
export interface ErrorResponse {
    /**
     * Human-readable error message
     * @type {string}
     * @memberof ErrorResponse
     */
    message: string;
    /**
     * Machine-readable error code in SCREAMING_SNAKE_CASE
     * @type {string}
     * @memberof ErrorResponse
     */
    code: ErrorResponseCodeEnum;
    /**
     * Array of field-level validation errors (only present for validation failures)
     * @type {Array<GetBillingInfo404ResponseDetailsInner>}
     * @memberof ErrorResponse
     */
    details?: Array<GetBillingInfo404ResponseDetailsInner>;
    /**
     * OpenTelemetry trace ID for debugging
     * @type {string}
     * @memberof ErrorResponse
     */
    trace_id?: string;
}


/**
 * @export
 */
export const ErrorResponseCodeEnum = {
    BadRequest: 'BAD_REQUEST',
    Unauthorized: 'UNAUTHORIZED',
    Forbidden: 'FORBIDDEN',
    NotFound: 'NOT_FOUND',
    Conflict: 'CONFLICT',
    InternalError: 'INTERNAL_ERROR',
    ValidationFailed: 'VALIDATION_FAILED',
    UnknownError: 'UNKNOWN_ERROR'
} as const;
export type ErrorResponseCodeEnum = typeof ErrorResponseCodeEnum[keyof typeof ErrorResponseCodeEnum];


/**
 * Check if a given object implements the ErrorResponse interface.
 */
export function instanceOfErrorResponse(value: object): value is ErrorResponse {
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    return true;
}

export function ErrorResponseFromJSON(json: any): ErrorResponse {
    return ErrorResponseFromJSONTyped(json, false);
}

export function ErrorResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
        'code': json['code'],
        'details': json['details'] == null ? undefined : ((json['details'] as Array<any>).map(GetBillingInfo404ResponseDetailsInnerFromJSON)),
        'trace_id': json['trace_id'] == null ? undefined : json['trace_id'],
    };
}

export function ErrorResponseToJSON(json: any): ErrorResponse {
    return ErrorResponseToJSONTyped(json, false);
}

export function ErrorResponseToJSONTyped(value?: ErrorResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'code': value['code'],
        'details': value['details'] == null ? undefined : ((value['details'] as Array<any>).map(GetBillingInfo404ResponseDetailsInnerToJSON)),
        'trace_id': value['trace_id'],
    };
}

