/* tslint:disable */
/* eslint-disable */
/**
 * Saved API
 * encrypted backups and distributed storage
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FieldError
 */
export interface FieldError {
    /**
     * The JSON field name that failed validation
     * @type {string}
     * @memberof FieldError
     */
    field: string;
    /**
     * Human-readable validation error message
     * @type {string}
     * @memberof FieldError
     */
    message: string;
}

/**
 * Check if a given object implements the FieldError interface.
 */
export function instanceOfFieldError(value: object): value is FieldError {
    if (!('field' in value) || value['field'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function FieldErrorFromJSON(json: any): FieldError {
    return FieldErrorFromJSONTyped(json, false);
}

export function FieldErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): FieldError {
    if (json == null) {
        return json;
    }
    return {
        
        'field': json['field'],
        'message': json['message'],
    };
}

export function FieldErrorToJSON(json: any): FieldError {
    return FieldErrorToJSONTyped(json, false);
}

export function FieldErrorToJSONTyped(value?: FieldError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'field': value['field'],
        'message': value['message'],
    };
}

