/* tslint:disable */
/* eslint-disable */
/**
 * Saved API
 * encrypted backups and distributed storage
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetAgentConfigHub200ResponseTls
 */
export interface GetAgentConfigHub200ResponseTls {
    /**
     * 
     * @type {boolean}
     * @memberof GetAgentConfigHub200ResponseTls
     */
    enabled?: boolean;
}

/**
 * Check if a given object implements the GetAgentConfigHub200ResponseTls interface.
 */
export function instanceOfGetAgentConfigHub200ResponseTls(value: object): value is GetAgentConfigHub200ResponseTls {
    return true;
}

export function GetAgentConfigHub200ResponseTlsFromJSON(json: any): GetAgentConfigHub200ResponseTls {
    return GetAgentConfigHub200ResponseTlsFromJSONTyped(json, false);
}

export function GetAgentConfigHub200ResponseTlsFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAgentConfigHub200ResponseTls {
    if (json == null) {
        return json;
    }
    return {
        
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
    };
}

export function GetAgentConfigHub200ResponseTlsToJSON(json: any): GetAgentConfigHub200ResponseTls {
    return GetAgentConfigHub200ResponseTlsToJSONTyped(json, false);
}

export function GetAgentConfigHub200ResponseTlsToJSONTyped(value?: GetAgentConfigHub200ResponseTls | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'enabled': value['enabled'],
    };
}

