/* tslint:disable */
/* eslint-disable */
/**
 * Saved API
 * encrypted backups and distributed storage
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetAgentConfigHub200ResponseTls } from './GetAgentConfigHub200ResponseTls';
import {
    GetAgentConfigHub200ResponseTlsFromJSON,
    GetAgentConfigHub200ResponseTlsFromJSONTyped,
    GetAgentConfigHub200ResponseTlsToJSON,
    GetAgentConfigHub200ResponseTlsToJSONTyped,
} from './GetAgentConfigHub200ResponseTls';

/**
 * 
 * @export
 * @interface GetAgentConfigHub200Response
 */
export interface GetAgentConfigHub200Response {
    /**
     * 
     * @type {string}
     * @memberof GetAgentConfigHub200Response
     */
    server?: string;
    /**
     * 
     * @type {string}
     * @memberof GetAgentConfigHub200Response
     */
    workspace?: string;
    /**
     * 
     * @type {string}
     * @memberof GetAgentConfigHub200Response
     */
    queue?: string;
    /**
     * 
     * @type {GetAgentConfigHub200ResponseTls}
     * @memberof GetAgentConfigHub200Response
     */
    tls?: GetAgentConfigHub200ResponseTls;
}

/**
 * Check if a given object implements the GetAgentConfigHub200Response interface.
 */
export function instanceOfGetAgentConfigHub200Response(value: object): value is GetAgentConfigHub200Response {
    return true;
}

export function GetAgentConfigHub200ResponseFromJSON(json: any): GetAgentConfigHub200Response {
    return GetAgentConfigHub200ResponseFromJSONTyped(json, false);
}

export function GetAgentConfigHub200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAgentConfigHub200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'server': json['server'] == null ? undefined : json['server'],
        'workspace': json['workspace'] == null ? undefined : json['workspace'],
        'queue': json['queue'] == null ? undefined : json['queue'],
        'tls': json['tls'] == null ? undefined : GetAgentConfigHub200ResponseTlsFromJSON(json['tls']),
    };
}

export function GetAgentConfigHub200ResponseToJSON(json: any): GetAgentConfigHub200Response {
    return GetAgentConfigHub200ResponseToJSONTyped(json, false);
}

export function GetAgentConfigHub200ResponseToJSONTyped(value?: GetAgentConfigHub200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'server': value['server'],
        'workspace': value['workspace'],
        'queue': value['queue'],
        'tls': GetAgentConfigHub200ResponseTlsToJSON(value['tls']),
    };
}

