/* tslint:disable */
/* eslint-disable */
/**
 * BackedUp API
 * Microservices-based backup and vault management platform with encrypted backups and distributed storage
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetAutoBackupHistoryDetails200ResponseEventsInner
 */
export interface GetAutoBackupHistoryDetails200ResponseEventsInner {
    /**
     * 
     * @type {number}
     * @memberof GetAutoBackupHistoryDetails200ResponseEventsInner
     */
    event_id?: number;
    /**
     * 
     * @type {Date}
     * @memberof GetAutoBackupHistoryDetails200ResponseEventsInner
     */
    event_time?: Date;
    /**
     * 
     * @type {string}
     * @memberof GetAutoBackupHistoryDetails200ResponseEventsInner
     */
    event_type?: string;
    /**
     * Event-specific details
     * @type {{ [key: string]: any; }}
     * @memberof GetAutoBackupHistoryDetails200ResponseEventsInner
     */
    details?: { [key: string]: any; };
}

/**
 * Check if a given object implements the GetAutoBackupHistoryDetails200ResponseEventsInner interface.
 */
export function instanceOfGetAutoBackupHistoryDetails200ResponseEventsInner(value: object): value is GetAutoBackupHistoryDetails200ResponseEventsInner {
    return true;
}

export function GetAutoBackupHistoryDetails200ResponseEventsInnerFromJSON(json: any): GetAutoBackupHistoryDetails200ResponseEventsInner {
    return GetAutoBackupHistoryDetails200ResponseEventsInnerFromJSONTyped(json, false);
}

export function GetAutoBackupHistoryDetails200ResponseEventsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAutoBackupHistoryDetails200ResponseEventsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'event_id': json['event_id'] == null ? undefined : json['event_id'],
        'event_time': json['event_time'] == null ? undefined : (new Date(json['event_time'])),
        'event_type': json['event_type'] == null ? undefined : json['event_type'],
        'details': json['details'] == null ? undefined : json['details'],
    };
}

export function GetAutoBackupHistoryDetails200ResponseEventsInnerToJSON(json: any): GetAutoBackupHistoryDetails200ResponseEventsInner {
    return GetAutoBackupHistoryDetails200ResponseEventsInnerToJSONTyped(json, false);
}

export function GetAutoBackupHistoryDetails200ResponseEventsInnerToJSONTyped(value?: GetAutoBackupHistoryDetails200ResponseEventsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'event_id': value['event_id'],
        'event_time': value['event_time'] == null ? undefined : ((value['event_time']).toISOString()),
        'event_type': value['event_type'],
        'details': value['details'],
    };
}

