/* tslint:disable */
/* eslint-disable */
/**
 * Saved API
 * encrypted backups and distributed storage
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetBillingInfo401ResponseDetailsInner } from './GetBillingInfo401ResponseDetailsInner';
import {
    GetBillingInfo401ResponseDetailsInnerFromJSON,
    GetBillingInfo401ResponseDetailsInnerFromJSONTyped,
    GetBillingInfo401ResponseDetailsInnerToJSON,
    GetBillingInfo401ResponseDetailsInnerToJSONTyped,
} from './GetBillingInfo401ResponseDetailsInner';

/**
 * 
 * @export
 * @interface GetBillingInfo401Response
 */
export interface GetBillingInfo401Response {
    /**
     * Human-readable error message
     * @type {string}
     * @memberof GetBillingInfo401Response
     */
    message: string;
    /**
     * Machine-readable error code in SCREAMING_SNAKE_CASE
     * @type {string}
     * @memberof GetBillingInfo401Response
     */
    code: GetBillingInfo401ResponseCodeEnum;
    /**
     * Array of field-level validation errors (only present for validation failures)
     * @type {Array<GetBillingInfo401ResponseDetailsInner>}
     * @memberof GetBillingInfo401Response
     */
    details?: Array<GetBillingInfo401ResponseDetailsInner>;
    /**
     * OpenTelemetry trace ID for debugging
     * @type {string}
     * @memberof GetBillingInfo401Response
     */
    trace_id?: string;
}


/**
 * @export
 */
export const GetBillingInfo401ResponseCodeEnum = {
    BadRequest: 'BAD_REQUEST',
    Unauthorized: 'UNAUTHORIZED',
    Forbidden: 'FORBIDDEN',
    NotFound: 'NOT_FOUND',
    Conflict: 'CONFLICT',
    InternalError: 'INTERNAL_ERROR',
    ValidationFailed: 'VALIDATION_FAILED',
    UnknownError: 'UNKNOWN_ERROR'
} as const;
export type GetBillingInfo401ResponseCodeEnum = typeof GetBillingInfo401ResponseCodeEnum[keyof typeof GetBillingInfo401ResponseCodeEnum];


/**
 * Check if a given object implements the GetBillingInfo401Response interface.
 */
export function instanceOfGetBillingInfo401Response(value: object): value is GetBillingInfo401Response {
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    return true;
}

export function GetBillingInfo401ResponseFromJSON(json: any): GetBillingInfo401Response {
    return GetBillingInfo401ResponseFromJSONTyped(json, false);
}

export function GetBillingInfo401ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetBillingInfo401Response {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
        'code': json['code'],
        'details': json['details'] == null ? undefined : ((json['details'] as Array<any>).map(GetBillingInfo401ResponseDetailsInnerFromJSON)),
        'trace_id': json['trace_id'] == null ? undefined : json['trace_id'],
    };
}

export function GetBillingInfo401ResponseToJSON(json: any): GetBillingInfo401Response {
    return GetBillingInfo401ResponseToJSONTyped(json, false);
}

export function GetBillingInfo401ResponseToJSONTyped(value?: GetBillingInfo401Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'code': value['code'],
        'details': value['details'] == null ? undefined : ((value['details'] as Array<any>).map(GetBillingInfo401ResponseDetailsInnerToJSON)),
        'trace_id': value['trace_id'],
    };
}

