/* tslint:disable */
/* eslint-disable */
/**
 * Saved API
 * Microservices-based backup and vault management platform with encrypted backups and distributed storage
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetCurrentUsage200Response
 */
export interface GetCurrentUsage200Response {
    /**
     * 
     * @type {number}
     * @memberof GetCurrentUsage200Response
     */
    storage_gb?: number;
    /**
     * 
     * @type {number}
     * @memberof GetCurrentUsage200Response
     */
    computation_seconds?: number;
    /**
     * 
     * @type {number}
     * @memberof GetCurrentUsage200Response
     */
    transfer_gb?: number;
    /**
     * 
     * @type {Date}
     * @memberof GetCurrentUsage200Response
     */
    period_start?: Date;
    /**
     * 
     * @type {Date}
     * @memberof GetCurrentUsage200Response
     */
    period_end?: Date;
}

/**
 * Check if a given object implements the GetCurrentUsage200Response interface.
 */
export function instanceOfGetCurrentUsage200Response(value: object): value is GetCurrentUsage200Response {
    return true;
}

export function GetCurrentUsage200ResponseFromJSON(json: any): GetCurrentUsage200Response {
    return GetCurrentUsage200ResponseFromJSONTyped(json, false);
}

export function GetCurrentUsage200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetCurrentUsage200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'storage_gb': json['storage_gb'] == null ? undefined : json['storage_gb'],
        'computation_seconds': json['computation_seconds'] == null ? undefined : json['computation_seconds'],
        'transfer_gb': json['transfer_gb'] == null ? undefined : json['transfer_gb'],
        'period_start': json['period_start'] == null ? undefined : (new Date(json['period_start'])),
        'period_end': json['period_end'] == null ? undefined : (new Date(json['period_end'])),
    };
}

export function GetCurrentUsage200ResponseToJSON(json: any): GetCurrentUsage200Response {
    return GetCurrentUsage200ResponseToJSONTyped(json, false);
}

export function GetCurrentUsage200ResponseToJSONTyped(value?: GetCurrentUsage200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'storage_gb': value['storage_gb'],
        'computation_seconds': value['computation_seconds'],
        'transfer_gb': value['transfer_gb'],
        'period_start': value['period_start'] == null ? undefined : ((value['period_start']).toISOString()),
        'period_end': value['period_end'] == null ? undefined : ((value['period_end']).toISOString()),
    };
}

