/* tslint:disable */
/* eslint-disable */
/**
 * Saved API
 * encrypted backups and distributed storage
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetClientConfigAuth200Response
 */
export interface GetClientConfigAuth200Response {
    /**
     * 
     * @type {string}
     * @memberof GetClientConfigAuth200Response
     */
    issuer?: string;
    /**
     * 
     * @type {string}
     * @memberof GetClientConfigAuth200Response
     */
    client_id?: string;
    /**
     * 
     * @type {string}
     * @memberof GetClientConfigAuth200Response
     */
    audience?: string;
    /**
     * The Auth0 realm (e.g., "email", "sms").
     * @type {string}
     * @memberof GetClientConfigAuth200Response
     */
    realm?: string;
}

/**
 * Check if a given object implements the GetClientConfigAuth200Response interface.
 */
export function instanceOfGetClientConfigAuth200Response(value: object): value is GetClientConfigAuth200Response {
    return true;
}

export function GetClientConfigAuth200ResponseFromJSON(json: any): GetClientConfigAuth200Response {
    return GetClientConfigAuth200ResponseFromJSONTyped(json, false);
}

export function GetClientConfigAuth200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetClientConfigAuth200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'issuer': json['issuer'] == null ? undefined : json['issuer'],
        'client_id': json['client_id'] == null ? undefined : json['client_id'],
        'audience': json['audience'] == null ? undefined : json['audience'],
        'realm': json['realm'] == null ? undefined : json['realm'],
    };
}

export function GetClientConfigAuth200ResponseToJSON(json: any): GetClientConfigAuth200Response {
    return GetClientConfigAuth200ResponseToJSONTyped(json, false);
}

export function GetClientConfigAuth200ResponseToJSONTyped(value?: GetClientConfigAuth200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'issuer': value['issuer'],
        'client_id': value['client_id'],
        'audience': value['audience'],
        'realm': value['realm'],
    };
}

