/* tslint:disable */
/* eslint-disable */
/**
 * Saved API
 * encrypted backups and distributed storage
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Backup statistics for this job
 * @export
 * @interface GetJobDetails200ResponseStats
 */
export interface GetJobDetails200ResponseStats {
    /**
     * 
     * @type {number}
     * @memberof GetJobDetails200ResponseStats
     */
    total_count?: number;
    /**
     * 
     * @type {number}
     * @memberof GetJobDetails200ResponseStats
     */
    total_storage_bytes?: number;
    /**
     * 
     * @type {number}
     * @memberof GetJobDetails200ResponseStats
     */
    success_rate?: number;
}

/**
 * Check if a given object implements the GetJobDetails200ResponseStats interface.
 */
export function instanceOfGetJobDetails200ResponseStats(value: object): value is GetJobDetails200ResponseStats {
    return true;
}

export function GetJobDetails200ResponseStatsFromJSON(json: any): GetJobDetails200ResponseStats {
    return GetJobDetails200ResponseStatsFromJSONTyped(json, false);
}

export function GetJobDetails200ResponseStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetJobDetails200ResponseStats {
    if (json == null) {
        return json;
    }
    return {
        
        'total_count': json['total_count'] == null ? undefined : json['total_count'],
        'total_storage_bytes': json['total_storage_bytes'] == null ? undefined : json['total_storage_bytes'],
        'success_rate': json['success_rate'] == null ? undefined : json['success_rate'],
    };
}

export function GetJobDetails200ResponseStatsToJSON(json: any): GetJobDetails200ResponseStats {
    return GetJobDetails200ResponseStatsToJSONTyped(json, false);
}

export function GetJobDetails200ResponseStatsToJSONTyped(value?: GetJobDetails200ResponseStats | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total_count': value['total_count'],
        'total_storage_bytes': value['total_storage_bytes'],
        'success_rate': value['success_rate'],
    };
}

