/* tslint:disable */
/* eslint-disable */
/**
 * Saved API
 * encrypted backups and distributed storage
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetJob401ResponseDetailsInner } from './GetJob401ResponseDetailsInner';
import {
    GetJob401ResponseDetailsInnerFromJSON,
    GetJob401ResponseDetailsInnerFromJSONTyped,
    GetJob401ResponseDetailsInnerToJSON,
    GetJob401ResponseDetailsInnerToJSONTyped,
} from './GetJob401ResponseDetailsInner';

/**
 * 
 * @export
 * @interface GetJob401Response
 */
export interface GetJob401Response {
    /**
     * Human-readable error message
     * @type {string}
     * @memberof GetJob401Response
     */
    message: string;
    /**
     * Machine-readable error code in SCREAMING_SNAKE_CASE
     * @type {string}
     * @memberof GetJob401Response
     */
    code: GetJob401ResponseCodeEnum;
    /**
     * Array of field-level validation errors (only present for validation failures)
     * @type {Array<GetJob401ResponseDetailsInner>}
     * @memberof GetJob401Response
     */
    details?: Array<GetJob401ResponseDetailsInner>;
    /**
     * OpenTelemetry trace ID for debugging
     * @type {string}
     * @memberof GetJob401Response
     */
    trace_id?: string;
}


/**
 * @export
 */
export const GetJob401ResponseCodeEnum = {
    BadRequest: 'BAD_REQUEST',
    Unauthorized: 'UNAUTHORIZED',
    Forbidden: 'FORBIDDEN',
    NotFound: 'NOT_FOUND',
    Conflict: 'CONFLICT',
    InternalError: 'INTERNAL_ERROR',
    ValidationFailed: 'VALIDATION_FAILED',
    UnknownError: 'UNKNOWN_ERROR'
} as const;
export type GetJob401ResponseCodeEnum = typeof GetJob401ResponseCodeEnum[keyof typeof GetJob401ResponseCodeEnum];


/**
 * Check if a given object implements the GetJob401Response interface.
 */
export function instanceOfGetJob401Response(value: object): value is GetJob401Response {
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    return true;
}

export function GetJob401ResponseFromJSON(json: any): GetJob401Response {
    return GetJob401ResponseFromJSONTyped(json, false);
}

export function GetJob401ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetJob401Response {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
        'code': json['code'],
        'details': json['details'] == null ? undefined : ((json['details'] as Array<any>).map(GetJob401ResponseDetailsInnerFromJSON)),
        'trace_id': json['trace_id'] == null ? undefined : json['trace_id'],
    };
}

export function GetJob401ResponseToJSON(json: any): GetJob401Response {
    return GetJob401ResponseToJSONTyped(json, false);
}

export function GetJob401ResponseToJSONTyped(value?: GetJob401Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'code': value['code'],
        'details': value['details'] == null ? undefined : ((value['details'] as Array<any>).map(GetJob401ResponseDetailsInnerToJSON)),
        'trace_id': value['trace_id'],
    };
}

