/* tslint:disable */
/* eslint-disable */
/**
 * Saved API
 * encrypted backups and distributed storage
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ListJobs200ResponseInnerOneOf } from './ListJobs200ResponseInnerOneOf';
import {
    instanceOfListJobs200ResponseInnerOneOf,
    ListJobs200ResponseInnerOneOfFromJSON,
    ListJobs200ResponseInnerOneOfFromJSONTyped,
    ListJobs200ResponseInnerOneOfToJSON,
} from './ListJobs200ResponseInnerOneOf';
import type { ListJobs200ResponseInnerOneOf1 } from './ListJobs200ResponseInnerOneOf1';
import {
    instanceOfListJobs200ResponseInnerOneOf1,
    ListJobs200ResponseInnerOneOf1FromJSON,
    ListJobs200ResponseInnerOneOf1FromJSONTyped,
    ListJobs200ResponseInnerOneOf1ToJSON,
} from './ListJobs200ResponseInnerOneOf1';
import type { ListJobs200ResponseInnerOneOf2 } from './ListJobs200ResponseInnerOneOf2';
import {
    instanceOfListJobs200ResponseInnerOneOf2,
    ListJobs200ResponseInnerOneOf2FromJSON,
    ListJobs200ResponseInnerOneOf2FromJSONTyped,
    ListJobs200ResponseInnerOneOf2ToJSON,
} from './ListJobs200ResponseInnerOneOf2';

/**
 * @type GetJobDetails200ResponseJob
 * The job object (type varies based on job type)
 * @export
 */
export type GetJobDetails200ResponseJob = ListJobs200ResponseInnerOneOf | ListJobs200ResponseInnerOneOf1 | ListJobs200ResponseInnerOneOf2;

export function GetJobDetails200ResponseJobFromJSON(json: any): GetJobDetails200ResponseJob {
    return GetJobDetails200ResponseJobFromJSONTyped(json, false);
}

export function GetJobDetails200ResponseJobFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetJobDetails200ResponseJob {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfListJobs200ResponseInnerOneOf(json)) {
        return ListJobs200ResponseInnerOneOfFromJSONTyped(json, true);
    }
    if (instanceOfListJobs200ResponseInnerOneOf1(json)) {
        return ListJobs200ResponseInnerOneOf1FromJSONTyped(json, true);
    }
    if (instanceOfListJobs200ResponseInnerOneOf2(json)) {
        return ListJobs200ResponseInnerOneOf2FromJSONTyped(json, true);
    }

    return {} as any;
}

export function GetJobDetails200ResponseJobToJSON(json: any): any {
    return GetJobDetails200ResponseJobToJSONTyped(json, false);
}

export function GetJobDetails200ResponseJobToJSONTyped(value?: GetJobDetails200ResponseJob | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfListJobs200ResponseInnerOneOf(value)) {
        return ListJobs200ResponseInnerOneOfToJSON(value as ListJobs200ResponseInnerOneOf);
    }
    if (instanceOfListJobs200ResponseInnerOneOf1(value)) {
        return ListJobs200ResponseInnerOneOf1ToJSON(value as ListJobs200ResponseInnerOneOf1);
    }
    if (instanceOfListJobs200ResponseInnerOneOf2(value)) {
        return ListJobs200ResponseInnerOneOf2ToJSON(value as ListJobs200ResponseInnerOneOf2);
    }

    return {};
}

