/* tslint:disable */
/* eslint-disable */
/**
 * Saved API
 * Microservices-based backup and vault management platform with encrypted backups and distributed storage
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetSubscription200Response
 */
export interface GetSubscription200Response {
    /**
     * 
     * @type {string}
     * @memberof GetSubscription200Response
     */
    subscription_id?: string;
    /**
     * 
     * @type {string}
     * @memberof GetSubscription200Response
     */
    status?: GetSubscription200ResponseStatusEnum;
    /**
     * 
     * @type {Date}
     * @memberof GetSubscription200Response
     */
    current_period_start?: Date;
    /**
     * 
     * @type {Date}
     * @memberof GetSubscription200Response
     */
    current_period_end?: Date;
}


/**
 * @export
 */
export const GetSubscription200ResponseStatusEnum = {
    Active: 'active',
    PastDue: 'past_due',
    Canceled: 'canceled',
    Incomplete: 'incomplete'
} as const;
export type GetSubscription200ResponseStatusEnum = typeof GetSubscription200ResponseStatusEnum[keyof typeof GetSubscription200ResponseStatusEnum];


/**
 * Check if a given object implements the GetSubscription200Response interface.
 */
export function instanceOfGetSubscription200Response(value: object): value is GetSubscription200Response {
    return true;
}

export function GetSubscription200ResponseFromJSON(json: any): GetSubscription200Response {
    return GetSubscription200ResponseFromJSONTyped(json, false);
}

export function GetSubscription200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetSubscription200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'subscription_id': json['subscription_id'] == null ? undefined : json['subscription_id'],
        'status': json['status'] == null ? undefined : json['status'],
        'current_period_start': json['current_period_start'] == null ? undefined : (new Date(json['current_period_start'])),
        'current_period_end': json['current_period_end'] == null ? undefined : (new Date(json['current_period_end'])),
    };
}

export function GetSubscription200ResponseToJSON(json: any): GetSubscription200Response {
    return GetSubscription200ResponseToJSONTyped(json, false);
}

export function GetSubscription200ResponseToJSONTyped(value?: GetSubscription200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'subscription_id': value['subscription_id'],
        'status': value['status'],
        'current_period_start': value['current_period_start'] == null ? undefined : ((value['current_period_start']).toISOString()),
        'current_period_end': value['current_period_end'] == null ? undefined : ((value['current_period_end']).toISOString()),
    };
}

