/* tslint:disable */
/* eslint-disable */
/**
 * Saved API
 * encrypted backups and distributed storage
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetUsageHistory200ResponseMetricsInner } from './GetUsageHistory200ResponseMetricsInner';
import {
    GetUsageHistory200ResponseMetricsInnerFromJSON,
    GetUsageHistory200ResponseMetricsInnerFromJSONTyped,
    GetUsageHistory200ResponseMetricsInnerToJSON,
    GetUsageHistory200ResponseMetricsInnerToJSONTyped,
} from './GetUsageHistory200ResponseMetricsInner';

/**
 * 
 * @export
 * @interface GetUsageHistory200Response
 */
export interface GetUsageHistory200Response {
    /**
     * 
     * @type {Array<GetUsageHistory200ResponseMetricsInner>}
     * @memberof GetUsageHistory200Response
     */
    metrics?: Array<GetUsageHistory200ResponseMetricsInner>;
    /**
     * 
     * @type {number}
     * @memberof GetUsageHistory200Response
     */
    total?: number;
}

/**
 * Check if a given object implements the GetUsageHistory200Response interface.
 */
export function instanceOfGetUsageHistory200Response(value: object): value is GetUsageHistory200Response {
    return true;
}

export function GetUsageHistory200ResponseFromJSON(json: any): GetUsageHistory200Response {
    return GetUsageHistory200ResponseFromJSONTyped(json, false);
}

export function GetUsageHistory200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetUsageHistory200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'metrics': json['metrics'] == null ? undefined : ((json['metrics'] as Array<any>).map(GetUsageHistory200ResponseMetricsInnerFromJSON)),
        'total': json['total'] == null ? undefined : json['total'],
    };
}

export function GetUsageHistory200ResponseToJSON(json: any): GetUsageHistory200Response {
    return GetUsageHistory200ResponseToJSONTyped(json, false);
}

export function GetUsageHistory200ResponseToJSONTyped(value?: GetUsageHistory200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'metrics': value['metrics'] == null ? undefined : ((value['metrics'] as Array<any>).map(GetUsageHistory200ResponseMetricsInnerToJSON)),
        'total': value['total'],
    };
}

