/* tslint:disable */
/* eslint-disable */
/**
 * Saved API
 * encrypted backups and distributed storage
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetWorkspaceInfo200ResponseBillingOverview } from './GetWorkspaceInfo200ResponseBillingOverview';
import {
    GetWorkspaceInfo200ResponseBillingOverviewFromJSON,
    GetWorkspaceInfo200ResponseBillingOverviewFromJSONTyped,
    GetWorkspaceInfo200ResponseBillingOverviewToJSON,
    GetWorkspaceInfo200ResponseBillingOverviewToJSONTyped,
} from './GetWorkspaceInfo200ResponseBillingOverview';
import type { GetWorkspaceInfo200ResponseHealthStatus } from './GetWorkspaceInfo200ResponseHealthStatus';
import {
    GetWorkspaceInfo200ResponseHealthStatusFromJSON,
    GetWorkspaceInfo200ResponseHealthStatusFromJSONTyped,
    GetWorkspaceInfo200ResponseHealthStatusToJSON,
    GetWorkspaceInfo200ResponseHealthStatusToJSONTyped,
} from './GetWorkspaceInfo200ResponseHealthStatus';
import type { GetWorkspaceInfo200ResponseQuickActions } from './GetWorkspaceInfo200ResponseQuickActions';
import {
    GetWorkspaceInfo200ResponseQuickActionsFromJSON,
    GetWorkspaceInfo200ResponseQuickActionsFromJSONTyped,
    GetWorkspaceInfo200ResponseQuickActionsToJSON,
    GetWorkspaceInfo200ResponseQuickActionsToJSONTyped,
} from './GetWorkspaceInfo200ResponseQuickActions';
import type { GetWorkspaceInfo200ResponseBackupStats } from './GetWorkspaceInfo200ResponseBackupStats';
import {
    GetWorkspaceInfo200ResponseBackupStatsFromJSON,
    GetWorkspaceInfo200ResponseBackupStatsFromJSONTyped,
    GetWorkspaceInfo200ResponseBackupStatsToJSON,
    GetWorkspaceInfo200ResponseBackupStatsToJSONTyped,
} from './GetWorkspaceInfo200ResponseBackupStats';
import type { GetWorkspaceInfo200ResponseRecentActivity } from './GetWorkspaceInfo200ResponseRecentActivity';
import {
    GetWorkspaceInfo200ResponseRecentActivityFromJSON,
    GetWorkspaceInfo200ResponseRecentActivityFromJSONTyped,
    GetWorkspaceInfo200ResponseRecentActivityToJSON,
    GetWorkspaceInfo200ResponseRecentActivityToJSONTyped,
} from './GetWorkspaceInfo200ResponseRecentActivity';
import type { GetWorkspaceInfo200ResponseCostTrends } from './GetWorkspaceInfo200ResponseCostTrends';
import {
    GetWorkspaceInfo200ResponseCostTrendsFromJSON,
    GetWorkspaceInfo200ResponseCostTrendsFromJSONTyped,
    GetWorkspaceInfo200ResponseCostTrendsToJSON,
    GetWorkspaceInfo200ResponseCostTrendsToJSONTyped,
} from './GetWorkspaceInfo200ResponseCostTrends';
import type { GetWorkspaceInfo200ResponseStorageUsage } from './GetWorkspaceInfo200ResponseStorageUsage';
import {
    GetWorkspaceInfo200ResponseStorageUsageFromJSON,
    GetWorkspaceInfo200ResponseStorageUsageFromJSONTyped,
    GetWorkspaceInfo200ResponseStorageUsageToJSON,
    GetWorkspaceInfo200ResponseStorageUsageToJSONTyped,
} from './GetWorkspaceInfo200ResponseStorageUsage';
import type { GetWorkspaceInfo200ResponseJobStats } from './GetWorkspaceInfo200ResponseJobStats';
import {
    GetWorkspaceInfo200ResponseJobStatsFromJSON,
    GetWorkspaceInfo200ResponseJobStatsFromJSONTyped,
    GetWorkspaceInfo200ResponseJobStatsToJSON,
    GetWorkspaceInfo200ResponseJobStatsToJSONTyped,
} from './GetWorkspaceInfo200ResponseJobStats';
import type { GetWorkspaceInfo200ResponseBackupTrendsInner } from './GetWorkspaceInfo200ResponseBackupTrendsInner';
import {
    GetWorkspaceInfo200ResponseBackupTrendsInnerFromJSON,
    GetWorkspaceInfo200ResponseBackupTrendsInnerFromJSONTyped,
    GetWorkspaceInfo200ResponseBackupTrendsInnerToJSON,
    GetWorkspaceInfo200ResponseBackupTrendsInnerToJSONTyped,
} from './GetWorkspaceInfo200ResponseBackupTrendsInner';
import type { GetWorkspaceInfo200ResponseAgentStats } from './GetWorkspaceInfo200ResponseAgentStats';
import {
    GetWorkspaceInfo200ResponseAgentStatsFromJSON,
    GetWorkspaceInfo200ResponseAgentStatsFromJSONTyped,
    GetWorkspaceInfo200ResponseAgentStatsToJSON,
    GetWorkspaceInfo200ResponseAgentStatsToJSONTyped,
} from './GetWorkspaceInfo200ResponseAgentStats';

/**
 * 
 * @export
 * @interface GetWorkspaceInfo200Response
 */
export interface GetWorkspaceInfo200Response {
    /**
     * 
     * @type {GetWorkspaceInfo200ResponseJobStats}
     * @memberof GetWorkspaceInfo200Response
     */
    job_stats?: GetWorkspaceInfo200ResponseJobStats;
    /**
     * 
     * @type {GetWorkspaceInfo200ResponseBackupStats}
     * @memberof GetWorkspaceInfo200Response
     */
    backup_stats?: GetWorkspaceInfo200ResponseBackupStats;
    /**
     * 
     * @type {GetWorkspaceInfo200ResponseAgentStats}
     * @memberof GetWorkspaceInfo200Response
     */
    agent_stats?: GetWorkspaceInfo200ResponseAgentStats;
    /**
     * 
     * @type {GetWorkspaceInfo200ResponseBillingOverview}
     * @memberof GetWorkspaceInfo200Response
     */
    billing_overview?: GetWorkspaceInfo200ResponseBillingOverview;
    /**
     * 
     * @type {GetWorkspaceInfo200ResponseStorageUsage}
     * @memberof GetWorkspaceInfo200Response
     */
    storage_usage?: GetWorkspaceInfo200ResponseStorageUsage;
    /**
     * 
     * @type {GetWorkspaceInfo200ResponseRecentActivity}
     * @memberof GetWorkspaceInfo200Response
     */
    recent_activity?: GetWorkspaceInfo200ResponseRecentActivity;
    /**
     * 
     * @type {Array<GetWorkspaceInfo200ResponseBackupTrendsInner>}
     * @memberof GetWorkspaceInfo200Response
     */
    backup_trends?: Array<GetWorkspaceInfo200ResponseBackupTrendsInner>;
    /**
     * 
     * @type {GetWorkspaceInfo200ResponseCostTrends}
     * @memberof GetWorkspaceInfo200Response
     */
    cost_trends?: GetWorkspaceInfo200ResponseCostTrends;
    /**
     * 
     * @type {GetWorkspaceInfo200ResponseHealthStatus}
     * @memberof GetWorkspaceInfo200Response
     */
    health_status?: GetWorkspaceInfo200ResponseHealthStatus;
    /**
     * 
     * @type {GetWorkspaceInfo200ResponseQuickActions}
     * @memberof GetWorkspaceInfo200Response
     */
    quick_actions?: GetWorkspaceInfo200ResponseQuickActions;
}

/**
 * Check if a given object implements the GetWorkspaceInfo200Response interface.
 */
export function instanceOfGetWorkspaceInfo200Response(value: object): value is GetWorkspaceInfo200Response {
    return true;
}

export function GetWorkspaceInfo200ResponseFromJSON(json: any): GetWorkspaceInfo200Response {
    return GetWorkspaceInfo200ResponseFromJSONTyped(json, false);
}

export function GetWorkspaceInfo200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetWorkspaceInfo200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'job_stats': json['job_stats'] == null ? undefined : GetWorkspaceInfo200ResponseJobStatsFromJSON(json['job_stats']),
        'backup_stats': json['backup_stats'] == null ? undefined : GetWorkspaceInfo200ResponseBackupStatsFromJSON(json['backup_stats']),
        'agent_stats': json['agent_stats'] == null ? undefined : GetWorkspaceInfo200ResponseAgentStatsFromJSON(json['agent_stats']),
        'billing_overview': json['billing_overview'] == null ? undefined : GetWorkspaceInfo200ResponseBillingOverviewFromJSON(json['billing_overview']),
        'storage_usage': json['storage_usage'] == null ? undefined : GetWorkspaceInfo200ResponseStorageUsageFromJSON(json['storage_usage']),
        'recent_activity': json['recent_activity'] == null ? undefined : GetWorkspaceInfo200ResponseRecentActivityFromJSON(json['recent_activity']),
        'backup_trends': json['backup_trends'] == null ? undefined : ((json['backup_trends'] as Array<any>).map(GetWorkspaceInfo200ResponseBackupTrendsInnerFromJSON)),
        'cost_trends': json['cost_trends'] == null ? undefined : GetWorkspaceInfo200ResponseCostTrendsFromJSON(json['cost_trends']),
        'health_status': json['health_status'] == null ? undefined : GetWorkspaceInfo200ResponseHealthStatusFromJSON(json['health_status']),
        'quick_actions': json['quick_actions'] == null ? undefined : GetWorkspaceInfo200ResponseQuickActionsFromJSON(json['quick_actions']),
    };
}

export function GetWorkspaceInfo200ResponseToJSON(json: any): GetWorkspaceInfo200Response {
    return GetWorkspaceInfo200ResponseToJSONTyped(json, false);
}

export function GetWorkspaceInfo200ResponseToJSONTyped(value?: GetWorkspaceInfo200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'job_stats': GetWorkspaceInfo200ResponseJobStatsToJSON(value['job_stats']),
        'backup_stats': GetWorkspaceInfo200ResponseBackupStatsToJSON(value['backup_stats']),
        'agent_stats': GetWorkspaceInfo200ResponseAgentStatsToJSON(value['agent_stats']),
        'billing_overview': GetWorkspaceInfo200ResponseBillingOverviewToJSON(value['billing_overview']),
        'storage_usage': GetWorkspaceInfo200ResponseStorageUsageToJSON(value['storage_usage']),
        'recent_activity': GetWorkspaceInfo200ResponseRecentActivityToJSON(value['recent_activity']),
        'backup_trends': value['backup_trends'] == null ? undefined : ((value['backup_trends'] as Array<any>).map(GetWorkspaceInfo200ResponseBackupTrendsInnerToJSON)),
        'cost_trends': GetWorkspaceInfo200ResponseCostTrendsToJSON(value['cost_trends']),
        'health_status': GetWorkspaceInfo200ResponseHealthStatusToJSON(value['health_status']),
        'quick_actions': GetWorkspaceInfo200ResponseQuickActionsToJSON(value['quick_actions']),
    };
}

