/* tslint:disable */
/* eslint-disable */
/**
 * Saved API
 * encrypted backups and distributed storage
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetWorkspaceInfo200ResponseJobStats
 */
export interface GetWorkspaceInfo200ResponseJobStats {
    /**
     * 
     * @type {number}
     * @memberof GetWorkspaceInfo200ResponseJobStats
     */
    total_jobs?: number;
    /**
     * 
     * @type {number}
     * @memberof GetWorkspaceInfo200ResponseJobStats
     */
    active_jobs?: number;
    /**
     * 
     * @type {number}
     * @memberof GetWorkspaceInfo200ResponseJobStats
     */
    inactive_jobs?: number;
    /**
     * 
     * @type {number}
     * @memberof GetWorkspaceInfo200ResponseJobStats
     */
    worker_jobs?: number;
    /**
     * 
     * @type {number}
     * @memberof GetWorkspaceInfo200ResponseJobStats
     */
    agent_jobs?: number;
    /**
     * 
     * @type {number}
     * @memberof GetWorkspaceInfo200ResponseJobStats
     */
    manual_jobs?: number;
}

/**
 * Check if a given object implements the GetWorkspaceInfo200ResponseJobStats interface.
 */
export function instanceOfGetWorkspaceInfo200ResponseJobStats(value: object): value is GetWorkspaceInfo200ResponseJobStats {
    return true;
}

export function GetWorkspaceInfo200ResponseJobStatsFromJSON(json: any): GetWorkspaceInfo200ResponseJobStats {
    return GetWorkspaceInfo200ResponseJobStatsFromJSONTyped(json, false);
}

export function GetWorkspaceInfo200ResponseJobStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetWorkspaceInfo200ResponseJobStats {
    if (json == null) {
        return json;
    }
    return {
        
        'total_jobs': json['total_jobs'] == null ? undefined : json['total_jobs'],
        'active_jobs': json['active_jobs'] == null ? undefined : json['active_jobs'],
        'inactive_jobs': json['inactive_jobs'] == null ? undefined : json['inactive_jobs'],
        'worker_jobs': json['worker_jobs'] == null ? undefined : json['worker_jobs'],
        'agent_jobs': json['agent_jobs'] == null ? undefined : json['agent_jobs'],
        'manual_jobs': json['manual_jobs'] == null ? undefined : json['manual_jobs'],
    };
}

export function GetWorkspaceInfo200ResponseJobStatsToJSON(json: any): GetWorkspaceInfo200ResponseJobStats {
    return GetWorkspaceInfo200ResponseJobStatsToJSONTyped(json, false);
}

export function GetWorkspaceInfo200ResponseJobStatsToJSONTyped(value?: GetWorkspaceInfo200ResponseJobStats | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total_jobs': value['total_jobs'],
        'active_jobs': value['active_jobs'],
        'inactive_jobs': value['inactive_jobs'],
        'worker_jobs': value['worker_jobs'],
        'agent_jobs': value['agent_jobs'],
        'manual_jobs': value['manual_jobs'],
    };
}

