/* tslint:disable */
/* eslint-disable */
/**
 * Saved API
 * encrypted backups and distributed storage
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetWorkspaceInfo200ResponseRecentActivity
 */
export interface GetWorkspaceInfo200ResponseRecentActivity {
    /**
     * 
     * @type {Date}
     * @memberof GetWorkspaceInfo200ResponseRecentActivity
     */
    last_backup_at?: Date;
    /**
     * 
     * @type {Date}
     * @memberof GetWorkspaceInfo200ResponseRecentActivity
     */
    last_successful_backup_at?: Date;
    /**
     * 
     * @type {number}
     * @memberof GetWorkspaceInfo200ResponseRecentActivity
     */
    recent_failures_count?: number;
}

/**
 * Check if a given object implements the GetWorkspaceInfo200ResponseRecentActivity interface.
 */
export function instanceOfGetWorkspaceInfo200ResponseRecentActivity(value: object): value is GetWorkspaceInfo200ResponseRecentActivity {
    return true;
}

export function GetWorkspaceInfo200ResponseRecentActivityFromJSON(json: any): GetWorkspaceInfo200ResponseRecentActivity {
    return GetWorkspaceInfo200ResponseRecentActivityFromJSONTyped(json, false);
}

export function GetWorkspaceInfo200ResponseRecentActivityFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetWorkspaceInfo200ResponseRecentActivity {
    if (json == null) {
        return json;
    }
    return {
        
        'last_backup_at': json['last_backup_at'] == null ? undefined : (new Date(json['last_backup_at'])),
        'last_successful_backup_at': json['last_successful_backup_at'] == null ? undefined : (new Date(json['last_successful_backup_at'])),
        'recent_failures_count': json['recent_failures_count'] == null ? undefined : json['recent_failures_count'],
    };
}

export function GetWorkspaceInfo200ResponseRecentActivityToJSON(json: any): GetWorkspaceInfo200ResponseRecentActivity {
    return GetWorkspaceInfo200ResponseRecentActivityToJSONTyped(json, false);
}

export function GetWorkspaceInfo200ResponseRecentActivityToJSONTyped(value?: GetWorkspaceInfo200ResponseRecentActivity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'last_backup_at': value['last_backup_at'] == null ? undefined : ((value['last_backup_at']).toISOString()),
        'last_successful_backup_at': value['last_successful_backup_at'] == null ? undefined : ((value['last_successful_backup_at']).toISOString()),
        'recent_failures_count': value['recent_failures_count'],
    };
}

