/* tslint:disable */
/* eslint-disable */
/**
 * Saved API
 * encrypted backups and distributed storage
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GitConfig
 */
export interface GitConfig {
    /**
     * 
     * @type {string}
     * @memberof GitConfig
     */
    url: string;
    /**
     * Branch to clone. Defaults to main.
     * @type {string}
     * @memberof GitConfig
     */
    branch?: string;
    /**
     * If true, includes .git dir with full history for all branches.
     * @type {boolean}
     * @memberof GitConfig
     */
    include_git_history?: boolean;
    /**
     * 
     * @type {string}
     * @memberof GitConfig
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof GitConfig
     */
    password?: string;
    /**
     * 
     * @type {string}
     * @memberof GitConfig
     */
    private_key?: string;
    /**
     * 
     * @type {string}
     * @memberof GitConfig
     */
    passphrase?: string;
    /**
     * Shallow clone depth. 0 means full history.
     * @type {number}
     * @memberof GitConfig
     */
    depth?: number;
    /**
     * 
     * @type {boolean}
     * @memberof GitConfig
     */
    submodules?: boolean;
}

/**
 * Check if a given object implements the GitConfig interface.
 */
export function instanceOfGitConfig(value: object): value is GitConfig {
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function GitConfigFromJSON(json: any): GitConfig {
    return GitConfigFromJSONTyped(json, false);
}

export function GitConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): GitConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'],
        'branch': json['branch'] == null ? undefined : json['branch'],
        'include_git_history': json['include_git_history'] == null ? undefined : json['include_git_history'],
        'username': json['username'] == null ? undefined : json['username'],
        'password': json['password'] == null ? undefined : json['password'],
        'private_key': json['private_key'] == null ? undefined : json['private_key'],
        'passphrase': json['passphrase'] == null ? undefined : json['passphrase'],
        'depth': json['depth'] == null ? undefined : json['depth'],
        'submodules': json['submodules'] == null ? undefined : json['submodules'],
    };
}

export function GitConfigToJSON(json: any): GitConfig {
    return GitConfigToJSONTyped(json, false);
}

export function GitConfigToJSONTyped(value?: GitConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
        'branch': value['branch'],
        'include_git_history': value['include_git_history'],
        'username': value['username'],
        'password': value['password'],
        'private_key': value['private_key'],
        'passphrase': value['passphrase'],
        'depth': value['depth'],
        'submodules': value['submodules'],
    };
}

