/* tslint:disable */
/* eslint-disable */
/**
 * Saved API
 * Microservices-based backup and vault management platform with encrypted backups and distributed storage
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListInvoices200ResponseInner
 */
export interface ListInvoices200ResponseInner {
    /**
     * 
     * @type {string}
     * @memberof ListInvoices200ResponseInner
     */
    id?: string;
    /**
     * 
     * @type {number}
     * @memberof ListInvoices200ResponseInner
     */
    amount_due?: number;
    /**
     * 
     * @type {string}
     * @memberof ListInvoices200ResponseInner
     */
    status?: string;
    /**
     * 
     * @type {number}
     * @memberof ListInvoices200ResponseInner
     */
    created?: number;
}

/**
 * Check if a given object implements the ListInvoices200ResponseInner interface.
 */
export function instanceOfListInvoices200ResponseInner(value: object): value is ListInvoices200ResponseInner {
    return true;
}

export function ListInvoices200ResponseInnerFromJSON(json: any): ListInvoices200ResponseInner {
    return ListInvoices200ResponseInnerFromJSONTyped(json, false);
}

export function ListInvoices200ResponseInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListInvoices200ResponseInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'amount_due': json['amount_due'] == null ? undefined : json['amount_due'],
        'status': json['status'] == null ? undefined : json['status'],
        'created': json['created'] == null ? undefined : json['created'],
    };
}

export function ListInvoices200ResponseInnerToJSON(json: any): ListInvoices200ResponseInner {
    return ListInvoices200ResponseInnerToJSONTyped(json, false);
}

export function ListInvoices200ResponseInnerToJSONTyped(value?: ListInvoices200ResponseInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'amount_due': value['amount_due'],
        'status': value['status'],
        'created': value['created'],
    };
}

