/* tslint:disable */
/* eslint-disable */
/**
 * BackedUp API
 * Microservices-based backup and vault management platform with encrypted backups and distributed storage
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListBackups200ResponseAllOfItemsInner
 */
export interface ListBackups200ResponseAllOfItemsInner {
    /**
     * 
     * @type {string}
     * @memberof ListBackups200ResponseAllOfItemsInner
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ListBackups200ResponseAllOfItemsInner
     */
    workspace_id?: string;
    /**
     * 
     * @type {string}
     * @memberof ListBackups200ResponseAllOfItemsInner
     */
    vault_id?: string;
    /**
     * 
     * @type {string}
     * @memberof ListBackups200ResponseAllOfItemsInner
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ListBackups200ResponseAllOfItemsInner
     */
    description?: string;
    /**
     * List of tags
     * @type {Array<string>}
     * @memberof ListBackups200ResponseAllOfItemsInner
     */
    tags?: Array<string>;
    /**
     * SHA256 hash of the backup file
     * @type {string}
     * @memberof ListBackups200ResponseAllOfItemsInner
     */
    checksum?: string;
    /**
     * Size of the backup in bytes
     * @type {number}
     * @memberof ListBackups200ResponseAllOfItemsInner
     */
    size?: number;
    /**
     * MIME type of the file
     * @type {string}
     * @memberof ListBackups200ResponseAllOfItemsInner
     */
    content_type?: string;
    /**
     * Current status of the backup
     * @type {string}
     * @memberof ListBackups200ResponseAllOfItemsInner
     */
    status?: ListBackups200ResponseAllOfItemsInnerStatusEnum;
    /**
     * 
     * @type {Date}
     * @memberof ListBackups200ResponseAllOfItemsInner
     */
    created_at?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ListBackups200ResponseAllOfItemsInner
     */
    updated_at?: Date;
    /**
     * Whether the backup upload has been confirmed
     * @type {boolean}
     * @memberof ListBackups200ResponseAllOfItemsInner
     */
    confirmed?: boolean;
    /**
     * Whether the backup has been verified
     * @type {boolean}
     * @memberof ListBackups200ResponseAllOfItemsInner
     */
    verified?: boolean;
    /**
     * S3 presigned URL for backup upload/download
     * @type {string}
     * @memberof ListBackups200ResponseAllOfItemsInner
     */
    presigned_url?: string;
    /**
     * When the presigned URL expires
     * @type {Date}
     * @memberof ListBackups200ResponseAllOfItemsInner
     */
    presigned_url_expires_at?: Date;
    /**
     * Temporal workflow ID
     * @type {string}
     * @memberof ListBackups200ResponseAllOfItemsInner
     */
    workflow_id?: string;
}


/**
 * @export
 */
export const ListBackups200ResponseAllOfItemsInnerStatusEnum = {
    Pending: 'pending',
    Uploading: 'uploading',
    Processing: 'processing',
    Completed: 'completed',
    CompletedWithErrors: 'completed_with_errors',
    Failed: 'failed'
} as const;
export type ListBackups200ResponseAllOfItemsInnerStatusEnum = typeof ListBackups200ResponseAllOfItemsInnerStatusEnum[keyof typeof ListBackups200ResponseAllOfItemsInnerStatusEnum];


/**
 * Check if a given object implements the ListBackups200ResponseAllOfItemsInner interface.
 */
export function instanceOfListBackups200ResponseAllOfItemsInner(value: object): value is ListBackups200ResponseAllOfItemsInner {
    return true;
}

export function ListBackups200ResponseAllOfItemsInnerFromJSON(json: any): ListBackups200ResponseAllOfItemsInner {
    return ListBackups200ResponseAllOfItemsInnerFromJSONTyped(json, false);
}

export function ListBackups200ResponseAllOfItemsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListBackups200ResponseAllOfItemsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'workspace_id': json['workspace_id'] == null ? undefined : json['workspace_id'],
        'vault_id': json['vault_id'] == null ? undefined : json['vault_id'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'tags': json['tags'] == null ? undefined : json['tags'],
        'checksum': json['checksum'] == null ? undefined : json['checksum'],
        'size': json['size'] == null ? undefined : json['size'],
        'content_type': json['content_type'] == null ? undefined : json['content_type'],
        'status': json['status'] == null ? undefined : json['status'],
        'created_at': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updated_at': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'confirmed': json['confirmed'] == null ? undefined : json['confirmed'],
        'verified': json['verified'] == null ? undefined : json['verified'],
        'presigned_url': json['presigned_url'] == null ? undefined : json['presigned_url'],
        'presigned_url_expires_at': json['presigned_url_expires_at'] == null ? undefined : (new Date(json['presigned_url_expires_at'])),
        'workflow_id': json['workflow_id'] == null ? undefined : json['workflow_id'],
    };
}

export function ListBackups200ResponseAllOfItemsInnerToJSON(json: any): ListBackups200ResponseAllOfItemsInner {
    return ListBackups200ResponseAllOfItemsInnerToJSONTyped(json, false);
}

export function ListBackups200ResponseAllOfItemsInnerToJSONTyped(value?: ListBackups200ResponseAllOfItemsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'workspace_id': value['workspace_id'],
        'vault_id': value['vault_id'],
        'name': value['name'],
        'description': value['description'],
        'tags': value['tags'],
        'checksum': value['checksum'],
        'size': value['size'],
        'content_type': value['content_type'],
        'status': value['status'],
        'created_at': value['created_at'] == null ? undefined : ((value['created_at']).toISOString()),
        'updated_at': value['updated_at'] == null ? undefined : ((value['updated_at']).toISOString()),
        'confirmed': value['confirmed'],
        'verified': value['verified'],
        'presigned_url': value['presigned_url'],
        'presigned_url_expires_at': value['presigned_url_expires_at'] == null ? undefined : ((value['presigned_url_expires_at']).toISOString()),
        'workflow_id': value['workflow_id'],
    };
}

