/* tslint:disable */
/* eslint-disable */
/**
 * Saved API
 * Microservices-based backup and vault management platform with encrypted backups and distributed storage
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListAutoBackupExecutions200ResponseExecutionsInner
 */
export interface ListAutoBackupExecutions200ResponseExecutionsInner {
    /**
     * Temporal workflow ID
     * @type {string}
     * @memberof ListAutoBackupExecutions200ResponseExecutionsInner
     */
    workflow_id?: string;
    /**
     * Temporal run ID
     * @type {string}
     * @memberof ListAutoBackupExecutions200ResponseExecutionsInner
     */
    run_id?: string;
    /**
     * Execution status (e.g., Running, Completed, Failed)
     * @type {string}
     * @memberof ListAutoBackupExecutions200ResponseExecutionsInner
     */
    status?: string;
    /**
     * 
     * @type {Date}
     * @memberof ListAutoBackupExecutions200ResponseExecutionsInner
     */
    start_time?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ListAutoBackupExecutions200ResponseExecutionsInner
     */
    close_time?: Date;
    /**
     * Execution duration in milliseconds
     * @type {number}
     * @memberof ListAutoBackupExecutions200ResponseExecutionsInner
     */
    execution_time?: number;
}

/**
 * Check if a given object implements the ListAutoBackupExecutions200ResponseExecutionsInner interface.
 */
export function instanceOfListAutoBackupExecutions200ResponseExecutionsInner(value: object): value is ListAutoBackupExecutions200ResponseExecutionsInner {
    return true;
}

export function ListAutoBackupExecutions200ResponseExecutionsInnerFromJSON(json: any): ListAutoBackupExecutions200ResponseExecutionsInner {
    return ListAutoBackupExecutions200ResponseExecutionsInnerFromJSONTyped(json, false);
}

export function ListAutoBackupExecutions200ResponseExecutionsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListAutoBackupExecutions200ResponseExecutionsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'workflow_id': json['workflow_id'] == null ? undefined : json['workflow_id'],
        'run_id': json['run_id'] == null ? undefined : json['run_id'],
        'status': json['status'] == null ? undefined : json['status'],
        'start_time': json['start_time'] == null ? undefined : (new Date(json['start_time'])),
        'close_time': json['close_time'] == null ? undefined : (new Date(json['close_time'])),
        'execution_time': json['execution_time'] == null ? undefined : json['execution_time'],
    };
}

export function ListAutoBackupExecutions200ResponseExecutionsInnerToJSON(json: any): ListAutoBackupExecutions200ResponseExecutionsInner {
    return ListAutoBackupExecutions200ResponseExecutionsInnerToJSONTyped(json, false);
}

export function ListAutoBackupExecutions200ResponseExecutionsInnerToJSONTyped(value?: ListAutoBackupExecutions200ResponseExecutionsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'workflow_id': value['workflow_id'],
        'run_id': value['run_id'],
        'status': value['status'],
        'start_time': value['start_time'] == null ? undefined : ((value['start_time']).toISOString()),
        'close_time': value['close_time'] == null ? undefined : ((value['close_time']).toISOString()),
        'execution_time': value['execution_time'],
    };
}

