/* tslint:disable */
/* eslint-disable */
/**
 * Saved API
 * Microservices-based backup and vault management platform with encrypted backups and distributed storage
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListAutoBackupExecutions200ResponseExecutionsInner } from './ListAutoBackupExecutions200ResponseExecutionsInner';
import {
    ListAutoBackupExecutions200ResponseExecutionsInnerFromJSON,
    ListAutoBackupExecutions200ResponseExecutionsInnerFromJSONTyped,
    ListAutoBackupExecutions200ResponseExecutionsInnerToJSON,
    ListAutoBackupExecutions200ResponseExecutionsInnerToJSONTyped,
} from './ListAutoBackupExecutions200ResponseExecutionsInner';

/**
 * 
 * @export
 * @interface ListAutoBackupExecutions200Response
 */
export interface ListAutoBackupExecutions200Response {
    /**
     * 
     * @type {Array<ListAutoBackupExecutions200ResponseExecutionsInner>}
     * @memberof ListAutoBackupExecutions200Response
     */
    executions?: Array<ListAutoBackupExecutions200ResponseExecutionsInner>;
}

/**
 * Check if a given object implements the ListAutoBackupExecutions200Response interface.
 */
export function instanceOfListAutoBackupExecutions200Response(value: object): value is ListAutoBackupExecutions200Response {
    return true;
}

export function ListAutoBackupExecutions200ResponseFromJSON(json: any): ListAutoBackupExecutions200Response {
    return ListAutoBackupExecutions200ResponseFromJSONTyped(json, false);
}

export function ListAutoBackupExecutions200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListAutoBackupExecutions200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'executions': json['executions'] == null ? undefined : ((json['executions'] as Array<any>).map(ListAutoBackupExecutions200ResponseExecutionsInnerFromJSON)),
    };
}

export function ListAutoBackupExecutions200ResponseToJSON(json: any): ListAutoBackupExecutions200Response {
    return ListAutoBackupExecutions200ResponseToJSONTyped(json, false);
}

export function ListAutoBackupExecutions200ResponseToJSONTyped(value?: ListAutoBackupExecutions200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'executions': value['executions'] == null ? undefined : ((value['executions'] as Array<any>).map(ListAutoBackupExecutions200ResponseExecutionsInnerToJSON)),
    };
}

