/* tslint:disable */
/* eslint-disable */
/**
 * Saved API
 * Microservices-based backup and vault management platform with encrypted backups and distributed storage
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListWorkspaces200ResponseAllOfItemsInner } from './ListWorkspaces200ResponseAllOfItemsInner';
import {
    ListWorkspaces200ResponseAllOfItemsInnerFromJSON,
    ListWorkspaces200ResponseAllOfItemsInnerFromJSONTyped,
    ListWorkspaces200ResponseAllOfItemsInnerToJSON,
    ListWorkspaces200ResponseAllOfItemsInnerToJSONTyped,
} from './ListWorkspaces200ResponseAllOfItemsInner';

/**
 * 
 * @export
 * @interface ListWorkspaces200Response
 */
export interface ListWorkspaces200Response {
    /**
     * 
     * @type {number}
     * @memberof ListWorkspaces200Response
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof ListWorkspaces200Response
     */
    limit?: number;
    /**
     * 
     * @type {number}
     * @memberof ListWorkspaces200Response
     */
    total?: number;
    /**
     * 
     * @type {Array<ListWorkspaces200ResponseAllOfItemsInner>}
     * @memberof ListWorkspaces200Response
     */
    items?: Array<ListWorkspaces200ResponseAllOfItemsInner>;
}

/**
 * Check if a given object implements the ListWorkspaces200Response interface.
 */
export function instanceOfListWorkspaces200Response(value: object): value is ListWorkspaces200Response {
    return true;
}

export function ListWorkspaces200ResponseFromJSON(json: any): ListWorkspaces200Response {
    return ListWorkspaces200ResponseFromJSONTyped(json, false);
}

export function ListWorkspaces200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListWorkspaces200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'] == null ? undefined : json['page'],
        'limit': json['limit'] == null ? undefined : json['limit'],
        'total': json['total'] == null ? undefined : json['total'],
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(ListWorkspaces200ResponseAllOfItemsInnerFromJSON)),
    };
}

export function ListWorkspaces200ResponseToJSON(json: any): ListWorkspaces200Response {
    return ListWorkspaces200ResponseToJSONTyped(json, false);
}

export function ListWorkspaces200ResponseToJSONTyped(value?: ListWorkspaces200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page': value['page'],
        'limit': value['limit'],
        'total': value['total'],
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(ListWorkspaces200ResponseAllOfItemsInnerToJSON)),
    };
}

