/* tslint:disable */
/* eslint-disable */
/**
 * BackedUp API
 * Microservices-based backup and vault management platform with encrypted backups and distributed storage
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListAutoBackup200ResponseAllOfItemsInner
 */
export interface ListAutoBackup200ResponseAllOfItemsInner {
    /**
     * 
     * @type {string}
     * @memberof ListAutoBackup200ResponseAllOfItemsInner
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ListAutoBackup200ResponseAllOfItemsInner
     */
    vault_id?: string;
    /**
     * 
     * @type {string}
     * @memberof ListAutoBackup200ResponseAllOfItemsInner
     */
    workspace_id?: string;
    /**
     * Type of backup execution - 'worker' for cloud-managed, 'agent' for self-hosted
     * @type {string}
     * @memberof ListAutoBackup200ResponseAllOfItemsInner
     */
    type?: ListAutoBackup200ResponseAllOfItemsInnerTypeEnum;
    /**
     * Backup provider type (currently supports HTTP, extensible for future providers)
     * @type {string}
     * @memberof ListAutoBackup200ResponseAllOfItemsInner
     */
    provider?: ListAutoBackup200ResponseAllOfItemsInnerProviderEnum;
    /**
     * Only present when type is 'agent'
     * @type {string}
     * @memberof ListAutoBackup200ResponseAllOfItemsInner
     */
    agent_id?: string;
    /**
     * Only present when type is 'worker'
     * @type {string}
     * @memberof ListAutoBackup200ResponseAllOfItemsInner
     */
    zone?: string;
    /**
     * Cron expression
     * @type {string}
     * @memberof ListAutoBackup200ResponseAllOfItemsInner
     */
    schedule?: string;
    /**
     * Temporal workflow schedule ID
     * @type {string}
     * @memberof ListAutoBackup200ResponseAllOfItemsInner
     */
    temporal_schedule_id?: string;
}


/**
 * @export
 */
export const ListAutoBackup200ResponseAllOfItemsInnerTypeEnum = {
    Worker: 'worker',
    Agent: 'agent'
} as const;
export type ListAutoBackup200ResponseAllOfItemsInnerTypeEnum = typeof ListAutoBackup200ResponseAllOfItemsInnerTypeEnum[keyof typeof ListAutoBackup200ResponseAllOfItemsInnerTypeEnum];

/**
 * @export
 */
export const ListAutoBackup200ResponseAllOfItemsInnerProviderEnum = {
    Http: 'http'
} as const;
export type ListAutoBackup200ResponseAllOfItemsInnerProviderEnum = typeof ListAutoBackup200ResponseAllOfItemsInnerProviderEnum[keyof typeof ListAutoBackup200ResponseAllOfItemsInnerProviderEnum];


/**
 * Check if a given object implements the ListAutoBackup200ResponseAllOfItemsInner interface.
 */
export function instanceOfListAutoBackup200ResponseAllOfItemsInner(value: object): value is ListAutoBackup200ResponseAllOfItemsInner {
    return true;
}

export function ListAutoBackup200ResponseAllOfItemsInnerFromJSON(json: any): ListAutoBackup200ResponseAllOfItemsInner {
    return ListAutoBackup200ResponseAllOfItemsInnerFromJSONTyped(json, false);
}

export function ListAutoBackup200ResponseAllOfItemsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListAutoBackup200ResponseAllOfItemsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'vault_id': json['vault_id'] == null ? undefined : json['vault_id'],
        'workspace_id': json['workspace_id'] == null ? undefined : json['workspace_id'],
        'type': json['type'] == null ? undefined : json['type'],
        'provider': json['provider'] == null ? undefined : json['provider'],
        'agent_id': json['agent_id'] == null ? undefined : json['agent_id'],
        'zone': json['zone'] == null ? undefined : json['zone'],
        'schedule': json['schedule'] == null ? undefined : json['schedule'],
        'temporal_schedule_id': json['temporal_schedule_id'] == null ? undefined : json['temporal_schedule_id'],
    };
}

export function ListAutoBackup200ResponseAllOfItemsInnerToJSON(json: any): ListAutoBackup200ResponseAllOfItemsInner {
    return ListAutoBackup200ResponseAllOfItemsInnerToJSONTyped(json, false);
}

export function ListAutoBackup200ResponseAllOfItemsInnerToJSONTyped(value?: ListAutoBackup200ResponseAllOfItemsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'vault_id': value['vault_id'],
        'workspace_id': value['workspace_id'],
        'type': value['type'],
        'provider': value['provider'],
        'agent_id': value['agent_id'],
        'zone': value['zone'],
        'schedule': value['schedule'],
        'temporal_schedule_id': value['temporal_schedule_id'],
    };
}

