/* tslint:disable */
/* eslint-disable */
/**
 * Saved API
 * Microservices-based backup and vault management platform with encrypted backups and distributed storage
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListWorkspaces401Response
 */
export interface ListWorkspaces401Response {
    /**
     * 
     * @type {string}
     * @memberof ListWorkspaces401Response
     */
    message?: string;
}

/**
 * Check if a given object implements the ListWorkspaces401Response interface.
 */
export function instanceOfListWorkspaces401Response(value: object): value is ListWorkspaces401Response {
    return true;
}

export function ListWorkspaces401ResponseFromJSON(json: any): ListWorkspaces401Response {
    return ListWorkspaces401ResponseFromJSONTyped(json, false);
}

export function ListWorkspaces401ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListWorkspaces401Response {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function ListWorkspaces401ResponseToJSON(json: any): ListWorkspaces401Response {
    return ListWorkspaces401ResponseToJSONTyped(json, false);
}

export function ListWorkspaces401ResponseToJSONTyped(value?: ListWorkspaces401Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

