/* tslint:disable */
/* eslint-disable */
/**
 * Saved API
 * encrypted backups and distributed storage
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListInvoices200ResponseInvoicesInner } from './ListInvoices200ResponseInvoicesInner';
import {
    ListInvoices200ResponseInvoicesInnerFromJSON,
    ListInvoices200ResponseInvoicesInnerFromJSONTyped,
    ListInvoices200ResponseInvoicesInnerToJSON,
    ListInvoices200ResponseInvoicesInnerToJSONTyped,
} from './ListInvoices200ResponseInvoicesInner';

/**
 * 
 * @export
 * @interface ListInvoices200Response
 */
export interface ListInvoices200Response {
    /**
     * 
     * @type {Array<ListInvoices200ResponseInvoicesInner>}
     * @memberof ListInvoices200Response
     */
    invoices?: Array<ListInvoices200ResponseInvoicesInner>;
}

/**
 * Check if a given object implements the ListInvoices200Response interface.
 */
export function instanceOfListInvoices200Response(value: object): value is ListInvoices200Response {
    return true;
}

export function ListInvoices200ResponseFromJSON(json: any): ListInvoices200Response {
    return ListInvoices200ResponseFromJSONTyped(json, false);
}

export function ListInvoices200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListInvoices200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'invoices': json['invoices'] == null ? undefined : ((json['invoices'] as Array<any>).map(ListInvoices200ResponseInvoicesInnerFromJSON)),
    };
}

export function ListInvoices200ResponseToJSON(json: any): ListInvoices200Response {
    return ListInvoices200ResponseToJSONTyped(json, false);
}

export function ListInvoices200ResponseToJSONTyped(value?: ListInvoices200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'invoices': value['invoices'] == null ? undefined : ((value['invoices'] as Array<any>).map(ListInvoices200ResponseInvoicesInnerToJSON)),
    };
}

