/* tslint:disable */
/* eslint-disable */
/**
 * BackedUp API
 * Microservices-based backup and vault management platform with encrypted backups and distributed storage
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListSignals200ResponseAllOfItemsInner } from './ListSignals200ResponseAllOfItemsInner';
import {
    ListSignals200ResponseAllOfItemsInnerFromJSON,
    ListSignals200ResponseAllOfItemsInnerFromJSONTyped,
    ListSignals200ResponseAllOfItemsInnerToJSON,
    ListSignals200ResponseAllOfItemsInnerToJSONTyped,
} from './ListSignals200ResponseAllOfItemsInner';

/**
 * 
 * @export
 * @interface ListSignals200Response
 */
export interface ListSignals200Response {
    /**
     * 
     * @type {number}
     * @memberof ListSignals200Response
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof ListSignals200Response
     */
    limit?: number;
    /**
     * 
     * @type {number}
     * @memberof ListSignals200Response
     */
    total?: number;
    /**
     * 
     * @type {Array<ListSignals200ResponseAllOfItemsInner>}
     * @memberof ListSignals200Response
     */
    items?: Array<ListSignals200ResponseAllOfItemsInner>;
}

/**
 * Check if a given object implements the ListSignals200Response interface.
 */
export function instanceOfListSignals200Response(value: object): value is ListSignals200Response {
    return true;
}

export function ListSignals200ResponseFromJSON(json: any): ListSignals200Response {
    return ListSignals200ResponseFromJSONTyped(json, false);
}

export function ListSignals200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListSignals200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'] == null ? undefined : json['page'],
        'limit': json['limit'] == null ? undefined : json['limit'],
        'total': json['total'] == null ? undefined : json['total'],
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(ListSignals200ResponseAllOfItemsInnerFromJSON)),
    };
}

export function ListSignals200ResponseToJSON(json: any): ListSignals200Response {
    return ListSignals200ResponseToJSONTyped(json, false);
}

export function ListSignals200ResponseToJSONTyped(value?: ListSignals200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page': value['page'],
        'limit': value['limit'],
        'total': value['total'],
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(ListSignals200ResponseAllOfItemsInnerToJSON)),
    };
}

