/* tslint:disable */
/* eslint-disable */
/**
 * Saved API
 * encrypted backups and distributed storage
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListCreditTransactions200ResponseTransactionsInner
 */
export interface ListCreditTransactions200ResponseTransactionsInner {
    /**
     * 
     * @type {string}
     * @memberof ListCreditTransactions200ResponseTransactionsInner
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ListCreditTransactions200ResponseTransactionsInner
     */
    workspace_id?: string;
    /**
     * 
     * @type {number}
     * @memberof ListCreditTransactions200ResponseTransactionsInner
     */
    amount?: number;
    /**
     * 
     * @type {number}
     * @memberof ListCreditTransactions200ResponseTransactionsInner
     */
    balance_after?: number;
    /**
     * 
     * @type {string}
     * @memberof ListCreditTransactions200ResponseTransactionsInner
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof ListCreditTransactions200ResponseTransactionsInner
     */
    type?: string;
    /**
     * 
     * @type {Date}
     * @memberof ListCreditTransactions200ResponseTransactionsInner
     */
    created_at?: Date;
}

/**
 * Check if a given object implements the ListCreditTransactions200ResponseTransactionsInner interface.
 */
export function instanceOfListCreditTransactions200ResponseTransactionsInner(value: object): value is ListCreditTransactions200ResponseTransactionsInner {
    return true;
}

export function ListCreditTransactions200ResponseTransactionsInnerFromJSON(json: any): ListCreditTransactions200ResponseTransactionsInner {
    return ListCreditTransactions200ResponseTransactionsInnerFromJSONTyped(json, false);
}

export function ListCreditTransactions200ResponseTransactionsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListCreditTransactions200ResponseTransactionsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'workspace_id': json['workspace_id'] == null ? undefined : json['workspace_id'],
        'amount': json['amount'] == null ? undefined : json['amount'],
        'balance_after': json['balance_after'] == null ? undefined : json['balance_after'],
        'description': json['description'] == null ? undefined : json['description'],
        'type': json['type'] == null ? undefined : json['type'],
        'created_at': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
    };
}

export function ListCreditTransactions200ResponseTransactionsInnerToJSON(json: any): ListCreditTransactions200ResponseTransactionsInner {
    return ListCreditTransactions200ResponseTransactionsInnerToJSONTyped(json, false);
}

export function ListCreditTransactions200ResponseTransactionsInnerToJSONTyped(value?: ListCreditTransactions200ResponseTransactionsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'workspace_id': value['workspace_id'],
        'amount': value['amount'],
        'balance_after': value['balance_after'],
        'description': value['description'],
        'type': value['type'],
        'created_at': value['created_at'] == null ? undefined : ((value['created_at']).toISOString()),
    };
}

