/* tslint:disable */
/* eslint-disable */
/**
 * Saved API
 * Microservices-based backup and vault management platform with encrypted backups and distributed storage
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListAgents200ResponseAllOfItemsInner } from './ListAgents200ResponseAllOfItemsInner';
import {
    ListAgents200ResponseAllOfItemsInnerFromJSON,
    ListAgents200ResponseAllOfItemsInnerFromJSONTyped,
    ListAgents200ResponseAllOfItemsInnerToJSON,
    ListAgents200ResponseAllOfItemsInnerToJSONTyped,
} from './ListAgents200ResponseAllOfItemsInner';

/**
 * 
 * @export
 * @interface ListAgents200Response
 */
export interface ListAgents200Response {
    /**
     * 
     * @type {number}
     * @memberof ListAgents200Response
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof ListAgents200Response
     */
    limit?: number;
    /**
     * 
     * @type {number}
     * @memberof ListAgents200Response
     */
    total?: number;
    /**
     * 
     * @type {Array<ListAgents200ResponseAllOfItemsInner>}
     * @memberof ListAgents200Response
     */
    items?: Array<ListAgents200ResponseAllOfItemsInner>;
}

/**
 * Check if a given object implements the ListAgents200Response interface.
 */
export function instanceOfListAgents200Response(value: object): value is ListAgents200Response {
    return true;
}

export function ListAgents200ResponseFromJSON(json: any): ListAgents200Response {
    return ListAgents200ResponseFromJSONTyped(json, false);
}

export function ListAgents200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListAgents200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'] == null ? undefined : json['page'],
        'limit': json['limit'] == null ? undefined : json['limit'],
        'total': json['total'] == null ? undefined : json['total'],
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(ListAgents200ResponseAllOfItemsInnerFromJSON)),
    };
}

export function ListAgents200ResponseToJSON(json: any): ListAgents200Response {
    return ListAgents200ResponseToJSONTyped(json, false);
}

export function ListAgents200ResponseToJSONTyped(value?: ListAgents200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page': value['page'],
        'limit': value['limit'],
        'total': value['total'],
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(ListAgents200ResponseAllOfItemsInnerToJSON)),
    };
}

