/* tslint:disable */
/* eslint-disable */
/**
 * Saved API
 * encrypted backups and distributed storage
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ListJobs200ResponseInnerOneOf } from './ListJobs200ResponseInnerOneOf';
import {
    instanceOfListJobs200ResponseInnerOneOf,
    ListJobs200ResponseInnerOneOfFromJSON,
    ListJobs200ResponseInnerOneOfFromJSONTyped,
    ListJobs200ResponseInnerOneOfToJSON,
} from './ListJobs200ResponseInnerOneOf';
import type { ListJobs200ResponseInnerOneOf1 } from './ListJobs200ResponseInnerOneOf1';
import {
    instanceOfListJobs200ResponseInnerOneOf1,
    ListJobs200ResponseInnerOneOf1FromJSON,
    ListJobs200ResponseInnerOneOf1FromJSONTyped,
    ListJobs200ResponseInnerOneOf1ToJSON,
} from './ListJobs200ResponseInnerOneOf1';
import type { ListJobs200ResponseInnerOneOf2 } from './ListJobs200ResponseInnerOneOf2';
import {
    instanceOfListJobs200ResponseInnerOneOf2,
    ListJobs200ResponseInnerOneOf2FromJSON,
    ListJobs200ResponseInnerOneOf2FromJSONTyped,
    ListJobs200ResponseInnerOneOf2ToJSON,
} from './ListJobs200ResponseInnerOneOf2';

/**
 * @type ListJobs200ResponseInner
 * 
 * @export
 */
export type ListJobs200ResponseInner = { type: 'agent' } & ERRORUNKNOWN | { type: 'manual' } & ERRORUNKNOWN | { type: 'worker' } & ERRORUNKNOWN;

export function ListJobs200ResponseInnerFromJSON(json: any): ListJobs200ResponseInner {
    return ListJobs200ResponseInnerFromJSONTyped(json, false);
}

export function ListJobs200ResponseInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListJobs200ResponseInner {
    if (json == null) {
        return json;
    }
    switch (json['type']) {
        case 'agent':
            return Object.assign({}, ERRORUNKNOWNFromJSONTyped(json, true), { type: 'agent' } as const);
        case 'manual':
            return Object.assign({}, ERRORUNKNOWNFromJSONTyped(json, true), { type: 'manual' } as const);
        case 'worker':
            return Object.assign({}, ERRORUNKNOWNFromJSONTyped(json, true), { type: 'worker' } as const);
        default:
            return json;
    }
}

export function ListJobs200ResponseInnerToJSON(json: any): any {
    return ListJobs200ResponseInnerToJSONTyped(json, false);
}

export function ListJobs200ResponseInnerToJSONTyped(value?: ListJobs200ResponseInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    switch (value['type']) {
        case 'agent':
            return Object.assign({}, ERRORUNKNOWNToJSON(value), { type: 'agent' } as const);
        case 'manual':
            return Object.assign({}, ERRORUNKNOWNToJSON(value), { type: 'manual' } as const);
        case 'worker':
            return Object.assign({}, ERRORUNKNOWNToJSON(value), { type: 'worker' } as const);
        default:
            return json;
    }
}

