/* tslint:disable */
/* eslint-disable */
/**
 * Saved API
 * encrypted backups and distributed storage
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListJobs200ResponseInnerOneOf2
 */
export interface ListJobs200ResponseInnerOneOf2 {
    /**
     * 
     * @type {string}
     * @memberof ListJobs200ResponseInnerOneOf2
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ListJobs200ResponseInnerOneOf2
     */
    workspace_id: string;
    /**
     * 
     * @type {boolean}
     * @memberof ListJobs200ResponseInnerOneOf2
     */
    enabled: boolean;
    /**
     * 
     * @type {string}
     * @memberof ListJobs200ResponseInnerOneOf2
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ListJobs200ResponseInnerOneOf2
     */
    type: ListJobs200ResponseInnerOneOf2TypeEnum;
    /**
     * 
     * @type {number}
     * @memberof ListJobs200ResponseInnerOneOf2
     */
    max_backup_count: number;
    /**
     * Duration in nanoseconds
     * @type {number}
     * @memberof ListJobs200ResponseInnerOneOf2
     */
    retention_lock_period: number;
    /**
     * Duration in nanoseconds
     * @type {number}
     * @memberof ListJobs200ResponseInnerOneOf2
     */
    max_backup_age: number;
    /**
     * 
     * @type {number}
     * @memberof ListJobs200ResponseInnerOneOf2
     */
    compression_level: number;
    /**
     * 
     * @type {Date}
     * @memberof ListJobs200ResponseInnerOneOf2
     */
    created_at: Date;
    /**
     * 
     * @type {Date}
     * @memberof ListJobs200ResponseInnerOneOf2
     */
    updated_at: Date;
}


/**
 * @export
 */
export const ListJobs200ResponseInnerOneOf2TypeEnum = {
    Worker: 'worker',
    Agent: 'agent',
    Manual: 'manual'
} as const;
export type ListJobs200ResponseInnerOneOf2TypeEnum = typeof ListJobs200ResponseInnerOneOf2TypeEnum[keyof typeof ListJobs200ResponseInnerOneOf2TypeEnum];


/**
 * Check if a given object implements the ListJobs200ResponseInnerOneOf2 interface.
 */
export function instanceOfListJobs200ResponseInnerOneOf2(value: object): value is ListJobs200ResponseInnerOneOf2 {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('workspace_id' in value) || value['workspace_id'] === undefined) return false;
    if (!('enabled' in value) || value['enabled'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('max_backup_count' in value) || value['max_backup_count'] === undefined) return false;
    if (!('retention_lock_period' in value) || value['retention_lock_period'] === undefined) return false;
    if (!('max_backup_age' in value) || value['max_backup_age'] === undefined) return false;
    if (!('compression_level' in value) || value['compression_level'] === undefined) return false;
    if (!('created_at' in value) || value['created_at'] === undefined) return false;
    if (!('updated_at' in value) || value['updated_at'] === undefined) return false;
    return true;
}

export function ListJobs200ResponseInnerOneOf2FromJSON(json: any): ListJobs200ResponseInnerOneOf2 {
    return ListJobs200ResponseInnerOneOf2FromJSONTyped(json, false);
}

export function ListJobs200ResponseInnerOneOf2FromJSONTyped(json: any, ignoreDiscriminator: boolean): ListJobs200ResponseInnerOneOf2 {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'workspace_id': json['workspace_id'],
        'enabled': json['enabled'],
        'name': json['name'],
        'type': json['type'],
        'max_backup_count': json['max_backup_count'],
        'retention_lock_period': json['retention_lock_period'],
        'max_backup_age': json['max_backup_age'],
        'compression_level': json['compression_level'],
        'created_at': (new Date(json['created_at'])),
        'updated_at': (new Date(json['updated_at'])),
    };
}

export function ListJobs200ResponseInnerOneOf2ToJSON(json: any): ListJobs200ResponseInnerOneOf2 {
    return ListJobs200ResponseInnerOneOf2ToJSONTyped(json, false);
}

export function ListJobs200ResponseInnerOneOf2ToJSONTyped(value?: ListJobs200ResponseInnerOneOf2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'workspace_id': value['workspace_id'],
        'enabled': value['enabled'],
        'name': value['name'],
        'type': value['type'],
        'max_backup_count': value['max_backup_count'],
        'retention_lock_period': value['retention_lock_period'],
        'max_backup_age': value['max_backup_age'],
        'compression_level': value['compression_level'],
        'created_at': ((value['created_at']).toISOString()),
        'updated_at': ((value['updated_at']).toISOString()),
    };
}

