/* tslint:disable */
/* eslint-disable */
/**
 * Saved API
 * encrypted backups and distributed storage
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListAgents200ResponseInner
 */
export interface ListAgents200ResponseInner {
    /**
     * The unique identifier of the agent.
     * @type {string}
     * @memberof ListAgents200ResponseInner
     */
    id?: string;
    /**
     * The unique identifier of the workspace the agent belongs to.
     * @type {string}
     * @memberof ListAgents200ResponseInner
     */
    workspace_id?: string;
    /**
     * The provider user ID associated with the agent.
     * @type {string}
     * @memberof ListAgents200ResponseInner
     */
    provider_user_id?: string;
    /**
     * The username of the agent.
     * @type {string}
     * @memberof ListAgents200ResponseInner
     */
    username?: string;
    /**
     * The name of the agent.
     * @type {string}
     * @memberof ListAgents200ResponseInner
     */
    name?: string;
    /**
     * The description of the agent.
     * @type {string}
     * @memberof ListAgents200ResponseInner
     */
    description?: string;
    /**
     * The status of the agent.
     * @type {string}
     * @memberof ListAgents200ResponseInner
     */
    status?: string;
    /**
     * The password for the agent.
     * @type {string}
     * @memberof ListAgents200ResponseInner
     */
    password?: string;
    /**
     * The grant type for the agent.
     * @type {string}
     * @memberof ListAgents200ResponseInner
     */
    grant_type?: string;
    /**
     * The client ID for the agent.
     * @type {string}
     * @memberof ListAgents200ResponseInner
     */
    client_id?: string;
    /**
     * The audience for the agent.
     * @type {string}
     * @memberof ListAgents200ResponseInner
     */
    audience?: string;
    /**
     * The realm for the agent.
     * @type {string}
     * @memberof ListAgents200ResponseInner
     */
    realm?: string;
    /**
     * The scope of permissions for the agent.
     * @type {string}
     * @memberof ListAgents200ResponseInner
     */
    scope?: string;
    /**
     * The timestamp when the agent was created.
     * @type {Date}
     * @memberof ListAgents200ResponseInner
     */
    created_at?: Date;
    /**
     * The timestamp when the agent was last updated.
     * @type {Date}
     * @memberof ListAgents200ResponseInner
     */
    updated_at?: Date;
}

/**
 * Check if a given object implements the ListAgents200ResponseInner interface.
 */
export function instanceOfListAgents200ResponseInner(value: object): value is ListAgents200ResponseInner {
    return true;
}

export function ListAgents200ResponseInnerFromJSON(json: any): ListAgents200ResponseInner {
    return ListAgents200ResponseInnerFromJSONTyped(json, false);
}

export function ListAgents200ResponseInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListAgents200ResponseInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'workspace_id': json['workspace_id'] == null ? undefined : json['workspace_id'],
        'provider_user_id': json['provider_user_id'] == null ? undefined : json['provider_user_id'],
        'username': json['username'] == null ? undefined : json['username'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'status': json['status'] == null ? undefined : json['status'],
        'password': json['password'] == null ? undefined : json['password'],
        'grant_type': json['grant_type'] == null ? undefined : json['grant_type'],
        'client_id': json['client_id'] == null ? undefined : json['client_id'],
        'audience': json['audience'] == null ? undefined : json['audience'],
        'realm': json['realm'] == null ? undefined : json['realm'],
        'scope': json['scope'] == null ? undefined : json['scope'],
        'created_at': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updated_at': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
    };
}

export function ListAgents200ResponseInnerToJSON(json: any): ListAgents200ResponseInner {
    return ListAgents200ResponseInnerToJSONTyped(json, false);
}

export function ListAgents200ResponseInnerToJSONTyped(value?: ListAgents200ResponseInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'workspace_id': value['workspace_id'],
        'provider_user_id': value['provider_user_id'],
        'username': value['username'],
        'name': value['name'],
        'description': value['description'],
        'status': value['status'],
        'password': value['password'],
        'grant_type': value['grant_type'],
        'client_id': value['client_id'],
        'audience': value['audience'],
        'realm': value['realm'],
        'scope': value['scope'],
        'created_at': value['created_at'] == null ? undefined : ((value['created_at']).toISOString()),
        'updated_at': value['updated_at'] == null ? undefined : ((value['updated_at']).toISOString()),
    };
}

