/* tslint:disable */
/* eslint-disable */
/**
 * Saved API
 * Microservices-based backup and vault management platform with encrypted backups and distributed storage
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListSignals200ResponseAllOfItemsInner
 */
export interface ListSignals200ResponseAllOfItemsInner {
    /**
     * 
     * @type {string}
     * @memberof ListSignals200ResponseAllOfItemsInner
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ListSignals200ResponseAllOfItemsInner
     */
    workspace_id?: string;
    /**
     * 
     * @type {Date}
     * @memberof ListSignals200ResponseAllOfItemsInner
     */
    created_at?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ListSignals200ResponseAllOfItemsInner
     */
    updated_at?: Date;
    /**
     * 
     * @type {string}
     * @memberof ListSignals200ResponseAllOfItemsInner
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ListSignals200ResponseAllOfItemsInner
     */
    provider?: ListSignals200ResponseAllOfItemsInnerProviderEnum;
}


/**
 * @export
 */
export const ListSignals200ResponseAllOfItemsInnerProviderEnum = {
    Email: 'email',
    Webhook: 'webhook'
} as const;
export type ListSignals200ResponseAllOfItemsInnerProviderEnum = typeof ListSignals200ResponseAllOfItemsInnerProviderEnum[keyof typeof ListSignals200ResponseAllOfItemsInnerProviderEnum];


/**
 * Check if a given object implements the ListSignals200ResponseAllOfItemsInner interface.
 */
export function instanceOfListSignals200ResponseAllOfItemsInner(value: object): value is ListSignals200ResponseAllOfItemsInner {
    return true;
}

export function ListSignals200ResponseAllOfItemsInnerFromJSON(json: any): ListSignals200ResponseAllOfItemsInner {
    return ListSignals200ResponseAllOfItemsInnerFromJSONTyped(json, false);
}

export function ListSignals200ResponseAllOfItemsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListSignals200ResponseAllOfItemsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'workspace_id': json['workspace_id'] == null ? undefined : json['workspace_id'],
        'created_at': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updated_at': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'name': json['name'] == null ? undefined : json['name'],
        'provider': json['provider'] == null ? undefined : json['provider'],
    };
}

export function ListSignals200ResponseAllOfItemsInnerToJSON(json: any): ListSignals200ResponseAllOfItemsInner {
    return ListSignals200ResponseAllOfItemsInnerToJSONTyped(json, false);
}

export function ListSignals200ResponseAllOfItemsInnerToJSONTyped(value?: ListSignals200ResponseAllOfItemsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'workspace_id': value['workspace_id'],
        'created_at': value['created_at'] == null ? undefined : ((value['created_at']).toISOString()),
        'updated_at': value['updated_at'] == null ? undefined : ((value['updated_at']).toISOString()),
        'name': value['name'],
        'provider': value['provider'],
    };
}

