/* tslint:disable */
/* eslint-disable */
/**
 * Saved API
 * encrypted backups and distributed storage
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListJobs200ResponseInnerOneOf
 */
export interface ListJobs200ResponseInnerOneOf {
    /**
     * 
     * @type {string}
     * @memberof ListJobs200ResponseInnerOneOf
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ListJobs200ResponseInnerOneOf
     */
    workspace_id: string;
    /**
     * 
     * @type {boolean}
     * @memberof ListJobs200ResponseInnerOneOf
     */
    enabled: boolean;
    /**
     * 
     * @type {string}
     * @memberof ListJobs200ResponseInnerOneOf
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ListJobs200ResponseInnerOneOf
     */
    type: ListJobs200ResponseInnerOneOfTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof ListJobs200ResponseInnerOneOf
     */
    provider: ListJobs200ResponseInnerOneOfProviderEnum;
    /**
     * Cron schedule expression
     * @type {string}
     * @memberof ListJobs200ResponseInnerOneOf
     */
    schedule: string;
    /**
     * 
     * @type {number}
     * @memberof ListJobs200ResponseInnerOneOf
     */
    max_backup_count: number;
    /**
     * Duration in nanoseconds
     * @type {number}
     * @memberof ListJobs200ResponseInnerOneOf
     */
    retention_lock_period: number;
    /**
     * Duration in nanoseconds
     * @type {number}
     * @memberof ListJobs200ResponseInnerOneOf
     */
    max_backup_age: number;
    /**
     * 
     * @type {number}
     * @memberof ListJobs200ResponseInnerOneOf
     */
    compression_level: number;
    /**
     * Temporal workflow schedule ID
     * @type {string}
     * @memberof ListJobs200ResponseInnerOneOf
     */
    temporal_schedule_id: string;
    /**
     * 
     * @type {Date}
     * @memberof ListJobs200ResponseInnerOneOf
     */
    created_at: Date;
    /**
     * 
     * @type {Date}
     * @memberof ListJobs200ResponseInnerOneOf
     */
    updated_at: Date;
}


/**
 * @export
 */
export const ListJobs200ResponseInnerOneOfTypeEnum = {
    Worker: 'worker',
    Agent: 'agent',
    Manual: 'manual'
} as const;
export type ListJobs200ResponseInnerOneOfTypeEnum = typeof ListJobs200ResponseInnerOneOfTypeEnum[keyof typeof ListJobs200ResponseInnerOneOfTypeEnum];

/**
 * @export
 */
export const ListJobs200ResponseInnerOneOfProviderEnum = {
    Http: 'http',
    Ftp: 'ftp',
    Webdav: 'webdav',
    Git: 'git',
    AwsS3: 'aws.s3',
    AwsDynamodb: 'aws.dynamodb',
    Mysql: 'mysql',
    Postgres: 'postgres',
    Mssql: 'mssql',
    Redis: 'redis'
} as const;
export type ListJobs200ResponseInnerOneOfProviderEnum = typeof ListJobs200ResponseInnerOneOfProviderEnum[keyof typeof ListJobs200ResponseInnerOneOfProviderEnum];


/**
 * Check if a given object implements the ListJobs200ResponseInnerOneOf interface.
 */
export function instanceOfListJobs200ResponseInnerOneOf(value: object): value is ListJobs200ResponseInnerOneOf {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('workspace_id' in value) || value['workspace_id'] === undefined) return false;
    if (!('enabled' in value) || value['enabled'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('provider' in value) || value['provider'] === undefined) return false;
    if (!('schedule' in value) || value['schedule'] === undefined) return false;
    if (!('max_backup_count' in value) || value['max_backup_count'] === undefined) return false;
    if (!('retention_lock_period' in value) || value['retention_lock_period'] === undefined) return false;
    if (!('max_backup_age' in value) || value['max_backup_age'] === undefined) return false;
    if (!('compression_level' in value) || value['compression_level'] === undefined) return false;
    if (!('temporal_schedule_id' in value) || value['temporal_schedule_id'] === undefined) return false;
    if (!('created_at' in value) || value['created_at'] === undefined) return false;
    if (!('updated_at' in value) || value['updated_at'] === undefined) return false;
    return true;
}

export function ListJobs200ResponseInnerOneOfFromJSON(json: any): ListJobs200ResponseInnerOneOf {
    return ListJobs200ResponseInnerOneOfFromJSONTyped(json, false);
}

export function ListJobs200ResponseInnerOneOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListJobs200ResponseInnerOneOf {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'workspace_id': json['workspace_id'],
        'enabled': json['enabled'],
        'name': json['name'],
        'type': json['type'],
        'provider': json['provider'],
        'schedule': json['schedule'],
        'max_backup_count': json['max_backup_count'],
        'retention_lock_period': json['retention_lock_period'],
        'max_backup_age': json['max_backup_age'],
        'compression_level': json['compression_level'],
        'temporal_schedule_id': json['temporal_schedule_id'],
        'created_at': (new Date(json['created_at'])),
        'updated_at': (new Date(json['updated_at'])),
    };
}

export function ListJobs200ResponseInnerOneOfToJSON(json: any): ListJobs200ResponseInnerOneOf {
    return ListJobs200ResponseInnerOneOfToJSONTyped(json, false);
}

export function ListJobs200ResponseInnerOneOfToJSONTyped(value?: ListJobs200ResponseInnerOneOf | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'workspace_id': value['workspace_id'],
        'enabled': value['enabled'],
        'name': value['name'],
        'type': value['type'],
        'provider': value['provider'],
        'schedule': value['schedule'],
        'max_backup_count': value['max_backup_count'],
        'retention_lock_period': value['retention_lock_period'],
        'max_backup_age': value['max_backup_age'],
        'compression_level': value['compression_level'],
        'temporal_schedule_id': value['temporal_schedule_id'],
        'created_at': ((value['created_at']).toISOString()),
        'updated_at': ((value['updated_at']).toISOString()),
    };
}

