/* tslint:disable */
/* eslint-disable */
/**
 * Saved API
 * Microservices-based backup and vault management platform with encrypted backups and distributed storage
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RequestBackupCopy200Response
 */
export interface RequestBackupCopy200Response {
    /**
     * Presigned URL for downloading the backup (expires in 24 hours)
     * @type {string}
     * @memberof RequestBackupCopy200Response
     */
    url: string;
}

/**
 * Check if a given object implements the RequestBackupCopy200Response interface.
 */
export function instanceOfRequestBackupCopy200Response(value: object): value is RequestBackupCopy200Response {
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function RequestBackupCopy200ResponseFromJSON(json: any): RequestBackupCopy200Response {
    return RequestBackupCopy200ResponseFromJSONTyped(json, false);
}

export function RequestBackupCopy200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestBackupCopy200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'],
    };
}

export function RequestBackupCopy200ResponseToJSON(json: any): RequestBackupCopy200Response {
    return RequestBackupCopy200ResponseToJSONTyped(json, false);
}

export function RequestBackupCopy200ResponseToJSONTyped(value?: RequestBackupCopy200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
    };
}

