/* tslint:disable */
/* eslint-disable */
/**
 * Saved API
 * encrypted backups and distributed storage
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RequestBackup201Response
 */
export interface RequestBackup201Response {
    /**
     * 
     * @type {string}
     * @memberof RequestBackup201Response
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof RequestBackup201Response
     */
    workspace_id?: string;
    /**
     * 
     * @type {string}
     * @memberof RequestBackup201Response
     */
    job_id?: string;
    /**
     * 
     * @type {string}
     * @memberof RequestBackup201Response
     */
    status?: string;
    /**
     * 
     * @type {Date}
     * @memberof RequestBackup201Response
     */
    started_at?: Date;
    /**
     * 
     * @type {Date}
     * @memberof RequestBackup201Response
     */
    completed_at?: Date;
    /**
     * 
     * @type {Date}
     * @memberof RequestBackup201Response
     */
    created_at?: Date;
    /**
     * 
     * @type {Date}
     * @memberof RequestBackup201Response
     */
    updated_at?: Date;
}

/**
 * Check if a given object implements the RequestBackup201Response interface.
 */
export function instanceOfRequestBackup201Response(value: object): value is RequestBackup201Response {
    return true;
}

export function RequestBackup201ResponseFromJSON(json: any): RequestBackup201Response {
    return RequestBackup201ResponseFromJSONTyped(json, false);
}

export function RequestBackup201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestBackup201Response {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'workspace_id': json['workspace_id'] == null ? undefined : json['workspace_id'],
        'job_id': json['job_id'] == null ? undefined : json['job_id'],
        'status': json['status'] == null ? undefined : json['status'],
        'started_at': json['started_at'] == null ? undefined : (new Date(json['started_at'])),
        'completed_at': json['completed_at'] == null ? undefined : (new Date(json['completed_at'])),
        'created_at': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updated_at': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
    };
}

export function RequestBackup201ResponseToJSON(json: any): RequestBackup201Response {
    return RequestBackup201ResponseToJSONTyped(json, false);
}

export function RequestBackup201ResponseToJSONTyped(value?: RequestBackup201Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'workspace_id': value['workspace_id'],
        'job_id': value['job_id'],
        'status': value['status'],
        'started_at': value['started_at'] == null ? undefined : ((value['started_at']).toISOString()),
        'completed_at': value['completed_at'] == null ? undefined : ((value['completed_at']).toISOString()),
        'created_at': value['created_at'] == null ? undefined : ((value['created_at']).toISOString()),
        'updated_at': value['updated_at'] == null ? undefined : ((value['updated_at']).toISOString()),
    };
}

