/* tslint:disable */
/* eslint-disable */
/**
 * BackedUp API
 * Microservices-based backup and vault management platform with encrypted backups and distributed storage
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SetProjectEncryptionKey
 */
export interface SetProjectEncryptionKey {
    /**
     * 
     * @type {string}
     * @memberof SetProjectEncryptionKey
     */
    client_encryption_key_id: string;
}

/**
 * Check if a given object implements the SetProjectEncryptionKey interface.
 */
export function instanceOfSetProjectEncryptionKey(value: object): value is SetProjectEncryptionKey {
    if (!('client_encryption_key_id' in value) || value['client_encryption_key_id'] === undefined) return false;
    return true;
}

export function SetProjectEncryptionKeyFromJSON(json: any): SetProjectEncryptionKey {
    return SetProjectEncryptionKeyFromJSONTyped(json, false);
}

export function SetProjectEncryptionKeyFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetProjectEncryptionKey {
    if (json == null) {
        return json;
    }
    return {
        
        'client_encryption_key_id': json['client_encryption_key_id'],
    };
}

export function SetProjectEncryptionKeyToJSON(json: any): SetProjectEncryptionKey {
    return SetProjectEncryptionKeyToJSONTyped(json, false);
}

export function SetProjectEncryptionKeyToJSONTyped(value?: SetProjectEncryptionKey | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'client_encryption_key_id': value['client_encryption_key_id'],
    };
}

