/* tslint:disable */
/* eslint-disable */
/**
 * Saved API
 * encrypted backups and distributed storage
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TriggerJob202Response
 */
export interface TriggerJob202Response {
    /**
     * 
     * @type {string}
     * @memberof TriggerJob202Response
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof TriggerJob202Response
     */
    workflow_id?: string;
}

/**
 * Check if a given object implements the TriggerJob202Response interface.
 */
export function instanceOfTriggerJob202Response(value: object): value is TriggerJob202Response {
    return true;
}

export function TriggerJob202ResponseFromJSON(json: any): TriggerJob202Response {
    return TriggerJob202ResponseFromJSONTyped(json, false);
}

export function TriggerJob202ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TriggerJob202Response {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'workflow_id': json['workflow_id'] == null ? undefined : json['workflow_id'],
    };
}

export function TriggerJob202ResponseToJSON(json: any): TriggerJob202Response {
    return TriggerJob202ResponseToJSONTyped(json, false);
}

export function TriggerJob202ResponseToJSONTyped(value?: TriggerJob202Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'workflow_id': value['workflow_id'],
    };
}

