/* tslint:disable */
/* eslint-disable */
/**
 * BackedUp API
 * Microservices-based backup and vault management platform with encrypted backups and distributed storage
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateClientStorageJson
 */
export interface UpdateClientStorageJson {
    /**
     * 
     * @type {string}
     * @memberof UpdateClientStorageJson
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateClientStorageJson
     */
    provider?: UpdateClientStorageJsonProviderEnum;
    /**
     * 
     * @type {object}
     * @memberof UpdateClientStorageJson
     */
    config?: object;
}


/**
 * @export
 */
export const UpdateClientStorageJsonProviderEnum = {
    S3: 's3',
    Ftp: 'ftp'
} as const;
export type UpdateClientStorageJsonProviderEnum = typeof UpdateClientStorageJsonProviderEnum[keyof typeof UpdateClientStorageJsonProviderEnum];


/**
 * Check if a given object implements the UpdateClientStorageJson interface.
 */
export function instanceOfUpdateClientStorageJson(value: object): value is UpdateClientStorageJson {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function UpdateClientStorageJsonFromJSON(json: any): UpdateClientStorageJson {
    return UpdateClientStorageJsonFromJSONTyped(json, false);
}

export function UpdateClientStorageJsonFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateClientStorageJson {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'provider': json['provider'] == null ? undefined : json['provider'],
        'config': json['config'] == null ? undefined : json['config'],
    };
}

export function UpdateClientStorageJsonToJSON(json: any): UpdateClientStorageJson {
    return UpdateClientStorageJsonToJSONTyped(json, false);
}

export function UpdateClientStorageJsonToJSONTyped(value?: UpdateClientStorageJson | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'provider': value['provider'],
        'config': value['config'],
    };
}

