/* tslint:disable */
/* eslint-disable */
/**
 * Saved API
 * encrypted backups and distributed storage
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateAgentRequest
 */
export interface UpdateAgentRequest {
    /**
     * The new name of the agent.
     * @type {string}
     * @memberof UpdateAgentRequest
     */
    name?: string;
    /**
     * The new description of the agent.
     * @type {string}
     * @memberof UpdateAgentRequest
     */
    description?: string;
}

/**
 * Check if a given object implements the UpdateAgentRequest interface.
 */
export function instanceOfUpdateAgentRequest(value: object): value is UpdateAgentRequest {
    return true;
}

export function UpdateAgentRequestFromJSON(json: any): UpdateAgentRequest {
    return UpdateAgentRequestFromJSONTyped(json, false);
}

export function UpdateAgentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateAgentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function UpdateAgentRequestToJSON(json: any): UpdateAgentRequest {
    return UpdateAgentRequestToJSONTyped(json, false);
}

export function UpdateAgentRequestToJSONTyped(value?: UpdateAgentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
    };
}

