/* tslint:disable */
/* eslint-disable */
/**
 * BackedUp API
 * Microservices-based backup and vault management platform with encrypted backups and distributed storage
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateClientAgent
 */
export interface UpdateClientAgent {
    /**
     * 
     * @type {string}
     * @memberof UpdateClientAgent
     */
    name: string;
}

/**
 * Check if a given object implements the UpdateClientAgent interface.
 */
export function instanceOfUpdateClientAgent(value: object): value is UpdateClientAgent {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function UpdateClientAgentFromJSON(json: any): UpdateClientAgent {
    return UpdateClientAgentFromJSONTyped(json, false);
}

export function UpdateClientAgentFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateClientAgent {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function UpdateClientAgentToJSON(json: any): UpdateClientAgent {
    return UpdateClientAgentToJSONTyped(json, false);
}

export function UpdateClientAgentToJSONTyped(value?: UpdateClientAgent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

