/* tslint:disable */
/* eslint-disable */
/**
 * BackedUp API
 * Microservices-based backup and vault management platform with encrypted backups and distributed storage
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateClientEncryptionKey
 */
export interface UpdateClientEncryptionKey {
    /**
     * 
     * @type {string}
     * @memberof UpdateClientEncryptionKey
     */
    name: string;
}

/**
 * Check if a given object implements the UpdateClientEncryptionKey interface.
 */
export function instanceOfUpdateClientEncryptionKey(value: object): value is UpdateClientEncryptionKey {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function UpdateClientEncryptionKeyFromJSON(json: any): UpdateClientEncryptionKey {
    return UpdateClientEncryptionKeyFromJSONTyped(json, false);
}

export function UpdateClientEncryptionKeyFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateClientEncryptionKey {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function UpdateClientEncryptionKeyToJSON(json: any): UpdateClientEncryptionKey {
    return UpdateClientEncryptionKeyToJSONTyped(json, false);
}

export function UpdateClientEncryptionKeyToJSONTyped(value?: UpdateClientEncryptionKey | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

