/* tslint:disable */
/* eslint-disable */
/**
 * Saved API
 * encrypted backups and distributed storage
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateJobRequest
 */
export interface UpdateJobRequest {
    /**
     * 
     * @type {boolean}
     * @memberof UpdateJobRequest
     */
    enabled?: boolean;
    /**
     * 
     * @type {string}
     * @memberof UpdateJobRequest
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateJobRequest
     */
    schedule?: string;
}

/**
 * Check if a given object implements the UpdateJobRequest interface.
 */
export function instanceOfUpdateJobRequest(value: object): value is UpdateJobRequest {
    return true;
}

export function UpdateJobRequestFromJSON(json: any): UpdateJobRequest {
    return UpdateJobRequestFromJSONTyped(json, false);
}

export function UpdateJobRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateJobRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
        'name': json['name'] == null ? undefined : json['name'],
        'schedule': json['schedule'] == null ? undefined : json['schedule'],
    };
}

export function UpdateJobRequestToJSON(json: any): UpdateJobRequest {
    return UpdateJobRequestToJSONTyped(json, false);
}

export function UpdateJobRequestToJSONTyped(value?: UpdateJobRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'enabled': value['enabled'],
        'name': value['name'],
        'schedule': value['schedule'],
    };
}

