/* tslint:disable */
/* eslint-disable */
/**
 * BackedUp API
 * Microservices-based backup and vault management platform with encrypted backups and distributed storage
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateProject
 */
export interface UpdateProject {
    /**
     * 
     * @type {string}
     * @memberof UpdateProject
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof UpdateProject
     */
    retention_lock_period?: number;
    /**
     * 
     * @type {number}
     * @memberof UpdateProject
     */
    max_backup_count?: number;
    /**
     * 
     * @type {number}
     * @memberof UpdateProject
     */
    max_backup_age?: number;
    /**
     * 
     * @type {number}
     * @memberof UpdateProject
     */
    compression_level?: number;
}

/**
 * Check if a given object implements the UpdateProject interface.
 */
export function instanceOfUpdateProject(value: object): value is UpdateProject {
    return true;
}

export function UpdateProjectFromJSON(json: any): UpdateProject {
    return UpdateProjectFromJSONTyped(json, false);
}

export function UpdateProjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateProject {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'retention_lock_period': json['retention_lock_period'] == null ? undefined : json['retention_lock_period'],
        'max_backup_count': json['max_backup_count'] == null ? undefined : json['max_backup_count'],
        'max_backup_age': json['max_backup_age'] == null ? undefined : json['max_backup_age'],
        'compression_level': json['compression_level'] == null ? undefined : json['compression_level'],
    };
}

export function UpdateProjectToJSON(json: any): UpdateProject {
    return UpdateProjectToJSONTyped(json, false);
}

export function UpdateProjectToJSONTyped(value?: UpdateProject | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'retention_lock_period': value['retention_lock_period'],
        'max_backup_count': value['max_backup_count'],
        'max_backup_age': value['max_backup_age'],
        'compression_level': value['compression_level'],
    };
}

