/* tslint:disable */
/* eslint-disable */
/**
 * Saved API
 * encrypted backups and distributed storage
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UploadBackup200Response
 */
export interface UploadBackup200Response {
    /**
     * Pre-signed URL for uploading the backup
     * @type {string}
     * @memberof UploadBackup200Response
     */
    upload_url: string;
    /**
     * When the upload URL expires
     * @type {Date}
     * @memberof UploadBackup200Response
     */
    expires_at: Date;
}

/**
 * Check if a given object implements the UploadBackup200Response interface.
 */
export function instanceOfUploadBackup200Response(value: object): value is UploadBackup200Response {
    if (!('upload_url' in value) || value['upload_url'] === undefined) return false;
    if (!('expires_at' in value) || value['expires_at'] === undefined) return false;
    return true;
}

export function UploadBackup200ResponseFromJSON(json: any): UploadBackup200Response {
    return UploadBackup200ResponseFromJSONTyped(json, false);
}

export function UploadBackup200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UploadBackup200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'upload_url': json['upload_url'],
        'expires_at': (new Date(json['expires_at'])),
    };
}

export function UploadBackup200ResponseToJSON(json: any): UploadBackup200Response {
    return UploadBackup200ResponseToJSONTyped(json, false);
}

export function UploadBackup200ResponseToJSONTyped(value?: UploadBackup200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'upload_url': value['upload_url'],
        'expires_at': ((value['expires_at']).toISOString()),
    };
}

