/* tslint:disable */
/* eslint-disable */
/**
 * Saved API
 * encrypted backups and distributed storage
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UploadBackupRequest
 */
export interface UploadBackupRequest {
    /**
     * 
     * @type {string}
     * @memberof UploadBackupRequest
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof UploadBackupRequest
     */
    size: number;
    /**
     * 
     * @type {string}
     * @memberof UploadBackupRequest
     */
    checksum: string;
    /**
     * 
     * @type {string}
     * @memberof UploadBackupRequest
     */
    mime_type: string;
}

/**
 * Check if a given object implements the UploadBackupRequest interface.
 */
export function instanceOfUploadBackupRequest(value: object): value is UploadBackupRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('size' in value) || value['size'] === undefined) return false;
    if (!('checksum' in value) || value['checksum'] === undefined) return false;
    if (!('mime_type' in value) || value['mime_type'] === undefined) return false;
    return true;
}

export function UploadBackupRequestFromJSON(json: any): UploadBackupRequest {
    return UploadBackupRequestFromJSONTyped(json, false);
}

export function UploadBackupRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UploadBackupRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'size': json['size'],
        'checksum': json['checksum'],
        'mime_type': json['mime_type'],
    };
}

export function UploadBackupRequestToJSON(json: any): UploadBackupRequest {
    return UploadBackupRequestToJSONTyped(json, false);
}

export function UploadBackupRequestToJSONTyped(value?: UploadBackupRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'size': value['size'],
        'checksum': value['checksum'],
        'mime_type': value['mime_type'],
    };
}

