/* tslint:disable */
/* eslint-disable */
/**
 * BackedUp API
 * Microservices-based backup and vault management platform with encrypted backups and distributed storage
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WorkflowExecution
 */
export interface WorkflowExecution {
    /**
     * Temporal workflow ID
     * @type {string}
     * @memberof WorkflowExecution
     */
    workflow_id?: string;
    /**
     * Temporal run ID
     * @type {string}
     * @memberof WorkflowExecution
     */
    run_id?: string;
    /**
     * Execution status (e.g., Running, Completed, Failed)
     * @type {string}
     * @memberof WorkflowExecution
     */
    status?: string;
    /**
     * 
     * @type {Date}
     * @memberof WorkflowExecution
     */
    start_time?: Date;
    /**
     * 
     * @type {Date}
     * @memberof WorkflowExecution
     */
    close_time?: Date;
    /**
     * Execution duration in milliseconds
     * @type {number}
     * @memberof WorkflowExecution
     */
    execution_time?: number;
}

/**
 * Check if a given object implements the WorkflowExecution interface.
 */
export function instanceOfWorkflowExecution(value: object): value is WorkflowExecution {
    return true;
}

export function WorkflowExecutionFromJSON(json: any): WorkflowExecution {
    return WorkflowExecutionFromJSONTyped(json, false);
}

export function WorkflowExecutionFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkflowExecution {
    if (json == null) {
        return json;
    }
    return {
        
        'workflow_id': json['workflow_id'] == null ? undefined : json['workflow_id'],
        'run_id': json['run_id'] == null ? undefined : json['run_id'],
        'status': json['status'] == null ? undefined : json['status'],
        'start_time': json['start_time'] == null ? undefined : (new Date(json['start_time'])),
        'close_time': json['close_time'] == null ? undefined : (new Date(json['close_time'])),
        'execution_time': json['execution_time'] == null ? undefined : json['execution_time'],
    };
}

export function WorkflowExecutionToJSON(json: any): WorkflowExecution {
    return WorkflowExecutionToJSONTyped(json, false);
}

export function WorkflowExecutionToJSONTyped(value?: WorkflowExecution | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'workflow_id': value['workflow_id'],
        'run_id': value['run_id'],
        'status': value['status'],
        'start_time': value['start_time'] == null ? undefined : ((value['start_time']).toISOString()),
        'close_time': value['close_time'] == null ? undefined : ((value['close_time']).toISOString()),
        'execution_time': value['execution_time'],
    };
}

